//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by XTPCommandBarsResource.rc
//
// This file is a part of the XTREME COMMANDBARS MFC class library.
// (c)1998-2007 Codejock Software, All Rights Reserved.
//
// THIS SOURCE FILE IS THE PROPERTY OF CODEJOCK SOFTWARE AND IS NOT TO BE
// RE-DISTRIBUTED BY ANY MEANS WHATSOEVER WITHOUT THE EXPRESSED WRITTEN
// CONSENT OF CODEJOCK SOFTWARE.
//
// THIS SOURCE CODE CAN ONLY BE USED UNDER THE TERMS AND CONDITIONS OUTLINED
// IN THE XTREME TOOLKIT PRO LICENSE AGREEMENT. CODEJOCK SOFTWARE GRANTS TO
// YOU (ONE SOFTWARE DEVELOPER) THE LIMITED RIGHT TO USE THIS SOFTWARE ON A
// SINGLE COMPUTER.
//
// CONTACT INFORMATION:
// support@codejock.com
// http://www.codejock.com
//
/////////////////////////////////////////////////////////////////////////////

#define XTP_COMMANDBARS_RESOURCE_FIRST  9100
#define XTP_COMMANDBARS_RESOURCE_LAST   9299

#define XTP_IDB_TOOLBAR_TOOLS           9100
#define XTP_IDB_TOOLBAR_TOOLS32         9101
#define XTP_IDB_MENUBAR_ICONS           9102
#define XTP_IDB_CUSTOMIZE_ICONS         9103
#define XTP_IDB_WORKSPACE_ICONS         9104

#define XTP_IDC_COMMANDBARS_DRAGCOPY    9105
#define XTP_IDC_COMMANDBARS_DRAGMOVE    9106
#define XTP_IDC_COMMANDBARS_DRAGDELETE  9107
#define XTP_IDC_WORKSPACE_NEW           9108
#define XTP_IDC_WORKSPACE_DELETE        9109
#define XTP_IDC_COMMANDBARS_LINE        9110
#define XTP_IDC_COMMANDBARS_PICKCOLOR   9111
#define XTP_IDC_COMMANDBARS_FILLCOLOR   9112
#define XTP_IDC_COMMANDBARS_PENCIL      9113

//////////////////////////////////////////////////////////////////////////
#define XTP_IDD_PAGE_MENUS              9114
#define XTP_IDC_STATIC_APPLICATIONMENUS 100
#define XTP_IDC_STATIC_CONTEXTMENUS     101
#define XTP_IDC_COMBO_APPMENUS          102
#define XTP_IDC_BUTTON_RESETAPP         103
#define XTP_IDC_COMBO_CONTEXTMENUS      104
#define XTP_IDC_BUTTON_RESETCONTEXT     105
#define XTP_IDC_STATIC_DESCRIPTION      106
#define XTP_IDC_STATIC_ICON             107

#define XTP_IDD_IMAGEEDITOR_DIALOG      9115
#define XTP_IDC_STATIC_PICTURE          100
#define XTP_IDC_STATIC_PREVIEW          101
#define XTP_IDC_STATIC_COLORS           102
#define XTP_IDC_STATIC_TOOLS            103
#define XTP_IDC_STATIC_MOVE             104
#define XTP_IDC_CLR_ERASE               105
#define XTP_IDC_CLR_PICKER              106
#define XTP_IDC_BUTTON_LEFT             107
#define XTP_IDC_BUTTON_DOWN             108
#define XTP_IDC_BUTTON_UP               109
#define XTP_IDC_BUTTON_RIGHT            110

#define XTP_IDD_PAGE_KEYBOARD           9116
#define XTP_IDC_COMBO_CATEGORY          100
#define XTP_IDC_TXT_COMMANDS            101
#define XTP_IDC_LBOX_ACCEL_COMMANDS     102
#define XTP_IDC_TXT_ASSIGNMENTS         103
#define XTP_IDC_LBOX_KEYS               104
#define XTP_IDC_TXT_NEWKEY              105
#define XTP_IDC_EDIT_SHORTCUTKEY        106
#define XTP_IDC_BTN_ASSIGN              107
#define XTP_IDC_BTN_REMOVE              108
#define XTP_IDC_BTN_ACCEL_RESET         109
#define XTP_IDC_TXT_DESC_TITLE          110
#define XTP_IDC_TXT_DESC_OVERVIEW       111

#define XTP_IDD_PAGE_TOOLBARS           9117
#define XTP_IDC_LIST_TOOLBARS           100
#define XTP_IDC_BUTTON_NEW              101
#define XTP_IDC_BUTTON_RENAME           102
#define XTP_IDC_BUTTON_DELETE           103
#define XTP_IDC_BUTTON_RESET            104

#define XTP_IDD_PAGE_OPTIONS            9118
#define XTP_IDC_CHECK_FULL_MENUS        100
#define XTP_IDC_CHECK_AFTERDELAY        101
#define XTP_IDC_BUTTON_RESETDATA        102
#define XTP_IDC_CHECK_LARGEICONS        103
#define XTP_IDC_CHECK_SCREENTTIPS       104
#define XTP_IDC_CHECK_SHORTCUTS         105
#define XTP_IDC_COMBO_ANIMATION         106
#define XTP_IDC_GROUP_OTHER             107
#define XTP_IDC_GROUP_PERSONALIZED      108

#define XTP_IDD_PAGE_COMMANDS           9119
#define XTP_IDC_LIST_CATEGORIES         100
#define XTP_IDC_LIST_COMMANDS           101

#define XTP_IDD_NEWTOOLBAR              9120
#define XTP_IDC_EDIT_TOOLBARNAME        100

//////////////////////////////////////////////////////////////////////////

#define XTP_IDR_CUSTOMIZEMENU           9121

#define XTP_ID_CUSTOMIZE_ADDORREMOVE    9122
#define XTP_ID_CUSTOMIZE_RESET          9123
#define XTP_ID_CUSTOMIZE_DELETE         9124
#define XTP_ID_CUSTOMIZE_NAME           9125
#define XTP_ID_CUSTOMIZE_COPYBUTTONIMAGE 9126
#define XTP_ID_CUSTOMIZE_PASTEBUTTONIMAGE 9127
#define XTP_ID_CUSTOMIZE_RESETBUTTONIMAGE 9128
#define XTP_ID_CUSTOMIZE_EDITBUTTONIMAGE 9129
#define XTP_ID_CUSTOMIZE_CHANGEBUTTONIMAGE 9130
#define XTP_ID_CUSTOMIZE_DEFAULTSTYLE   9131
#define XTP_ID_CUSTOMIZE_IMAGEANDTEXT   9132
#define XTP_ID_CUSTOMIZE_TEXTONLY       9133
#define XTP_ID_CUSTOMIZE_BEGINAGROUP    9134

#define XTP_ID_BUTTON_PENCIL            9135
#define XTP_ID_BUTTON_FILL              9136
#define XTP_ID_BUTTON_GETCOLOR          9137
#define XTP_ID_BUTTON_LINE              9138
#define XTP_ID_BUTTON_RECTANGLE         9139
#define XTP_ID_BUTTON_CIRCLE            9140
#define XTP_ID_BUTTON_COPY              9141
#define XTP_ID_BUTTON_PASTE             9142
#define XTP_ID_BUTTON_CLEAR             9143
#define XTP_ID_BUTTON_UNDO              9144
#define XTP_ID_BUTTON_REDO              9145
#define XTP_ID_BUTTON_OPEN              9146

#define XTP_ID_DIALOGBAR_CAPTION        9147
#define XTP_ID_TOOLBAR_EXPAND           9148
#define XTP_ID_TOOLBAR_HIDE             9149
#define XTP_ID_POPUPBAR_EXPAND          9150
#define XTP_ID_MENUBAR_CLOSE            9151
#define XTP_ID_MENUBAR_RESTORE          9152
#define XTP_ID_MENUBAR_MINIMIZE         9153
#define XTP_ID_MENUBAR_SYSMENU          9154

#define XTP_ID_WORKSPACE_MOVEPREVIOUS   9155
#define XTP_ID_WORKSPACE_MOVENEXT       9156
#define XTP_ID_WORKSPACE_NEWHORIZONTAL  9157
#define XTP_ID_WORKSPACE_NEWVERTICAL    9158
#define XTP_ID_WORKSPACE_CANCEL         9159

#define XTP_IDS_CUSTOMIZE_CLOSE         9160
#define XTP_IDS_CUSTOMIZE               9161
#define XTP_IDS_NEWMENU                 9162

#define XTP_IDS_CUSTOM_BAR              9163
#define XTP_IDS_ERROR_BLANKNAME         9164
#define XTP_IDS_ERROR_LIMIT             9165
#define XTP_IDS_ERROR_EXISTS            9166
#define XTP_IDS_RENAMETOOLBAR           9167
#define XTP_IDS_CONFIRM_DELETE          9168
#define XTP_IDS_ALLCOMMANDS             9169

#define XTP_IDS_CONFIRM_RESETDATA       9170
#define XTP_IDS_INVALID_NUMBER          9171
#define XTP_IDS_INVALID_FONTSIZE        9172
#define XTP_IDS_CONFIRM_RESET           9173
#define XTP_IDS_BUILTINMENUS            9174

#define XTP_IDS_CONFIRM_KEYBOARD        9175
#define XTP_IDS_CONFIRM_REASSIGN        9176
#define XTP_IDS_CONFIRM_UPDATE          9177
#define XTP_IDS_IMAGEEDITOR_FILTER      9178

#define XTP_IDS_ANIMATION_SYSDEF        9179
#define XTP_IDS_ANIMATION_RANDOM        9180
#define XTP_IDS_ANIMATION_UNFOLD        9181
#define XTP_IDS_ANIMATION_SLIDE         9182
#define XTP_IDS_ANIMATION_FADE          9183
#define XTP_IDS_ANIMATION_NONE          9184

#define XTP_IDS_TABNAVIGATEBUTTON_ACTIVEFILES  9185

#define XTP_ID_WINDOWLIST               35000
#define XTP_ID_CUSTOMIZE                35001
#define XTP_ID_WORKSPACE_ACTIONS        35002
#define XTP_ID_FILE_MRU                 35003
