#pragma once

#define MAX_QUREY_LENGTH								1024

#define MAX_ACCOUNT_LENGTH								21		// ar
#define MAX_CHARNAME_LENGTH								51		// ar

#define MAX_ACCOUNTID_LENGTH							51		// MU HXKR
#define MAX_CHARACTERID_LENGTH							33		// MU HXKR
#define MAX_TYPENAME_LENGTH								21
#define MAX_PRODUCTNAME_LENGTH							51
#define MAX_MESSAGE_LENGTH								201
#define MAX_VERSION_LENGTH								14
#define MAX_POINTNAME_LENGTH							11
#define MAX_RANK_LENGTH									4
#define MAX_VALUE_LENGTH								255
#define MAX_ITEMNAME_LENGTH								256

#define PROTOCOL_CLIENT_INQUIRE_CASH					0x0071
#define PROTOCOL_SERVER_INQUIRE_CASH					0x0072
#define PROTOCOL_CLIENT_BUYPRODUCT						0x0073
#define PROTOCOL_SERVER_BUYPRODUCT						0x0074
#define PROTOCOL_CLIENT_GIFTPRODUCT						0x0075
#define PROTOCOL_SERVER_GIFTPRODUCT						0x0076
#define PROTOCOL_CLIENT_STORAGELIST						0x0077
#define PROTOCOL_SERVER_STORAGELIST						0x0078
#define PROTOCOL_CLIENT_GIFTCASH						0x0079
#define PROTOCOL_SERVER_GIFTCASH						0x007A
#define PROTOCOL_CLIENT_PRODUCTBUYGIFTCHECK				0x007B
#define PROTOCOL_SERVER_PRODUCTBUYGIFTCHECK				0x007C
#define PROTOCOL_CLIENT_STORAGEUSE						0x007D
#define PROTOCOL_SERVER_STORAGEUSE						0x007E
#define PROTOCOL_CLIENT_STORAGEUSE_ROLLBACK				0x007F
#define PROTOCOL_SERVER_STORAGEUSE_ROLLBACK				0x0080
#define PROTOCOL_CLIENT_STORAGETHROW					0x0081
#define PROTOCOL_SERVER_STORAGETHROW					0x0082
#define PROTOCOL_CLIENT_PRODUCTEVENTLIST				0x0083
#define PROTOCOL_SERVER_PRODUCTEVENTLIST				0x0084
#define PROTOCOL_SERVER_UPDATECATEGORYLIST				0x0085
#define PROTOCOL_SERVER_UPDATEPRODUCTLIST				0x0086
#define PROTOCOL_CLIENT_PACKAGELEFTCOUNT				0x0089
#define PROTOCOL_SERVER_PACKAGELEFTCOUNT				0x008A
#define PROTOCOL_CLIENT_MILEAGESAVE						0x008B
#define PROTOCOL_SERVER_MILEAGESAVE						0x008C
#define PROTOCOL_CLIENT_MILEAGEDEDUCT					0x008D
#define PROTOCOL_SERVER_MILEAGEDEDUCT					0x008E
#define PROTOCOL_CLIENT_MILEAGELIVESAVEUP				0x008F
#define PROTOCOL_SERVER_MILEAGELIVESAVEUP				0x0090
#define PROTOCOL_CLIENT_ITEMSERIALUPDATE				0x0091
#define PROTOCOL_SERVER_ITEMSERIALUPDATE				0x0092
#define PROTOCOL_CLIENT_PRODUCTINFOSELECT				0x0093
#define PROTOCOL_SERVER_PRODUCTINFOSELECT				0x0094

#define PROTOCOL_CLIENT_INQUIRE_SALESVERSION			0x0095
#define PROTOCOL_SERVER_INQUIRE_SALESVERSION			0x0096
#define PROTOCOL_CLIENT_INQUIRE_BANNERVERSION			0x0087
#define PROTOCOL_SERVER_INQUIRE_BANNERVERSION			0x0088

#define PROTOCOL_CLIENT_UPDATEVERSION					0x0097
#define PROTOCOL_SERVER_UPDATEVERSION					0x0098
#define PROTOCOL_CLIENT_UPDATE_BANNERVERSION			0x0099
#define PROTOCOL_SERVER_UPDATE_BANNERVERSION			0x009A

#define PROTOCOL_CLIENT_INQUIRE_GAMEPOINTVALUE			0x009B
#define PROTOCOL_SERVER_INQUIRE_GAMEPOINTVALUE			0x009C

#define PROTOCOL_CLIENT_STORAGELIST_PAGE				0x009D
#define PROTOCOL_SERVER_STORAGELIST_PAGE				0x009E































