/***********************************************************************
 *
 * Module:  rpplugin.h
 *
 * Purpose: Required file for each plugin.
 *
 * Notes:   This is a required file for each plugin. It should be
 *          generated by the plugin vendor. The information contained in
 *          this file should be derived from the vendor ID / name to
 *          prevent conflict with other plugins.
 *
 ***********************************************************************/

#if !defined( RPPLUGIN_H )
#define RPPLUGIN_H

/* =====================================================================
 *  Includes
 * ===================================================================== */
#include "rpcriter.h"
/* Note: each vendor can choose their own method for allocation of
 *       unique ID's. This file defines the ID's used by Criterion.
 */

/* =====================================================================
 *  Defines
 * ===================================================================== */

/* rwPLUGIN_ID must be defined in order to use the RenderWare Graphics
 * debug/error mechanism
 */
#define rwPLUGIN_ID             rwID_PITEXDICTIONARYTK
#define rwPLUGIN_ERRFUNC        _rwdb_CriterionPITexDict
#define rwPLUGIN_ERRENUM        e_rwdb_CriterionPITexDict
#define rwPLUGIN_ERRENUMLAST    e_rwdb_CriterionPITexDictLAST

#if (defined( RWDEBUG ) && !defined( RPERROR_H ))

#define RWDEBUGSTACKDEPTH       rtPITexDictStackDepth

#endif /* (defined( RWDEBUG ) && !defined( RPERROR_H )) */


/* =====================================================================
 *  Module specific type definitions
 * ===================================================================== */

/* =====================================================================
 *  Extern variables
 * ===================================================================== */

#if (defined( RWDEBUG ) && !defined( RPERROR_H ))

#if defined( __cplusplus )
extern "C"
{
#endif /* defined( __cplusplus ) */

extern long rtPITexDictStackDepth;

#if defined( __cplusplus )
}
#endif /* defined( __cplusplus ) */

#endif /* (defined( RWDEBUG ) && !defined( RPERROR_H )) */


/* =====================================================================
 *  Extern function prototypes
 * ===================================================================== */


#endif /* !defined( RPPLUGIN_H ) */
