PLUGIN = rtmipk
LIBNAME = rtmipkmatfx

# Who are the maintainers ?
MAINTAINERS = jamesa

CSRC =						\
	$(CURDIR)/mipkcalc.c			\
	$(CURDIR)/mipkworldmatfx.c		\
	$(CURDIR)/mipkmatfx.c
	
ifndef BASEDIR
BASEDIR = $(CURDIR)/../..
endif
include $(BASEDIR)/makeincl/maketool
