//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by RegionTool.rc
//
#define IDC_ADD                         3
#define IDC_REMOVE                      4
#define IDC_SAVE_MAP_LIST               5
#define IDC_EDIT                        6
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_REGIONTOOL_DIALOG           102
#define IDS_ALREADY_LOCKED              102
#define IDR_HTML_SELECTSKYSETDLG        103
#define IDR_MAINFRAME                   128
#define IDD_GOTO                        129
#define IDD_TEMPLATE                    130
#define IDD_REGIONMENU                  132
#define IDD_LOGIN                       133
#define IDD_UPLOAD_DATA                 135
#define IDD_GOTO_DIALOG                 137
#define IDD_WORLDMAP_SELECT             138
#define IDD_WORLDMAP_EDIT               139
#define IDD_ITEMSELECT                  140
#define IDD_SELECTSKYSET                141
#define IDD_WORLDCOODCALC               142
#define IDD_REGIONSELECT_DLG            143
#define IDD_WORLDCOODCALCEX             144
#define IDD_PROGRESS_DLG                225
#define IDC_REGIONVIEW                  1000
#define IDC_GOTO                        1005
#define IDC_DIVISION                    1006
#define IDC_NAME                        1007
#define IDC_COMMENT                     1008
#define IDC_INDEX                       1009
#define IDC_PRIORITY                    1010
#define IDC_TYPE                        1012
#define IDC_SAFETY                      1013
#define IDC_TAB_REGION                  1015
#define IDC_TAB_SPAWN                   1016
#define IDC_TAB_Sky                     1017
#define IDC_MENUWND                     1018
#define IDC_ID                          1019
#define IDC_PASS                        1020
#define IDC_BITMAPUPDATE                1020
#define IDC_RIDABLE                     1021
#define IDC_PET                         1022
#define IDC_BUTTON1                     1022
#define IDC_ITEMTELEPORT                1023
#define IDC_CHARACTERTEMPLATE           1023
#define IDC_ITEMPOTION                  1024
#define IDC_AI2TEMPLATE                 1024
#define IDC_ITEMRESURRECT               1025
#define IDC_OBJECTTEMPLATE              1025
#define IDC_SPAWNGROUP                  1026
#define IDC_DISABLEMINIMAP              1026
#define IDC_SKYSET                      1027
#define IDC_GOTO_BATTLEFIELD            1027
#define IDC_JAIL                        1027
#define IDC_REGIONTOOL                  1028
#define IDC_GOTO_DELPARAS               1028
#define IDC_SRC_HEIGHT                  1028
#define IDC_ARTIST                      1029
#define IDC_GOTO_TURLAN                 1029
#define IDC_DESIGN                      1030
#define IDC_GOTO_TRILGARD               1030
#define IDC_GOTO_KUN                    1031
#define IDC_DISPLAY                     1032
#define IDC_CHECK1                      1033
#define IDC_ZONELOADING                 1033
#define IDC_SHOWTHISBOXAGAIN            1034
#define IDC_CHARACTER_BLOCK             1034
#define IDC_PROGRESS                    1035
#define IDC_CHARACTER_BLOCK2            1035
#define IDC_ITEM_POTION_TYPE2           1035
#define IDC_SELECTWORLDMAP              1036
#define IDC_MESSAGE                     1036
#define IDC_WORLDMAP                    1037
#define IDC_PERCENT                     1037
#define IDC_LIST                        1038
#define IDC_SELECTSKYSET                1038
#define IDC_ITEM_POTION_GUILD           1039
#define IDC_STARTX                      1040
#define IDC_STARTZ                      1041
#define IDC_ENDX                        1042
#define IDC_ENDZ                        1043
#define IDC_ITEMID                      1045
#define IDC_SELECT_ITEM_ID              1046
#define IDC_NONEEDITEM                  1048
#define IDC_DEFAULTSKYSET               1049
#define IDC_CALCCOODINATE               1051
#define IDC_DIVISION1                   1052
#define IDC_CALCCOODINATE2              1052
#define IDC_X1                          1053
#define IDC_Y1                          1054
#define IDC_DIVISION2                   1055
#define IDC_MAP_DISPLAY                 1055
#define IDC_X2                          1056
#define IDC_VDISTANCE                   1056
#define IDC_Y2                          1057
#define IDC_LEVELLIMIT                  1057
#define IDC_LEVELMIN                    1058
#define IDC_EDIT1                       1059
#define IDC_PARENTINDEX                 1059
#define IDC_CHOICEREGION                1060
#define IDC_REGIONSELECT_LIST           1061
#define IDC_X1_EDIT                     1061
#define IDC_Y1_EDIT                     1062
#define IDC_X2_EDIT                     1063
#define IDC_EDIT6                       1064
#define IDC_Y2_EDIT                     1064
#define ID_EXPORTBTN                    1065
#define IDC_X1_STATIC                   1066
#define IDC_Y1_STATIC                   1067
#define IDC_X2_STATIC                   1068
#define IDC_Y2_STATIC                   1069
#define IDC_RADIUS                      1270
#define IDC_SRC_X                       1271
#define IDC_SRC_Z                       1272
#define IDC_DST_X                       1273
#define IDC_SRC_Z2                      1274
#define IDC_DST_Z                       1274
#define IDD_EVENT_NATURE_DLG            30500
#define IDC_WEATHER_TEMPLATE_COMBO      31001
#define IDC_RANGE                       31002
#define IDC_USE_CLOUD                   31455
#define IDC_USE_FOG                     31456
#define IDC_USE_EFFECT                  31457
#define IDC_USE_LIGHT                   31458

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        145
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1070
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
