//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PatchClient_FR.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_PATCHCLIENT_DIALOG          102
#define IDS_CONTINUE_DOWNLOAD           102
#define IDS_MSG_DOWNLOAD                103
#define IDS_MSG_PROGRESS                104
#define IDS_MSG_APPLY_FILE              105
#define IDS_MSG_APPLY_PROGRESS          106
#define IDS_MSG_COMPLETE                107
#define IDS_DISCONNECTED                108
#define IDS_INSUFFICENT_DISK            109
#define IDS_RUN_AGAIN                   110
#define IDS_ERROR_DNS                   111
#define IDS_ERROR_CONNECTION            112
#define IDS_RUN_GAME                    113
#define IDS_ERROR_FTP_CONNECTION        114
#define IDS_ERROR_FTP_DISCONNECTED      115
#define IDS_ERROR_FTP_OPEN              116
#define IDS_ERROR_FTP_RECEIVE           117
#define IDS_ERROR_FAILED                118
#define IDS_ERROR_PATCH_CONNECTION      119
#define IDS_ERROR_DIRECTX               120
#define IDS_ERROR_RUN_CLIENT            121
#define IDS_ERROR_SET_DIRECTORY         122
#define IDS_ERROR_MAKE_PATCH_FOLDER     123
#define IDS_MSG_JOIN                    124
#define IDS_MSG_OPTION                  125
#define IDS_MSG_HOMEPAGE                126
#define IDS_MSG_START                   127
#define IDR_MAINFRAME                   128
#define IDS_STRING128                   128
#define IDS_MSG_NOTICE                  128
#define IDS_PATCH_INFO                  129
#define IDS_PATCH_TOTAL                 130
#define IDC_CURSOR1                     131
#define IDS_REAL_TITLE                  131
#define IDS_TEST_TITLE                  132
#define IDS_CHECK_VERSION               133
#define IDS_VERSION_ERROR               134
#define IDS_STRING135                   135
#define IDS_WIDTHSIZE                   135
#define IDS_HEIGHTSIZE                  136
#define IDS_PROGRASSBAR1X               137
#define IDS_PROGRESSBAR1X               137
#define IDS_PROGRASSBAR1Y               138
#define IDS_PROGRESSBAR1Y               138
#define IDS_PROGRASSBAR2Y               139
#define IDS_PROGRESSBAR2Y               139
#define IDS_EXITBTNPOSX2                140
#define IDS_PROGRESSMSG1X               140
#define IDS_EXITBTNPOSY2                141
#define IDS_PROGRESSMSG1Y               141
#define IDS_PROGRESSMSG2Y               142
#define IDS_PROGRESSMSGWIDTH            143
#define IDS_PROGRESSMSGHEIGHT           144
#define IDS_STARTBTNPOSX                145
#define IDS_MSG_CONNECTING              146
#define IDS_OPTIONTITLE                 147
#define IDS_HIGH                        148
#define IDS_MIDDLE                      149
#define IDS_LOW                         150
#define IDS_STARTBTNPOSY                151
#define IDS_STARTBTNWIDTH               152
#define IDD_PATCHCLIENT_OPTION_DIALOG   153
#define IDS_STARTBTNHEIGHT              153
#define IDS_OPTIONBTNPOSX               154
#define IDS_OPTIONBTNPOSY               155
#define IDS_OPTIONBTNWITDH              156
#define IDS_OPTIONBTNWIDTH              156
#define IDS_OPTIONBTNHEIGHT             157
#define IDS_INTERFACE1                  158
#define IDS_INTERFACE2                  159
#define IDS_OPTIONTITLE2                160
#define IDB_Progress                    161
#define IDS_OPTIONON                    161
#define IDS_OPTIONOFF                   162
#define IDS_SCREENSIZE                  163
#define IDS_TETUREQUALITY               164
#define IDS_INTERFACESTYLE              165
#define IDS_QUICKOPTIONSPEED            166
#define IDS_QUICKOPTIONQUALITY          167
#define IDS_USERSPEC                    168
#define IDS_RANGEFAR                    169
#define IDS_RANGEMIDDLE                 170
#define IDI_ArchlordIcon                171
#define IDS_RANGENEAR                   171
#define IDB_Progress1                   172
#define IDS_CHARACTERRANGE              172
#define IDS_MAPRANGE                    173
#define IDB_Progress3                   174
#define IDS_NATUREOBJECT                174
#define IDB_OPTION_DRIVER               175
#define IDB_DRIVERBACK                  175
#define IDS_SPECIALEFFECT               175
#define IDD_DRIVER_DOWN_DLG             176
#define IDS_SHADOW                      176
#define IDS_WATEREFFECT                 177
#define IDS_SPECIALTEXTURE              178
#define IDS_GLOWEFFECT                  179
#define IDB_Button_Option_Set           180
#define IDS_AUTOEXPOSURE                180
#define IDS_IMPACTEFFECT                181
#define IDS_RANGEALL                    182
#define IDS_OPTIONDESC1                 183
#define IDS_OPTIONDESC2                 184
#define IDS_OPTIONDESC3                 185
#define IDS_BROOMTYPE1                  186
#define IDS_BROOMTYPE2                  187
#define IDS_ERROR_DOWNLOAD              188
#define IDB_Button_Option_Save_Set      189
#define IDS_BOTTOMCMTITLE               189
#define IDB_Button_Option_Cancel_Set    190
#define IDS_BOTTOMCMSTR1                190
#define IDS_BOTTOMCMSTR2                191
#define IDS_PROGRASSBARWIDTH            194
#define IDS_PROGRESSBARWIDTH            194
#define IDS_PROGRASSBARHEIGHT           195
#define IDS_PROGRESSBARHEIGHT           195
#define IDB_BITMAP1                     196
#define IDB_Button_Close_Set            196
#define IDS_EXITBTNPOSX                 196
#define IDS_EXITBTNPOSY                 197
#define IDS_WINDOWED_MODE               200
#define IDB_BITMAP2                     201
#define IDB_BITMAP3                     202
#define IDB_Progress2                   202
#define IDB_BITMAP4                     203
#define IDB_Button_Startgame_Set        203
#define IDB_MenuBtn5                    206
#define IDB_MenuBtn1                    207
#define IDB_MenuBtn2                    208
#define IDB_MenuBtn3                    209
#define IDB_MenuBtn4                    210
#define IDB_SelectServer2               211
#define IDB_SelectServer3               212
#define IDB_SelectServer1               213
#define IDB_ServerSelectSet             218
#define IDB_ScrollThumb                 221
#define IDC_FileRecvProgress            1002
#define IDC_EXitButton                  1003
#define IDC_LoginButton                 1004
#define IDC_BlockRecvProgress           1004
#define IDC_IDEditBox                   1006
#define IDC_PasswordEditBox             1007
#define IDC_ProviderList                1010
#define IDC_PatchHistory                1010
#define IDC_Static_DetailInfo           1011
#define IDC_Static_Status               1012
#define IDC_START_GAME                  1013
#define IDC_RegisterButton              1015
#define IDC_OptionButton                1016
#define IDC_HomepageButton              1017
#define IDC_Option_Button_Save          1019
#define IDC_Option_Button_Cancel        1020
#define IDC_Option_Combo_Resolution     1033
#define IDC_Option_Combo_Sound          1034
#define IDC_Option_Combo_Speaker        1035
#define IDC_Static_Progress_Percent     1036
#define IDC_Option_Combo_Texture        1038
#define IDC_OPTION_SLIDER               1039
#define IDC_BUTTON_DRIVER_OK            1040
#define IDC_Option_Combo_Texture2       1040
#define IDC_Option_Select_Interface     1040
#define IDC_Option_Combo_WindowedMode   1040
#define IDC_BUTTON_DRIVER_NO            1041
#define IDC_PROGRESS1                   1042
#define IDC_CHECK_DONOTUSECHECKDRIVER   1043
#define IDC_HOMEPAGE                    1044
#define IDC_JOIN                        1045
#define IDC_CUSTOMER                    1046
#define IDC_DRIVER                      1047
#define IDC_LINE                        1048
#define IDC_MenuBtn1                    1051
#define IDC_MenuBtn2                    1052
#define IDC_MenuBtn3                    1053
#define IDC_MenuBtn4                    1054
#define IDC_MenuBtn5                    1055
#define IDC_ServerList                  1056
#define IDC_SeverSelect1                1057
#define IDC_SeverSelect2                1058
#define IDC_SeverSelect3                1059
#define IDC_ScrollThumbBtn              1062
#define IDS_SITEURL1                    1063
#define IDS_SITEURL2                    1064
#define IDS_SITEURL3                    1065
#define IDS_SITEURL4                    1066

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        222
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1067
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
