//
// Generated by Microsoft (R) D3DX9 Shader Assembler
//
//  Source: dot3notexture.psh
//  Flags: 
//


const DWORD dwDot3notexturePixelShader[] =
{
    0xffff0101, 0x00000042, 0xb00f0000, 0x00000042, 0xb00f0001, 0x00000040, 
    0xb00f0002, 0x00000008, 0x80170000, 0xb4e40000, 0xb4e40002, 0x00000004, 
    0x80070000, 0x80e40000, 0xa0e40000, 0xa0e40001, 0x40000005, 0x80080000, 
    0xa0ff0000, 0x90ff0000, 0x0000ffff
};
