//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ApmEventManagerDlg.rc
//
#define IDC_EVENT_LIST                  21000
#define IDD_EVENT_LIST                  21000
#define IDC_EVENT_ADD                   21001
#define IDD_EVENT_SELECT                21001
#define IDC_EVENT_REMOVE                21002
#define IDC_EVENT_SELECT                21002
#define IDD_EVENT_CONDITION             21002
#define IDC_EVENT_EDIT                  21003
#define IDC_EVENT_ADD_SELECT            21004
#define IDC_EVENT_CONDITION_TARGET      21005
#define IDC_EVENT_CONDITION_AREA        21006
#define IDC_EVENT_CONDITION_ENVIRONMENT 21007
#define IDC_EVENT_CONDITION_TIME        21008
#define IDC_EVENT_CONDITION_TARGET_FACTOR 21009
#define IDC_EVENT_CONDITION_TARGET_ITEMS 21010
#define IDC_EVENT_CONDITION_TARGET_ITEM_ADD 21011
#define IDC_EVENT_CONDITION_TARGET_ITEM_ADD2 21012
#define IDC_EVENT_CONDITION_TARGET_ITEM_REMOVE 21012
#define IDC_EVENT_CONDITION_AREA_SPHERE 21013
#define IDC_EVENT_CONDITION_AREA_FAN    21014
#define IDC_EVENT_CONDITION_AREA_BOX    21015
#define IDC_EVENT_CONDITION_AREA_SPHERE_RADIUS 21018
#define IDC_EVENT_CONDITION_AREA_BOX_INF_X 21019
#define IDC_EVENT_CONDITION_AREA_BOX_INF_Y 21020
#define IDC_EVENT_CONDITION_AREA_BOX_INF_Z 21021
#define IDC_EVENT_CONDITION_AREA_FAN_RADIUS 21022
#define IDC_EVENT_CONDITION_AREA_FAN_ANGLE 21023
#define IDC_EVENT_CONDITION_AREA_BOX_SUP_X 21024
#define IDC_EVENT_CONDITION_AREA_BOX_SUP_Y 21025
#define IDC_EVENT_CONDITION_AREA_BOX_INF_Z2 21026
#define IDC_EVENT_CONDITION_AREA_BOX_SUP_Z 21026

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        21003
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         21020
#define _APS_NEXT_SYMED_VALUE           21000
#endif
#endif
