#if (!defined(RPPLUGIN_H))
#define RPPLUGIN_H

/*
 * This is a required file for each plugin. It should be generated by the
 * plugin vendor. The information contained in this file should be unique
 * derived from the vendor id / name to prevent conflict with other plugins
 */

#if (defined(RWDEBUG) && !defined(RPERROR_H))
extern long _rtGenCPipeStackDepth;
#define RWDEBUGSTACKDEPTH _rtGenCPipeStackDepth
#endif /* (defined(RWDEBUG) !defined(RPERROR_H)) */

#include <rpcriter.h>          /* Note: each vendor can choose their own method for
                                * allocation of unique ID's. This file defines
                                * the ID's used by Criterion.
                                */

/* rwPLUGIN_ID must be defined in order to use the RenderWare debug/error
 * mechanism
 */

#define rwPLUGIN_ID            rwID_GENCPIPETOOLKIT
#define rwPLUGIN_ERRFUNC      _rwdb_CriterionGENCPIPETOOL
#define rwPLUGIN_ERRENUM     e_rwdb_CriterionGENCPIPETOOL
#define rwPLUGIN_ERRENUMLAST e_rwdb_CriterionGENCPIPETOOLLAST

#endif /* (!defined(RPPLUGIN_H)) */
