PLUGIN = rtdict

# Who are the maintainers ?
MAINTAINERS = gregb

ifndef BASEDIR
BASEDIR = $(CURDIR)/../..
endif
include $(BASEDIR)/makeincl/maketool

DOXYSRC := $(CURDIR)/$(PLUGIN).h $(CURDIR)/$(PLUGIN).c
