# What plugin are we building ?

PLUGIN = rtltmapcnv
# Who are the maintainers ?
MAINTAINERS = ajh

CSRC =						\
        $(CURDIR)/rasterg.c                     \
        $(CURDIR)/fillerg.c                     \
        $(CURDIR)/rasterng.c                    \
        $(CURDIR)/fillerng.c                     \
        $(CURDIR)/atmcnv.c                      \
        $(CURDIR)/worldcnv.c                    \
        $(CURDIR)/rtltmapcnv.c                       

ifndef BASEDIR
BASEDIR = $(CURDIR)/../..
endif
include $(BASEDIR)/makeincl/maketool
