//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MapTool.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_LOGIN                       101
#define IDR_MAINFRAME                   128
#define IDB_HSV_TABLE                   129
#define IDD_HSVCONTROL_RGB_INPUT_DLG    130
#define IDD_SPLASH                      132
#define IDR_BLANK                       151
#define IDB_PITCH                       153
#define IDB_ELEVATION                   155
#define IDB_YAW                         156
#define IDB_ZDOLLY                      157
#define IDB_HDOLLY                      158
#define IDB_ROLL                        159
#define IDB_ZOOM                        160
#define IDB_CAMERAH                     161
#define IDB_LIGHTV                      162
#define IDB_CAMERAV                     163
#define IDB_LIGHTH                      164
#define IDB_CONERADIUS                  165
#define IDD_ENTITIES                    165
#define IDB_CONEANGLE                   166
#define IDI_CAMERA                      170
#define IDI_WORLD                       171
#define IDI_SOFTSPOT                    179
#define IDI_SPOTLIGHT                   180
#define IDI_AMBIENT                     182
#define IDI_DIRECTIONAL                 183
#define IDB_LIGHTAMBIENT                184
#define IDI_CLUMP                       185
#define IDB_CLUMPH                      185
#define IDB_CLUMPV                      186
#define IDI_TRASH                       187
#define IDB_SPLASH                      191
#define IDI_ANIM                        195
#define IDI_SNAPTO                      196
#define IDD_MOUSEFLIGHT                 197
#define IDB_MOUSEFLIGHT                 199
#define IDD_1RPGFLIGHT                  201
#define IDB_1RPGFLIGHT                  203
#define IDD_MAPSELECT                   206
#define IDB_TOOLBAR_UP                  208
#define IDB_TOOLBAR_DOWN                209
#define IDB_BACKGROUND                  210
#define IDR_TILEMENU                    211
#define IDD_TILEWINDOW_EDITCATEGORY     212
#define IDD_TILE_EDITCATEGORY           213
#define IDD_TILE_NAME_EDIT              214
#define IDD_DIALOG_OBJECT               215
#define IDR_OBJECTMENU                  216
#define IDD_SUBDIVISION                 217
#define IDD_CONST                       218
#define IDD_LIGHTSETTINGDIALOG          219
#define IDB_COLORTABLE                  222
#define IDD_ADJUST_GEOMETRY_HEIGHT      224
#define IDD_PROGRESS_DLG                225
#define IDD_CAMERA_SETTING              227
#define IDD_KEYREFERENCE                229
#define IDD_CREATESECTOR_DIALOG         230
#define IDB_MODE_TILE_UNSELECT          231
#define IDB_MODE_SUBDIV_UNSELECT        232
#define IDB_MODE_OBJECT_SELECTED        233
#define IDB_MODE_OBJECT_UNSELECT        234
#define IDB_MODE_GEOMETRY_SELECTED      235
#define IDB_MODE_GEOMETRY_UNSELECT      236
#define IDB_MODE_TILE_SELECTED          237
#define IDB_MODE_SUBDIV_SELECTED        238
#define IDB_TILE_CATEGORY_UNSELECT      239
#define IDB_TILE_LAYER_BACKGROUND       240
#define IDB_TILE_LAYER_ALPHA            241
#define IDB_TILE_BACKTILE               242
#define IDB_TILE_CATEGORY_SELECTED      243
#define IDB_TILE_LAYER_UPPER            244
#define IDB_TILE_TILESELECT             245
#define IDB_TILE_TILESELECT2            246
#define IDD_GENERATE_ROUGH              247
#define IDD_CONVERT_TILE_DIALOG         248
#define IDB_ALEF_FULL_MAP               250
#define IDD_OPTION                      252
#define IDD_EXPORT                      253
#define IDD_SAVE                        256
#define IDR_MAIN_OBJECT_POPUP           257
#define IDD_OBJECT_PROPERTIES           258
#define IDD_FARCLIPPLANE                260
#define IDD_SKYSETTING                  261
#define IDB_TILE_LAYER_TONGMAP          262
#define IDB_HSV_TABLE1                  263
#define IDD_OBJECT_BRUSH_SETTING        266
#define IDD_SKY_TEMPLATE_PREVIEW        268
#define IDB_BLOCKING_PLUGIN             270
#define IDD_WATER_HEIGHT                274
#define IDD_PRELIGHT                    275
#define IDD_SKY_VALUE_CHANGE            277
#define IDD_COMMANDCONSOLE              278
#define IDD_DDSCONVERT                  279
#define IDD_GRASS_SET                   283
#define IDD_ATOMICFILTER                284
#define IDD_EVENTNATURE_FILTER          285
#define IDD_NPCNAMEEDIT                 286
#define IDB_BACKGROUND2                 287
#define IDD_HEIGHTMAP_PROPERTY          288
#define IDD_GENERATE_GEOMETRY           289
#define IDD_DURATION_SET_DIALOG         291
#define IDD_DUNGEON_TEMPLATE_EDIT       294
#define IDD_DUNGEON_TEMPLATE_SELECT     295
#define IDD_AMBOCCLMAP_PREFIX           296
#define IDD_AMBOCCLMAP_SUPERSAMPLE      297
#define IDD_CAMERAWALKSETTING           298
#define IDD_NATURE_EFFECT_SET           299
#define IDD_FINDOBJECT                  301
#define IDD_AMBOCCLMAP_DESTROY          302
#define IDD_ROUGHLOAD                   303
#define IDD_NPC_PROPERTY                304
#define IDC_R                           1001
#define IDC_COMBO1                      1001
#define IDC_CONEANGLE                   1002
#define IDC_G                           1002
#define IDC_B                           1003
#define IDC_CONERADIUS                  1004
#define IDC_ENTITYTREE                  1006
#define IDC_NEWAMBIENT                  1008
#define IDC_NEWSPOT                     1009
#define IDC_NEWSOFTSPOT                 1010
#define IDC_NEWDIRECTIONAL              1011
#define IDC_NEWCLUMP                    1012
#define IDC_TRASHBUTTON                 1013
#define IDC_SNAPTO                      1014
#define IDC_ATTACHANIM                  1015
#define IDC_HELPPIC                     1015
#define IDC_MAP_X                       1016
#define IDC_MAP_Y                       1017
#define IDC_ZOOM                        1018
#define IDC_MAP_SELECT_CONTROL          1019
#define IDC_INFO                        1020
#define IDC_MAP_X2                      1021
#define IDC_LOADSELECTEDONLY            1022
#define IDC_TYPE                        1023
#define IDC_MAP_Y2                      1023
#define IDC_CATEGORYNAME                1024
#define IDC_NAME                        1025
#define IDC_EDIT1                       1026
#define IDC_EDIT2                       1027
#define IDC_BUTTON_BROWSE               1028
#define IDC_FOG_DISTANCE_VALUE          1028
#define IDC_POSITION_Z                  1028
#define IDC_ROTATE_MIN                  1028
#define IDC_EDIT_OBJECT                 1028
#define IDC_CIRCUMSTANCE_HEIGHT         1028
#define IDC_GEOMETRYFILTER              1028
#define IDC_HEIGHT_03                   1028
#define IDC_SRC_HEIGHT                  1028
#define IDC_EDIT_OBJECT_RED             1029
#define IDC_SCALE_X                     1029
#define IDC_SCALE_MAX                   1029
#define IDC_CIRCUMSTANCE_RANGE          1029
#define IDC_HEIGHT_04                   1029
#define IDC_DETAILSLIDER                1030
#define IDC_EDIT_OBJECT_GREEN           1030
#define IDC_SCALE_Y                     1030
#define IDC_ROTATE_MAX                  1030
#define IDC_HEIGHT_05                   1030
#define IDC_DETAIL                      1031
#define IDC_EDIT_OBJECT_BLUE            1031
#define IDC_SCALE_Z                     1031
#define IDC_ROTATE_Y_MIN                1031
#define IDC_HEIGHT_06                   1031
#define IDC_SECTORWIDTH                 1032
#define IDC_EDIT_OBJECT_BLUE2           1032
#define IDC_EDIT_OBJECT_ALPHA           1032
#define IDC_ROTATE_Y_MAX                1032
#define IDC_HEIGHT_07                   1032
#define IDC_HORICOUNT                   1033
#define IDC_AMBIANT_RGB                 1033
#define IDC_HEIGHT_08                   1033
#define IDC_VERTCOUNT                   1034
#define IDC_DIRECTIONAL_RGB             1034
#define IDC_VALUE                       1034
#define IDC_HEIGHT_09                   1034
#define IDC_DEPTH                       1035
#define IDC_PROGRESS                    1035
#define IDC_HEIGHT_10                   1035
#define IDC_MESSAGE                     1036
#define IDC_HEIGHT_11                   1036
#define IDC_PERCENT                     1037
#define IDC_HEIGHT_12                   1037
#define IDC_TILED                       1038
#define IDC_ALPHATILED                  1039
#define IDC_NEARCLIP_SLIDER             1040
#define IDC_FAR_CLIP_SLIDER             1042
#define IDC_FOG_DISTANCE_SLIDER         1043
#define IDC_USEFOG                      1044
#define IDC_FOGTYPECOMBO                1045
#define IDC_FOG_DENSITY_VALUE           1046
#define IDC_NEARCLIP_VALUE              1047
#define IDC_FAR_CLIP_VALUE              1048
#define IDC_REF                         1049
#define IDC_CREATEDETAIL                1051
#define IDC_CREATE_DEPTH                1052
#define IDC_OFFSET                      1053
#define IDC_CREATE_HEIGHT               1053
#define IDC_CATEGORY                    1057
#define IDC_DISPLAY                     1058
#define IDC_FILENAME                    1059
#define IDC_EXPORT                      1060
#define IDC_LOADALL                     1061
#define IDC_LOADTYPECOMBO               1062
#define IDC_USEPOLYGONLOCK              1063
#define IDC_TOGGLEFIELD                 1063
#define IDC_DETAILEXPORT                1064
#define IDC_SAVESELECTION               1064
#define IDC_COMPACTEXPORT               1065
#define IDC_ROUGHEXPORT                 1066
#define IDC_TILEEXPORT                  1067
#define IDC_LOADSELECTION               1067
#define IDC_BACKCOLORSET                1068
#define IDC_OBJECT_EXPORT               1069
#define IDC_MAPINFO                     1070
#define IDC_OBJECT_EXPORT2              1070
#define IDC_MINIMAP_EXPORT              1070
#define IDC_OBJECTTEMPLATE              1071
#define IDC_MINIMAP_EXPORT2             1071
#define IDC_SERVERDATA_EXPORT           1071
#define IDC_TILELIST                    1072
#define IDC_OBJECTLIST                  1073
#define IDC_TILEVERTEXCOLOR             1074
#define IDC_OBJECT_STATIC               1075
#define IDC_OCTREEDATA                  1075
#define IDC_OBJECT_PRELIGHT             1076
#define IDC_OBJECT_PRELIGHT_FORCE       1077
#define IDC_OBJECT_LIGHT                1078
#define IDC_OBJECT_MATERIAL             1079
#define IDC_OBJECT_AMBIENT              1080
#define IDC_OBJECT_AMBIENT2             1081
#define IDC_OBJECT_ALPHA                1081
#define IDC_HEIGHT_GENERATE             1082
#define IDC_TILE_GENERATE               1083
#define IDC_OBJECT_NO_CAMERA_ALPHA      1083
#define IDC_VERTEXCOLOR_GENERATE        1084
#define IDC_OBJECT_BLOCKING             1084
#define IDC_APPLYALPHA                  1085
#define IDC_OBJECT_RIDABLE              1085
#define IDC_NEAR                        1086
#define IDC_FOG_DISTANCE                1086
#define IDC_FAR                         1087
#define IDC_FOG                         1088
#define IDC_FOG_FARCLIP                 1088
#define IDC_FARCLIP_SLIDER              1089
#define IDC_NOPE                        1090
#define IDC_STOPTIME                    1090
#define IDC_FOGRANGE_SLIDER             1090
#define IDC_FOG_FARCLIP_SLIDER          1090
#define IDC_TIMEZONE                    1092
#define IDC_DIRECTIONAL                 1093
#define IDC_AMBIENT                     1094
#define IDC_BACKTEXTUREPREVIEW          1095
#define IDC_CLOUDTEXTUREPREVIEW         1096
#define IDC_FOGCOLOR                    1097
#define IDC_CLOUDTEXTUREPREVIEW2        1098
#define IDC_IMAGE_PREVIEW               1098
#define IDC_TEXTURELIST                 1099
#define IDC_CLOUDSPEED                  1100
#define IDC_USESKY                      1102
#define IDC_LOADRANGE_DETAIL            1103
#define IDC_LOADRANGE_DATA              1104
#define IDC_LOADRANGE_ROUGH             1105
#define IDC_SKYRADIUS                   1106
#define IDC_FOGDENSITY                  1107
#define IDC_FOGRANGE                    1108
#define IDC_SETFOG                      1109
#define IDC_DIMENSION                   1111
#define IDC_ROTATE_DEGREEX              1112
#define IDC_POSITION_X                  1113
#define IDC_POSITION_Y                  1114
#define IDC_ROTATE_DEGREEY              1115
#define IDC_USEBRUSHPOLYGON             1116
#define IDC_WALL                        1119
#define IDC_BRIDGE                      1120
#define IDC_DENSITY                     1120
#define IDC_SCALE_MIN                   1121
#define IDC_PLUGIN_SAVE                 1123
#define IDC_PULGIN_WATER_LIST           1124
#define IDC_PULGIN_WATER_BUTTON         1125
#define IDC_EFFECT                      1126
#define IDC_HEIGHT                      1127
#define IDC_CHARACTER                   1128
#define IDC_GEOMETRY                    1129
#define IDC_OBJECT                      1130
#define IDC_EDIT_CHARACTER              1131
#define IDC_EDIT_GEOMETRY               1132
#define IDC_CAMERABLOCKING              1133
#define IDC_SKY_HEIGHT_SLIDER           1134
#define IDC_SKY_RANGE_SLIDER            1135
#define IDC_CIRCUMSTANCE_HEIGHT_SLIDER  1136
#define IDC_CIRCUMSTANCE_RANGE_SLIDER   1137
#define IDC_SKY_HEIGHT                  1138
#define IDC_SKY_RANGE                   1139
#define IDC_COMMAND                     1141
#define IDC_FILELIST                    1142
#define IDC_CONVERT                     1143
#define IDC_SHOWGRID                    1144
#define IDC_PLUGIN_GRASS_LIST           1145
#define IDC_CHECK_GRASSONOFF            1146
#define IDC_PLUGIN_GRASS_SET            1147
#define IDC_GRASS_EDIT2                 1148
#define IDC_GRASS_EDIT3                 1149
#define IDC_GRASS_EDIT4                 1150
#define IDC_GRASS_EDIT5                 1151
#define IDC_GRASS_EDIT1                 1152
#define IDC_GRASS_EDIT6                 1155
#define IDC_GRASS_EDIT7                 1156
#define IDC_SYSTEM_OBJECT               1157
#define IDC_OBJECT_ALL                  1158
#define IDC_RIDABLEOBJECT               1159
#define IDC_BLOCKINGOBJECT              1160
#define IDC_EVENTFILTER                 1161
#define IDC_GRASS                       1162
#define IDC_OTHERS                      1163
#define IDC_EVENTCOMBO                  1164
#define IDC_SHOWGEOMETRY                1165
#define IDC_LIGHTCOLOR                  1166
#define IDC_LIGHTPOSITION               1167
#define IDC_SKYCOLOR                    1168
#define IDC_CLOUD                       1170
#define IDC_CIRCUMSTANCE                1171
#define IDC_AMBIENCE                    1172
#define IDC_BYTIME                      1174
#define IDC_BGM                         1175
#define IDC_DONOTCHANGEALL              1176
#define IDC_NAMEORIGIN                  1177
#define IDC_MINHEIGHT                   1178
#define IDC_MAXHEIGHT                   1179
#define IDC_ITERATION                   1180
#define IDC_FILTER                      1181
#define IDC_GENERATE                    1182
#define IDC_PROPERTY                    1186
#define IDC_DURATION                    1187
#define IDC_SHADOW2                     1188
#define IDC_EDITTEMPLATE                1189
#define IDC_ADDTEMPLATE                 1190
#define IDC_DELETE_TEMPLATE             1191
#define IDC_TEMPLATE_NAME               1192
#define IDC_DUNGEONTEMPLATELIST         1193
#define IDC_FLOOR_0                     1194
#define IDC_FLOOR_1                     1195
#define IDC_FLOOR_2                     1196
#define IDC_SLOPE_0                     1197
#define IDC_SLOPE_1                     1198
#define IDC_SLOPE_2                     1199
#define IDC_STAIR_0                     1200
#define IDC_STAIR_1                     1201
#define IDC_STAIR_2                     1202
#define IDC_WALL2_0                     1203
#define IDC_WALL2_1                     1204
#define IDC_WALL2_2                     1205
#define IDC_WALL4_0                     1206
#define IDC_WALL4_1                     1207
#define IDC_WALL4_2                     1208
#define IDC_FENCE_0                     1209
#define IDC_FENCE_1                     1210
#define IDC_FENCE_2                     1211
#define IDC_PILLAR_0                    1212
#define IDC_PILLAR_1                    1213
#define IDC_PILLAR_2                    1214
#define IDC_DOME4_0                     1215
#define IDC_DOME4_1                     1216
#define IDC_DOME4_2                     1217
#define IDC_DOME1_0                     1218
#define IDC_STATIC_AMBOCCLMAP_PREFIX    1218
#define IDC_DOME1_1                     1219
#define IDC_EDIT_AMBOCCLMAP_PREFIX      1219
#define IDC_DOME1_2                     1220
#define IDC_DUNGEON                     1220
#define IDC_STATIC_AMBOCCLMAP_SUPERSAMPLE 1220
#define IDC_EDIT_AMBOCCLMAP_SUPERSAMPLE 1221
#define IDC_STATIC_AMBOCCLMAP_RAYLENGTH 1222
#define IDC_EDIT_AMBOCCLMAP_RAYLENGTH   1223
#define IDC_SINGLE_NORMAL               1226
#define IDC_SINGLE_STARE                1227
#define IDC_SINGLE_PARALLEL             1228
#define IDC_SINGLE_FLIGHT               1229
#define IDC_LOOP                        1230
#define IDC_CLOSED                      1231
#define IDC_ACCEL                       1232
#define IDC_SINGLESPLINE                1233
#define IDC_CHECK2                      1234
#define IDC_DOUBLESPLINE                1234
#define IDC_STATIC_AMBOCCLMAP_RAYCOUNT  1234
#define IDC_OBJECTBOUNDINGSPHERE        1234
#define IDC_EDIT_AMBOCCLMAP_RAYCOUNT    1235
#define IDC_NEFFECT_COMBO               1236
#define IDC_NEFFECT_TEXTURE_BUTTON      1237
#define IDC_NEFFECT_EDIT_ID             1238
#define IDC_NEFFECT_TEXTURE             1239
#define IDC_NEFFECT_SIZE_MIN            1240
#define IDC_NEFFECT_SIZE_MAX            1241
#define IDC_NEFFECT_SPEED_MIN           1242
#define IDC_NEFFECT_SPEED_MAX           1243
#define IDC_NEFFECT_VIB_MIN             1244
#define IDC_NEFFECT_VIB_MAX             1245
#define IDC_NEFFECT_DENSITY_MIN         1246
#define IDC_NEFFECT_DENSITY_MAX         1247
#define IDC_NEFFECT_RED_MIN             1248
#define IDC_NEFFECT_RED_MAX             1249
#define IDC_NEFFECT_GREEN_MIN           1250
#define IDC_NEFFECT_GREEN_MAX           1251
#define IDC_NEFFECT_BLUE_MIN            1252
#define IDC_NEFFECT_BLUE_MAX            1253
#define IDC_NEFFECT_ALPHA_MIN           1254
#define IDC_NEFFECT_ALPHA_MAX           1255
#define ID_NEFFECT_OK                   1256
#define ID_NEFFECT_CANCEL               1257
#define IDC_EVENTID                     1259
#define IDC_TEMPLATE_SETTING            1260
#define IDC_SHOWOBJECTREALPOLYGONINFO   1262
#define IDC_CHECK_RECREATE_ALL          1262
#define IDC_SHOWOBJECTCOLLISIONATOMIC   1263
#define IDC_CHECK1                      1263
#define IDC_CHECK_DESTROY_ALL           1263
#define IDC_CHECK5                      1264
#define IDC_SHOWOBJECTPICKING           1264
#define IDC_OCTREEINFO                  1265
#define IDC_SHOW                        1266
#define IDC_HIDE                        1267
#define IDC_SHOW2                       1268
#define IDC_SET_DEFAULT                 1268
#define IDC_CLOUD_HEIGHT                1269
#define IDC_RADIUS                      1270
#define IDC_SRC_X                       1271
#define IDC_SRC_Z                       1272
#define IDC_DST_X                       1273
#define IDC_DST_Z                       1274
#define IDC_APPLY                       1274
#define IDC_SELECTSKYSET                1275
#define IDC_SKYSETCOMBO                 1277
#define IDC_EXPORTMODE                  1300
#define IDC_HEIGHT_01                   1301
#define IDC_HEIGHT_02                   1302
#define IDC_FENCE_5                     1303
#define ID_BUTTON32779                  32779
#define ID_NEWWORLD                     32782
#define ID_OPEN                         32784
#define ID_IMPORT                       32785
#define ID_BUTTON32786                  32786
#define ID_BUTTON32787                  32787
#define ID_BUTTON32788                  32788
#define ID_BUTTON32800                  32789
#define ID_BUTTON32801                  32790
#define ID_BUTTON32802                  32791
#define ID_BUTTON32803                  32792
#define ID_OPENWORLD                    32794
#define IDS_WORLD                       32795
#define ID_VIEW_ENTITIES                32807
#define ID_FILE_LOADWORLD               32808
#define ID_WHEELBARS_HORIZONTAL         32809
#define ID_WHEELBARS_VERTICAL           32810
#define ID_FILE_OPENGENERIC             32811
#define ID_HELP_FLIGHTMODEL             32812
#define IDS_LIGHT_AMBIENT               32813
#define IDS_LIGHT_SPOT                  32814
#define IDS_LIGHT_SOFTSPOT              32815
#define IDS_LIGHT_DIRECTIONAL           32816
#define ID_VIEW_HORIZONCOMPENSATION     32817
#define ID_FORWARD                      32818
#define IDS_NEWAMBIENT                  32819
#define ID_LEFT                         32820
#define IDS_NEWDIRECTIONAL              32821
#define ID_BACKWARD                     32822
#define IDS_NEWSPOT                     32823
#define ID_RIGHT                        32824
#define IDS_NEWCLUMP                    32825
#define IDS_SNAPTO                      32826
#define ID_FLIGHT_1RPG                  32827
#define IDS_ATTACHANIM                  32828
#define ID_HELP_CONTENTS                32828
#define ID_FLIGHT_MOUSE                 32829
#define IDM_TEST                        32829
#define IDS_TRASH                       32830
#define IDS_NEWSOFTSPOT                 32831
#define IDS_ELEVATION                   32832
#define IDM_TILEWINDOW_ADDCATEGORY      32832
#define IDS_ZDOLLY                      32833
#define IDM_TILEWINDOW_DELETE_CATEGORY  32833
#define IDS_PITCH                       32834
#define IDM_TILEWINDOW_EDIT_CATEGORY    32834
#define IDS_PAN                         32835
#define IDM_TILEWINDOW_EDIT_TILE        32835
#define IDS_YAW                         32836
#define IDS_CONEANGLE                   32837
#define ID_GEOMETRY                     32837
#define IDS_CONERADIUS                  32838
#define ID_TILE                         32838
#define IDS_ZOOM                        32839
#define ID_OBJECT                       32839
#define IDS_ROLL                        32840
#define ID_SUBDIVISION                  32840
#define IDS_DEFAULT_CAMERA              32841
#define IDM_OBJECT_ADDENTRY             32841
#define MSG_ANIMUPDATEFAIL              32842
#define IDM_OBJECT_DELETEENTRY          32842
#define MSG_ANIMATTACHFAIL              32843
#define IDM_OBJECT_EDITENTRY            32843
#define MSG_INVALIDPATH                 32844
#define IDM_SAVE                        32844
#define MSG_BADFILEEXT                  32845
#define IDM_LOAD                        32845
#define MSG_NOTEXTURES                  32846
#define IDM_REVERT                      32846
#define MSG_LOADWORLDFAIL               32847
#define IDM_UNDO                        32847
#define MSG_LOADCLUMPFAIL               32848
#define IDM_REVERT_CURRENT              32848
#define MSG_NOHELPFILE                  32849
#define IDM_REDO                        32849
#define IDS_WORLDFILTER                 32850
#define IDM_CAMERA_WALK_CHANGE          32850
#define IDS_CLUMPFILTER                 32851
#define IDM_UPDATE_NORMAL               32851
#define IDS_ALLFILESFILTER              32852
#define IDM_ADJUST_GEOMETRY_HEIGHT      32852
#define IDS_HELPPATH                    32853
#define IDM_MODECHANGE_GEOMETRY         32853
#define IDS_REGKEY                      32854
#define IDM_MODECHANGE_TILE             -32682
#define IDS_SELECT_TEXTUREDIR           32855
#define IDM_MODECHANGE_OBJECT           32855
#define IDS_ANIMFILTER                  32856
#define IDM_MODECHANGE_SUBDIVISION      32856
#define IDM_CAMERA_POSITION_SAVE1       32857
#define IDM_CAMERA_POSITION_SAVE2       32858
#define IDM_CAMERA_POSITION_SAVE3       32859
#define IDM_CAMERA_POSITION_SAVE4       32860
#define IDM_CAMERA_POSITION_GOTO1       32861
#define IDM_CHANGE_FPS_EDIT_MODE        32861
#define IDM_CAMERA_POSITION_GOTO2       32862
#define IDM_FULL_SCREEN_MODE            32862
#define IDM_CAMERA_POSITION_GOTO3       32863
#define IDM_CAMERA_POSITION_GOTO4       32864
#define IDM_CLIENT_FPS_VIEW             32864
#define IDM_TILE_SPOID_BACK             32865
#define IDM_TILE_SPOID_ALPHA            32866
#define IDM_TILE_SPOID_ALL              32867
#define IDM_GRID_TOGGLE                 32868
#define IDM_CAMERA_RESET                32869
#define IDM_CAMERA_FIRST_PERSON         32870
#define IDM_BSP_EXPORT                  32871
#define IDM_TONG_MAP_HAP_CHI_GI         32872
#define IDM_CREATESECTOR                32873
#define IDM_HELP_KEYREFERENCE           32874
#define IDM_OPTIMIZE_POLYGON_REDUCTION  32875
#define IDM_OPTIMIZE_TRASH_MATERIAL_REMOVE 32876
#define IDM_GENERATE_ROUGHMAP           32877
#define IDM_DWSECTOR_EACHEACH           32878
#define IDM_DWSECTOR_ALL_ROUGH          32879
#define IDM_DWSECTOR_ALL_DETAIL         32880
#define IDM_DWSECTOR_ACCORDINGTOCURSOR  32881
#define IDM_OPTIMIZE_ADJUST_EDGE        32882
#define IDM_CREATESECTOR_DETAIL         32883
#define IDM_TOGGLE_CAMERA_PROJECTIONTYPE 32884
#define IDM_UPDATE_ALL                  32885
#define IDM_EDIT_CREATE_ALPHA           32886
#define IDM_EXPORT_TILE                 32887
#define IDM_SMOOTH_GEOMETRY             32888
#define IDM_EDIT_CREATE_ALL_SECTOR      32889
#define IDM_BRUSH_SIZE_UP               32890
#define IDM_BRUSH_SIZE_DOWN             32891
#define IDM_FILL_TILE                   32892
#define IDM_OPEN_OPTION_DIALOG          32894
#define IDM_TOGGLE_FP_VIEW              32895
#define IDM_REFREAH_OBJECT_BLOCKING     32896
#define IDM_VIEW_GRID_NOGRID            32897
#define IDM_VIEW_GRID_FEW               32898
#define IDM_VIEW_GRID_NORMAL            32899
#define IDM_VIEW_GRID_LOT               32900
#define IDM_VIEW_BLOCKING_GEOMETRY      32901
#define IDM_VIEW_BLOCKING_OBJECT        32902
#define IDM_VIEW_TOGGLE_OBJECT          32903
#define IDM_OBJECT_TEST                 32904
#define IDM_OBJECT_PROPERTY             32904
#define IDM_VIEW_CLIPPLANE              32905
#define IDM_OBJECT_EVENT                32906
#define IDM_SKY_SETTING                 32907
#define IDM_TOGGLE_TIMER                32911
#define IDM_TONG_MAP_APPLY              32912
#define IDM_OBJECT_REFRESH              32913
#define IDM_ADD_WATER                   32914
#define IDM_MODECHANGE_GEOMETRY_REVERSE 32916
#define IDM_MODECHANGE_TILE_REVERSE     32917
#define IDM_VIEW_SKY_TEMPLATE           32918
#define IDM_VIEW_WATERDLG               32919
#define IDM_ANOTHER_GRID_TOGGLE         32920
#define IDM_TIME_SLOWER                 32921
#define IDM_TIME_FASTER                 32922
#define IDM_PRELIGHT_ADJUST             32923
#define IDM_EDIT_CREATE_COLLISION       32924
#define IDM_SKY_VALUE_CHANGE            32925
#define IDM_TEST_ADD                    32926
#define IDM_TEST_SUB                    32927
#define IDM_VIEW_PROJECTION             32928
#define IDM_FILE_MINIMAPEXPORT          32929
#define IDM_FILE_CLOSETEMPFILE          32931
#define IDM_FILE_OBJECT_EXPORT_FOR_SERVER 32932
#define IDM_FILE_DDS_CONVERT            32933
#define IDM_OPEN_SHORTCUT               32934
#define IDM_MENU_TOGGLE_TIMER           32935
#define IDM_OPEN_SHORTCUT2              -32600
#define IDM_CLEANUP_UNUSED_TEXTURE      32937
#define IDM_VIEW_ATOMICFILTER           32938
#define IDM_EVENTNATURE_FILTER          32939
#define IDM_EDIT_UPDATECOLLISION        32940
#define IDM_MODE_DUNGEON_TOGGLE         32941
#define IDM_CAMERA_SAVE                 32942
#define IDM_CAMERA_LOAD                 32943
#define IDM_FINDOBJECT                  32945
#define IDM_FINDOBJECTNEXT              32946
#define IDM_OBJECTPOPUP_TAKETEMPLATEINFO 32949
#define IDM_TURN90CW                    32950
#define ID_Menu                         32952
#define IDM_SELECTALL                   32955
#define IDM_TILEPOPUP_CHANGETILE        32959
#define IDM_TILEWINDOW_DELETE_TILE      32960
#define IDM_OBJECTPOP_OCTREEROOTDISPLAY 32962
#define IDM_OBJECTPOP_GROUPSAVE         32963
#define ID_Menu32964                    32964
#define ID_VIEW_ROUGHDISPLAY            32965
#define IDS_ERROR_POPUP_DIALOG          61204

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        305
#define _APS_NEXT_COMMAND_VALUE         32968
#define _APS_NEXT_CONTROL_VALUE         1278
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
