# What plugin are we building ?

PLUGIN = rtskinsp

# Who are the maintainers ?
MAINTAINERS = colinh

CSRC = \
	$(CURDIR)/skinsplit.c

ifndef BASEDIR
BASEDIR = $(CURDIR)/../..
endif
include $(BASEDIR)/makeincl/maketool
