PLUGIN = rttoon

# Who are the maintainers ?
MAINTAINERS = markj

ifndef BASEDIR
BASEDIR = $(CURDIR)/../..
endif
include $(BASEDIR)/makeincl/maketool

DOXYSRC := $(CURDIR)/$(PLUGIN).h $(CURDIR)/$(PLUGIN).cpp
