#define HACKSHIELD_ERROR_SUCESS					( 0x00000000 )
#define HACKSHIELD_ERROR						( 0x30000000 )

#define HSERROR_ENVFILE_NOTREAD					( HACKSHIELD_ERROR + 0x10 )
#define HSERROR_ENVFILE_NOTWRITE				( HACKSHIELD_ERROR + 0x20 )
#define HSERROR_NETWORK_CONNECT_FAIL			( HACKSHIELD_ERROR + 0x30 )
#define HSERROR_INVALID_PRODUCT_NUMBER			( HACKSHIELD_ERROR + 0x40 )
#define HSERROR_LIB_NOTEDIT_REG					( HACKSHIELD_ERROR + 0x50 )
#define HSERROR_NOTFINDFILE						( HACKSHIELD_ERROR + 0x60 )

#define HSERROR_PROTECT_LISTLOAD_FAIL			( HACKSHIELD_ERROR + 0x70 )
#define HSERROR_PROTECT_VERITY_FAIL				( HACKSHIELD_ERROR + 0x80 )
#define HSERROR_HSUPDATE_TIMEOUT				( HACKSHIELD_ERROR + 0x90 )

DWORD __stdcall _AhnHS_HSUpdate( LPCTSTR szUpdateDir, DWORD dwTimeOut );

