//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by AgcmAdminDlgXT.rc
//
#define IDC_E_CHAR_SEARCH_DATA          1015
#define IDC_BTN_SEARCH_SEARCH           1016
#define IDC_LV_SEARCH_RESULT            1017
#define IDC_BTN_SEARCH_ADD              1018
#define IDC_BTN_SEARCH_GO               1019
#define IDC_BTN_SEARCH_MODIFY           1020
#define IDC_BTN_SEARCH_GM               1021
#define IDC_CB_SEARCH_TYPE              1095
#define IDC_CB_SEARCH_FIELD             1096
#define IDC_B_HELP_COMPLETE             1134
#define IDC_B_HELP_DEFER                1135
#define IDC_B_HELP_DELIVER              1136
#define IDC_B_HELP_REJECT               1137
#define IDC_B_HELP_DELETE               1138
#define IDC_B_HELP_MEMO_SAVE            1139
#define IDC_B_HELP_GO                   1140
#define IDC_E_HELP_CHAT                 1142
#define IDC_E_HELP_CHAT_SEND            1143
#define IDD_MAIN                        7000
#define IDC_LS_MAIN_OBJECT              7001
#define IDM_MAIN                        7001
#define IDC_E_MAIN_INFO                 7002
#define IDD_SEARCH                      7002
#define IDC_E_MAIN_MOVE_X               7003
#define IDD_CHAR_DATA                   7003
#define IDC_E_MAIN_MOVE_X2              7004
#define IDD_HELP                        7004
#define IDC_E_MAIN_MOVE_Y               7004
#define IDC_CB_MAIN_MOVE_PLACE          7005
#define IDC_E_MAIN_MOVE_X3              7006
#define IDC_E_MAIN_MOVE_Z               7006
#define IDC_E_MAIN_MOVE_PC              7008
#define IDD_MOVE                        7008
#define IDC_E_MAIN_MOVE_TARGET          7009
#define IDC_B_MAIN_MOVE_GO              7010
#define IDM_MOVE                        7010
#define IDC_LV_MAIN_HELP                7011
#define IDD_BAN                         7011
#define IDC_S_MAIN_NUM_GM               7012
#define IDC_S_MAIN_ADMIN_COUNT          7012
#define IDC_S_MAIN_NUM_HELP             7013
#define IDD_ITEM                        7013
#define IDC_S_MAIN_HELP_COUNT           7013
#define IDC_CB_CHAR_VIEW                7014
#define IDC_S_MAIN_CURRENT_USER         7014
#define IDC_E_CHAR_VIEW_INFO            7015
#define IDI_ICON_BLACK                  7015
#define IDC_BTN_CHAR_REFRESH            7016
#define IDD_ADMIN_LIST                  7016
#define IDC_CH_CHAR_RELOAD              7017
#define IDD_NOTICE                      7017
#define IDC_S_CHAR_BASIC_PLACE          7018
#define IDC_S_VIEW_PLACE                7019
#define IDD_CHAR_ITEM                   7019
#define IDC_PROPERTY_GRID_CHAR          7020
#define IDC_BTN_CHAR_REALVIEW           7020
#define IDD_GAME                        7020
#define IDC_LV_HELP_LIST                7021
#define IDC_BTN_CHAR_BAN                7021
#define IDC_PROPERTY_GRID_ITEM          7022
#define IDC_PROPERTY_GRID_SKILL         7023
#define IDC_E_HELP_MSG                  7024
#define IDC_PROPERTY_GRID_PARTY         7025
#define IDC_E_MOVE_MOVE_PC              7025
#define IDC_E_HELP_MEMO                 7026
#define IDC_E_MOVE_MOVE_TARGET          7026
#define IDC_PROPERTY_GRID_HELP_CHAR     7027
#define IDC_CB_MOVE_MOVE_PLACE          7027
#define IDC_E_MOVE_MOVE_X               7028
#define IDC_E_MOVE_MOVE_Y               7029
#define IDC_E_MOVE_MOVE_Z               7030
#define IDC_B_MOVE_MOVE_GO              7031
#define IDC_S_CHARNAME                  7032
#define IDC_CB_CHAT_BAN_TIME            7033
#define IDC_S_CHAT_BAN_START            7034
#define IDC_CB_CHAR_BAN_TIME            7035
#define IDC_S_CHAR_BAN_START            7036
#define IDC_CB_ACC_BAN_TIME             7037
#define IDC_S_ACC_BAN_START             7038
#define IDC_B_BAN_LOGOUT                7039
#define IDC_S_ACCNAME                   7040
#define IDC_B_BAN_APPLY                 7041
#define IDC_B_BAN_CANCEL                7042
#define IDC_CH_CHATBAN_MODIFY           7043
#define IDC_CH_CHARBAN_MODIFY           7044
#define IDC_B_CHAT_SEND                 7044
#define IDC_CH_ACCBAN_MODIFY            7045
#define IDC_B_ITEM_CREATE               7045
#define IDC_CB_ITEM_TID                 7046
#define IDC_ITEM_DRAW_PLACE             7047
#define IDC_E_ITEM_COUNT                7048
#define IDC_CB_ITEM_RUNE_TID            7049
#define IDC_LV_ADMIN                    7050
#define IDC_B_ADMIN_SELECT              7051
#define IDC_ITEM_DRAW_PLACE2            7051
#define IDC_R_ITEM_CREATE               7052
#define IDC_R_ITEM_CONVERT              7053
#define IDC_S_ITEM_PROPERTY             7054
#define IDC_S_ITEM_CONVERT_TYPE         7055
#define IDC_B_ITEM_CONVERT              7056
#define IDC_CB_ITEM_SPIRIT_STONE_TID    7057
#define IDC_CB_ITEM_EGO_TID             7058
#define IDC_S_ITEM_INVENTORY_POS        7059
#define IDC_CHAR_DRAW_PLACE             7060
#define IDC_B_NOTICE                    7062
#define IDC_E_NOTICE                    7063
#define IDC_B_CHAR_ITEM_GRID_1_1        7064
#define IDC_CB_CHAR_ITEM_INDEX          7065
#define IDC_E_CHAR_ITEM_DESC            7066
#define IDC_S_CHAR_VIEW_CHARNAME        7067
#define IDC_B_CHAR_ITEM_GRID_1_2        7068
#define IDC_E_CHAR_ITEM_INVEN_MONEY     7069
#define IDC_B_CHAR_ITEM_GRID_1_3        7070
#define IDC_B_CHAR_ITEM_GRID_1_4        7071
#define IDC_B_CHAR_ITEM_GRID_2_1        7072
#define IDC_B_CHAR_ITEM_GRID_2_2        7073
#define IDC_B_CHAR_ITEM_GRID_2_3        7074
#define IDC_B_CHAR_ITEM_GRID_2_4        7075
#define IDC_B_CHAR_ITEM_GRID_3_1        7076
#define IDC_B_CHAR_ITEM_GRID_3_2        7077
#define IDC_B_CHAR_ITEM_GRID_3_3        7078
#define IDC_B_CHAR_ITEM_GRID_3_4        7079
#define IDC_B_CHAR_ITEM_GRID_4_1        7080
#define IDC_B_CHAR_ITEM_GRID_4_2        7081
#define IDC_B_CHAR_ITEM_GRID_4_3        7082
#define IDC_B_CHAR_ITEM_GRID_4_4        7083
#define IDC_B_CHAR_ITEM_GRID_5_1        7084
#define IDC_B_CHAR_ITEM_GRID_5_2        7085
#define IDC_B_CHAR_ITEM_GRID_5_3        7086
#define IDC_B_CHAR_ITEM_GRID_5_4        7087
#define IDC_B_CHAR_ITEM_GRID_6_1        7088
#define IDC_B_CHAR_ITEM_GRID_6_2        7089
#define IDC_B_CHAR_ITEM_GRID_6_3        7090
#define IDC_B_CHAR_ITEM_GRID_6_4        7091
#define IDC_B_CHAR_ITEM_GRID_7_1        7092
#define IDC_B_CHAR_ITEM_GRID_7_2        7093
#define IDC_B_CHAR_ITEM_GRID_7_3        7094
#define IDC_B_CHAR_ITEM_GRID_7_4        7095
#define IDC_E_CHAR_ITEM_BANK_MONEY      7096
#define IDC_B_CHAR_ITEM_REFRESH         7097
#define IDC_T_USER_STATUS               7098
#define IDC_L_USER_LIST                 7100
#define IDC_E_CHAT_SEND                 7101
#define IDC_R_CHAT                      7102
#define IDC_CB_SEND_TYPE                7103
#define IDM_FILE_CLOSE                  32771
#define IDM_OBJECT_SELECT               32773
#define IDM_OBJECT_DEL                  32774
#define IDM_OBJECT_CLEAR                32775
#define IDM_TOOL_SEARCH                 32776
#define IDM_TOOL_CHARACTER              32777
#define IDM_TOOL_HELP                   32778
#define IDM_HELP_ABOUT                  32779
#define IDM_TOOL_MOVE                   32780
#define IDM_HELP_SELECT                 32781
#define IDM_MOVE_FILE_CLOSE             32782
#define IDM_MOVE_EDIT_NORMAL            32783
#define IDM_MOVE_EDIT_ADD               32784
#define IDM_MOVE_EDIT_REMOVE            32785
#define IDM_TOOL_ITEM                   32786
#define IDM_TOOL_ADMIN_LIST             32787
#define IDM_TOOL_NOTICE                 32788

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        7021
#define _APS_NEXT_COMMAND_VALUE         32789
#define _APS_NEXT_CONTROL_VALUE         7104
#define _APS_NEXT_SYMED_VALUE           7000
#endif
#endif
