// Resource.h resources used by PropertyGrid classes.
//
// This file is a part of the XTREME PROPERTYGRID MFC class library.
// (c)1998-2007 Codejock Software, All Rights Reserved.
//
// THIS SOURCE FILE IS THE PROPERTY OF CODEJOCK SOFTWARE AND IS NOT TO BE
// RE-DISTRIBUTED BY ANY MEANS WHATSOEVER WITHOUT THE EXPRESSED WRITTEN
// CONSENT OF CODEJOCK SOFTWARE.
//
// THIS SOURCE CODE CAN ONLY BE USED UNDER THE TERMS AND CONDITIONS OUTLINED
// IN THE XTREME TOOLKIT PRO LICENSE AGREEMENT. CODEJOCK SOFTWARE GRANTS TO
// YOU (ONE SOFTWARE DEVELOPER) THE LIMITED RIGHT TO USE THIS SOFTWARE ON A
// SINGLE COMPUTER.
//
// CONTACT INFORMATION:
// support@codejock.com
// http://www.codejock.com
//
/////////////////////////////////////////////////////////////////////////////

#define XTP_PROPERTYGRID_RESOURCE_FIRST          9500
#define XTP_PROPERTYGRID_RESOURCE_LAST           9459

#define XTP_IDR_PROPERTYGRID_TOOLBAR             9500
#define XTP_IDC_PROPERTYGRID_CATEGORIZED         9501
#define XTP_IDC_PROPERTYGRID_ALPHABETIC          9502
#define XTP_IDS_PROPERTYGRID_TRUEFALSE           9503
