PLUGIN = rtworld

# Who are the maintainers ?
MAINTAINERS = ads callan 

# since this tool contains multiple object files - define the extra ones
# here. The standard ones are added by 'maketool'

CSRC =						\
	$(CURDIR)/imputil.c			\
	$(CURDIR)/optimise.c

ifndef BASEDIR
BASEDIR = $(CURDIR)/../..
endif
include $(BASEDIR)/makeincl/maketool

