# What plugin are we building ?

PLUGIN = rpuvanim

# Who are the maintainers ?
MAINTAINERS = gregb

# Additional objects
CSRC=						\
	$(CURDIR)/stdkey.c      \
	$(CURDIR)/linear.c      \
	$(CURDIR)/param.c

ifndef BASEDIR
BASEDIR = $(CURDIR)/../..
endif
include $(BASEDIR)/makeincl/makeplug

