# What plugin are we building ?

PLUGIN = rppvs

# Who are the maintainers ?
MAINTAINERS = adamj colinh

# Additional objects
CSRC =						\
	$(CURDIR)/rppvs.c			\
	$(CURDIR)/rppvsaux.c

ifndef BASEDIR
BASEDIR = $(CURDIR)/../..
endif
include $(BASEDIR)/makeincl/makeplug
