PLUGIN = rtcmpkey

# Who are the maintainers ?
MAINTAINERS = blakem

CSRC =						\
	$(CURDIR)/rtcmpkey.c			\
	$(CURDIR)/stdkeycnv.c

ifndef BASEDIR
BASEDIR = $(CURDIR)/../..
endif
include $(BASEDIR)/makeincl/maketool


