//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by AgcmAdminDlg.rc
//
#define IDD_MAIN                        101
#define IDM_MAIN                        102
#define IDD_CHAR_DATA                   103
#define IDD_SEARCH                      104
#define IDD_CHAR_ITEM                   105
#define IDD_CHAR_SKILL                  107
#define IDD_CHAR_SKILL_SUB              108
#define IDD_CHAR_PARTY                  109
#define IDD_HELP                        111
#define IDD_CHAR_MOVE                   112
#define IDC_BTN_MAIN_CLEAR              1007
#define IDC_BT_CHARINFO_CHARID          1007
#define IDC_BT_CHARINFO_CHARNAME        1008
#define IDC_BTN_MAIN_GO                 1008
#define IDC_BTN_MAIN_MODIFY             1009
#define IDC_E_CHARINFO_CHARID           1009
#define IDC_E_CHARINFO_CHARNAME         1010
#define IDC_LS_MAIN_OBJECT              1010
#define IDC_ST_SERVER                   1011
#define IDC_BT_CHARINFO_ACCNAME         1011
#define IDC_E_CHARINFO_ACCNAME          1012
#define IDC_BTN_MAIN_HELP               1012
#define IDC_BT_CHARINFO_RACE            1013
#define IDC_BTN_MAIN_DEL                1013
#define IDC_E_CHARINFO_RACE             1014
#define IDC_BT_CHARINFO_CLASS           1015
#define IDC_E_CHAR_SEARCH_DATA          1015
#define IDC_E_CHARINFO_CLASS            1016
#define IDC_BTN_SEARCH_SEARCH           1016
#define IDC_BT_CHARINFO_EXP             1017
#define IDC_LV_SEARCH_RESULT            1017
#define IDC_E_CHARINFO_EXP              1018
#define IDC_BTN_SEARCH_ADD              1018
#define IDC_BT_CHARINFO_LEV             1019
#define IDC_BTN_SEARCH_GO               1019
#define IDC_E_CHARINFO_LEV              1020
#define IDC_BTN_SEARCH_MODIFY           1020
#define IDC_BT_CHARINFO_CREDATE         1021
#define IDC_BTN_SEARCH_GM               1021
#define IDC_E_CHARINFO_CREDATE          1022
#define IDC_BT_CHARINFO_NAME            1023
#define IDC_E_CHARINFO_NAME             1024
#define IDC_BT_CHARINFO_LOGIN           1025
#define IDC_E_CHARINFO_LOGIN            1026
#define IDC_BT_CHARINFO_PLAYTIME        1027
#define IDC_E_CHARINFO_PLAYTIME         1028
#define IDC_BT_CHARINFO_XYZ             1029
#define IDC_E_CHARINFO_XYZ              1030
#define IDC_BT_CHARINFO_IP              1031
#define IDC_E_CHARINFO_IP               1032
#define IDC_BT_CHARINFO_LOGOUT          1033
#define IDC_E_CHARINFO_LOGOUT           1034
#define IDC_BT_CHARINFO_LAST_PLAYTIME   1035
#define IDC_E_CHARINFO_LAST_PLAYTIME    1036
#define IDC_BT_CHARINFO_LAST_XYZ        1037
#define IDC_E_CHARINFO_LAST_XYZ         1038
#define IDC_BT_CHARINFO_LAST_IP         1039
#define IDC_E_CHARINFO_LAST_IP          1040
#define IDC_BT_CHARINFO_STR             1041
#define IDC_E_CHARINFO_STR              1042
#define IDC_BT_CHARINFO_DEX             1043
#define IDC_E_CHARINFO_DEX              1044
#define IDC_BT_CHARINFO_CON             1045
#define IDC_E_CHARINFO_CON              1046
#define IDC_BT_CHARINFO_WIS             1047
#define IDC_E_CHARINFO_WIS              1048
#define IDC_BT_CHARINFO_INT             1049
#define IDC_E_CHARINFO_INT              1050
#define IDC_BT_CHARINFO_CHA             1051
#define IDC_E_CHARINFO_CHA              1052
#define IDC_BT_CHARINFO_HP              1053
#define IDC_E_CHARINFO_HP               1054
#define IDC_BT_CHARINFO_MAXHP           1055
#define IDC_E_CHARINFO_MAXHP            1056
#define IDC_BT_CHARINFO_MP              1057
#define IDC_E_CHARINFO_MP               1058
#define IDC_BT_CHARINFO_MAXMP           1059
#define IDC_E_CHARINFO_MAXMP            1060
#define IDC_BT_CHARINFO_SP              1061
#define IDC_E_CHARINFO_SP               1062
#define IDC_BT_CHARINFO_MAXSP           1063
#define IDC_E_CHARINFO_MAXSP            1064
#define IDC_BT_CHARINFO_AC              1065
#define IDC_E_CHARINFO_AC               1066
#define IDC_BT_CHARINFO_ATK             1067
#define IDC_E_CHARINFO_ATK              1068
#define IDC_BT_CHARINFO_MAGICATK        1069
#define IDC_E_CHARINFO_MAGICATK         1070
#define IDC_BT_CHARINFO_MINDMG          1071
#define IDC_E_CHARINFO_MINDMG           1072
#define IDC_BT_CHARINFO_MAXDMG          1073
#define IDC_E_CHARINFO_MAXDMG           1074
#define IDC_BT_CHARINFO_FIRE            1075
#define IDC_E_CHARINFO_FIRE             1076
#define IDC_BT_CHARINFO_WATER           1077
#define IDC_E_CHARINFO_WATER            1078
#define IDC_BT_CHARINFO_EARTH           1079
#define IDC_E_CHARINFO_EARTH            1080
#define IDC_BT_CHARINFO_WIND            1081
#define IDC_E_CHARINFO_WIND             1082
#define IDC_BT_CHARINFO_MAGIC           1083
#define IDC_E_CHARINFO_MAGIC            1084
#define IDC_BT_CHARINFO_INVMONEY        1085
#define IDC_E_CHARINFO_INVMONEY         1086
#define IDC_BT_CHARINFO_STOMONEY        1087
#define IDC_E_CHARINFO_STOMONEY         1088
#define IDC_BT_CHARINFO_MURDER          1089
#define IDC_BT_CHARINFO_EDIT_FIELD      1090
#define IDC_E_CHARINFO_EDIT_DATA        1091
#define IDC_BT_CHARINFO_EDIT_ENTER      1092
#define IDC_BT_CHARINFO_EDIT_CANCEL     1093
#define IDC_S_EDIT_GROUP                1094
#define IDC_CB_SEARCH_TYPE              1095
#define IDC_E_CHARINFO_MURDER           1095
#define IDC_CB_SEARCH_FIELD             1096
#define IDC_BT_CHARINFO_UT              1096
#define IDC_E_MAIN_INFO                 1097
#define IDC_E_CHARINFO_UT               1097
#define IDC_BT_CHARINFO_STATUS          1098
#define IDC_E_CHARINFO_STATUS           1099
#define IDC_LV_CHAR_ITEM_BASIC          1100
#define IDC_CB_CHAR_ITEM_POS            1101
#define IDC_BT_CHAR_ITEM_REFRESH        1102
#define IDC_LV_CHAR_ITEM_LIST           1103
#define IDC_E_CHAR_ITEM_DETAIL          1104
#define IDC_BT_CHAR_SKILL_ROLLBACK      1104
#define IDC_BT_CHAR_SKILL_ROLLBACK_COUNT 1105
#define IDC_E_CHAR_SKILL_ROLLBACK_COUNT 1106
#define IDC_BT_CHAR_SKILL_SAVE          1107
#define IDC_S_CHARINFO_SERVERID         1108
#define IDC_LV_CHAR_SKILL_BASIC         1109
#define IDC_CB_CHAR_SKILL_TYPE          1110
#define IDC_E_CHAR_SKILLSUB_SP1         1111
#define IDC_BT_CHAR_SKILL_REFRESH       1111
#define IDC_BT_CHAR_PARTY_RESET         1112
#define IDC_LV_CHAR_SKILL_LIST          1112
#define IDC_E_CHAR_SKILLSUB_SP2         1112
#define IDC_E_CHAR_SKILLSUB_SP3         1113
#define IDC_E_CHAR_SKILLSUB_SP4         1114
#define IDC_LV_CHAR_SKILLSUB_BASIC      1115
#define IDC_CB_CHAR_SKILLSUB_TYPE       1116
#define IDC_LV_CHAR_SKILLSUB_LIST       1117
#define IDC_BT_CHAR_SKILLSUB_ROLLBACK   1118
#define IDC_BT_CHAR_SKILLSUB_ROLLBACK_COUNT 1119
#define IDC_E_CHAR_SKILLSUB_ROLLBACK_COUNT 1120
#define IDC_BT_CHAR_SKILLSUB_SAVE       1121
#define IDC_LV_CHAR_PARTY_BASIC         1122
#define IDC_E_CHAR_SKILLSUB_SP5         1122
#define IDC_BT_CHAR_PARTY_REFRESH       1123
#define IDC_LV_CHAR_PARTY_LIST          1124
#define IDC_LV_MAIN_HELP                1125
#define IDC_LV_HELP_LIST                1126
#define IDC_B_HELP_REFRESH              1127
#define IDC_LV_HELP_BASIC               1128
#define IDC_B_HELP_GO                   1129
#define IDC_B_HELP_MODIFY               1130
#define IDC_B_HELP_GM                   1131
#define IDC_B_HELP_XYZ                  1132
#define IDC_E_HELP_MSG                  1133
#define IDC_B_HELP_COMPLETE             1134
#define IDC_B_HELP_DEFER                1135
#define IDC_B_HELP_DELIVER              1136
#define IDC_B_HELP_REJECT               1137
#define IDC_B_HELP_DELETE               1138
#define IDC_E_HELP_MEMO                 1139
#define IDC_B_HELP_SAVE                 1140
#define IDC_B_HELP_CANCEL               1141
#define IDC_E_HELP_CHAT                 1142
#define IDC_E_HELP_CHAT_SEND            1143
#define IDC_S_HELP_SERVERID             1144
#define IDC_E_CHAR_MOVE_NAME            1145
#define IDC_B_HELP_CHAT_SEND            1145
#define IDC_E_CHAR_MOVE_X               1146
#define IDC_E_CHAR_MOVE_Y               1147
#define IDC_E_CHAR_MOVE_Z               1148
#define IDC_B_CHAR_MOVE_GO              1149
#define IDC_C_CHAR_MOVE_SELF            1150
#define IDM_FILE_CLOSE                  40001
#define IDM_TOOL_CHARACTER              40002
#define IDM_TOOL_SEARCH                 40005
#define IDM_TOOL_HELP                   40006

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        113
#define _APS_NEXT_COMMAND_VALUE         40007
#define _APS_NEXT_CONTROL_VALUE         1152
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
