#ifndef	_ACUIRECRUITWRITE_H_
#define _ACUIRECRUITWRITE_H_

#include "AcUIControlHeader.h"

#define	ACUIRECRUITWRITE_WIDTH					258
#define	ACUIRECRUITWRITE_HEIGHT					276
#define ACUIRECRUITWRITE_CLASS_NUM				4
#define ACUIRECRUITWRITE_PURPOSTEDIT_X			43
#define ACUIRECRUITWRITE_PURPOSTEDIT_Y			70
#define ACUIRECRUITWRITE_PURPOSTEDIT_WIDTH		169
#define ACUIRECRUITWRITE_PURPOSTEDIT_HEIGHT		24
#define	ACUIRECRUITWRITE_PERSONNUMEDIT_X		100
#define	ACUIRECRUITWRITE_PERSONNUMEDIT_Y		100
#define	ACUIRECRUITWRITE_PERSONNUMEDIT_WIDTH	100
#define	ACUIRECRUITWRITE_PERSONNUMEDIT_HEIGHT	20
#define	ACUIRECRUITWRITE_LEVELMIN_X				100
#define	ACUIRECRUITWRITE_LEVELMIN_Y				122
#define	ACUIRECRUITWRITE_LEVELMAX_X				152
#define	ACUIRECRUITWRITE_LEVELMAX_Y				122
#define	ACUIRECRUITWRITE_LEVELEDIT_WIDTH		48
#define ACUIRECRUITWRITE_LEVELEDIT_HEIGHT		20
#define ACUIRECRUITWRITE_CLASSPUSH_X			45	
#define ACUIRECRUITWRITE_CLASSPUSH_Y			170
#define ACUIRECRUITWRITE_CLASSPUSH_WIDTH		21
#define ACUIRECRUITWRITE_CLASSPUSH_HEIGHT		30
#define ACUIRECRUITWRITE_CLASSPUSH_X_GAP		83
#define ACUIRECRUITWRITE_CLASSPUSH_Y_GAP		31
#define ACUIRECRUITWRITE_WRITE_BUTTON_X			29		
#define ACUIRECRUITWRITE_WRITE_BUTTON_Y			234	
#define ACUIRECRUITWRITE_CANCEL_BUTTON_X		73
#define ACUIRECRUITWRITE_CANCEL_BUTTON_Y		234
#define ACUIRECRUITWRITE_MODIFY_BUTTON_X		117
#define ACUIRECRUITWRITE_MODIFY_BUTTON_Y		234
#define ACUIRECRUITWRITE_DELETE_BUTTON_X		161
#define ACUIRECRUITWRITE_DELETE_BUTTON_Y		234
#define	ACUIRECRUITWRITE_BUTTON_WIDTH			21
#define	ACUIRECRUITWRITE_BUTTON_HEIGHT			29

enum 
{
	ACUIRECRUITWRITE_CONTROLID_WRITE			=	0	, 
	ACUIRECRUITWRITE_CONTROLID_CANCEL			=	1	,
	ACUIRECRUITWRITE_CONTROLID_MODIFY			=	2	,
	ACUIRECRUITWRITE_CONTROLID_DELETE			=	3	, 
	ACUIRECRUITWRITE_CONTROLID_PURPOSE_EDIT		=	4	, 
	ACUIRECRUITWRITE_CONTROLID_PERSONNUM_EDIT	=	5	,
	ACUIRECRUITWRITE_CONTROLID_LEVEL_MIN		=	6	,
	ACUIRECRUITWRITE_CONTROLID_LEVEL_MAX				
};

class AgcmRecruit;

class AcUIRecruitWrite : public AcUIModalImage
{
public:
	AcUIRecruitWrite();

public:
	AgcmRecruit*	m_pAgcmRecruit	;	// Recruit Client Module Pointer

	AcUIEdit		m_clPurpose		;	// 파티목적 
	AcUIEdit		m_clPersonNum	;	// 필요인원
	AcUIEdit		m_clLevelMin	;	// 필요레벨 Min
	AcUIEdit		m_clLevelMax	;	// 필요레벨	Max
	AcUIPushButton	m_clClassPush[ACUIRECRUITWRITE_CLASS_NUM]	; // Class고르기 Push Button
	AcUIButton		m_clWrite		;
	AcUIButton		m_clCancel		;
	AcUIButton		m_clModify		;
	AcUIButton		m_clDelete		;

public:
	void	SetWriteWindowInit()	;	// Write Window 내의 Control들을 초기화한다
	void	SetWriteWindowClose()	;	// Write Window 내의 Control들을 종료 처리 한다 - Edit
	void	SetNextEdit()			;
	void	SetModulePointer( AgcmRecruit* pAgcmRecruit );
	void	OnClickWriteButton()	;

public:
	virtual	BOOL OnInit			(					); 
	virtual BOOL OnLButtonDown	( RsMouseStatus* ms );
	virtual BOOL OnCommand		( INT32	nID , PVOID pParam	);
};

#endif //_ACUIRECRUITWRITE_H_