#if !defined(AFX_ACUICONTROLHEADER_H__47C0CAA3_54B8_442C_96AA_C5B96FE97A62__INCLUDED_)
#define AFX_ACUICONTROLHEADER_H__47C0CAA3_54B8_442C_96AA_C5B96FE97A62__INCLUDED_

#include "AcUIBase.h"
#include "AcUIBar.h"
#include "AcUIList.h"
#include "AcUISkillTree.h"
#include "AcUIButton.h"
#include "AcUICheckBox.h"
#include "AcUIBbs.h"
#include "AcUIBbsContent.h"
#include "AcUIEdit.h"
#include "AcUIMessageDialog.h"
#include "AcUIModalImage.h"
#include "AcUITexture.h"
#include "AcUIToolTip.h"
#include "AcUICombo.h"
#include "AcUIGrid.h"
#include "AcUIScroll.h"
#include "AcUITree.h"
#include "AcUIClock.h"

// AgcmUIManager¿¡ Coltrol ID
enum	
{
	ACUI_CTRID_BUTTON_0				=	1,
	ACUI_CTRID_BUTTON_1				=	2,
	ACUI_CTRID_BUTTON_2				=	3,
	ACUI_CTRID_BUTTON_3				=	4,
	ACUI_CTRID_BUTTON_4				=	5,
	ACUI_CTRID_BUTTON_5				=	6,
	ACUI_CTRID_BUTTON_6				=	7,			//LevelUp
	ACUI_CTRID_BUFF_1				=	8,
	ACUI_CTRID_BUFF_2				=	9,
	ACUI_CTRID_BUFF_3				=	10,
	ACUI_CTRID_BUFF_4				=	11,
	ACUI_CTRID_BUFF_5				=	12,
	ACUI_CTRID_BUFF_6				=	13,
	ACUI_CTRID_BUFF_7				=	14,
	ACUI_CTRID_BUFF_8				=	15,
	ACUI_CTRID_BUFF_9				=	16,
	ACUI_CTRID_SKILL_1				=	17,
	ACUI_CTRID_SKILL_2				=	18,
	ACUI_CTRID_SKILL_3				=	19,
	ACUI_CTRID_SKILL_4				=	20,
	ACUI_CTRID_SKILL_5				=	21,
	ACUI_CTRID_SKILL_6				=	22,
	ACUI_CTRID_SKILL_7				=	23,
	ACUI_CTRID_SKILL_8				=	24,
	ACUI_CTRID_SKILL_9				=	25,
	ACUI_CTRID_INVENTORY			=	26,
	ACUI_CTRID_EQUIPMENT			=	27,
	ACUI_CTRID_NPCINVENTORY			=	28, 
	ACUI_CTRID_MYTRADECONFIRM		=	29,
	ACUI_CTRID_HISTRADECONFIRM		=	30,
	ACUI_CTRID_RECRUIT				=	31,
	ACUI_CTRID_RECRUIT_BBS1			=	32,
	ACUI_CTRID_RECRUIT_BBS2			=	33,
	ACUI_CTRID_RECRUIT_TAB1			=	34,
	ACUI_CTRID_RECRUIT_TAB2			=	35,
	ACUI_CTRID_RECRUIT_FIND1		=	36,
	ACUI_CTRID_RECRUIT_FIND2		=	37,
	ACUI_CTRID_RECRUIT_CLOSE		=	38,
	ACUI_CTRID_CHARACTER_STATUS		=	39,
	ACUI_CTRID_CS_EXPAND			=	40,
	ACUI_CTRID_PERSONAL_INFO		=	41,
	ACUI_CTRID_PS_EXPAND			=	42,
	ACUI_CTRID_SKILL				=	43,
	ACUI_CTRID_SKILL_EXPAND			=	44,
	ACUI_CTRID_BANK					=	45,
	ACUI_CTRID_RECRUIT_WRITE		=	46,
	ACUI_CTRID_CHAT_WINDOW			=	47, 
	ACUI_CTRID_LOGIN_WINDOW			=	48,
	ACUI_CTRID_LOGIN_CHAR_SELECT	=	49, 
	ACUI_CTRID_LOGIN_CHAR_CREATE	=	50
};

#endif // !defined(AFX_ACUICONTROLHEADER_H__47C0CAA3_54B8_442C_96AA_C5B96FE97A62__INCLUDED_)
