#ifndef __AGCD_UI_CHARACTER_H__
#define __AGCD_UI_CHARACTER_H__

#include "AgpmCharacter.h"

#define AGCD_UI_CHAR_USRDAT_NAME_CUR_EXP		"현재 경험치"
#define AGCD_UI_CHAR_USRDAT_NAME_MAX_EXP		"현 레벨 최대 경험치"
#define AGCD_UI_CHAR_USRDAT_NAME_SELF_CHAR		"주인공 Character"
#define AGCD_UI_CHAR_USRDAT_NAME_TARGET_CHAR	"캐릭터 메뉴 대상 캐릭터"
#define	AGCD_UI_CHAR_USRDAT_NAME_MESSAGE_DATA	"캐릭터 메시지 데이타들"

//#define AGCD_UI_CHAR_USRDAT_NAME_CUR_EXP		"current exp"
//#define AGCD_UI_CHAR_USRDAT_NAME_MAX_EXP		"current level max exp"
//#define AGCD_UI_CHAR_USRDAT_NAME_SELF_CHAR		"main character"
//#define AGCD_UI_CHAR_USRDAT_NAME_TARGET_CHAR	"char menu target char"
//#define	AGCD_UI_CHAR_USRDAT_NAME_MESSAGE_DATA	"char msg data"

typedef enum
{
	E_AGCD_UI_CHAR_USRDAT_CUR_EXP	= 0,
	E_AGCD_UI_CHAR_USRDAT_MAX_EXP,
	E_AGCD_UI_CHAR_USRDAT_SELF_CHAR,
	E_AGCD_UI_CHAR_USRDAT_NUM
};

#define	AGCD_UI_CHAR_DISP_NAME_CHAR_NAME		"캐릭터 이름"
#define AGCD_UI_CHAR_DISP_NAME_CLASS_NAME		"클래스 이름"
#define AGCD_UI_CHAR_DISP_NAME_RACE_NAME		"레이스 이름"
#define AGCD_UI_CHAR_DISP_NAME_GENDER_NAME		"젠더 이름"
#define	AGCD_UI_CHAR_DISP_NAME_RACE_CLASS		"레이스,클레스 이름"
#define AGCD_UI_CHAR_DISP_NAME_CUR_LEVEL		"현재 레벨"
#define AGCD_UI_CHAR_DISP_NAME_CUR_EXP			"현재 경험치"
#define AGCD_UI_CHAR_DISP_NAME_MAX_EXP			"현 레벨 최대 경험치"
#define AGCD_UI_CHAR_DISP_NAME_EXP_PERCENT		"경험치(%)"
#define	AGCD_UI_CHAR_DISP_NAME_EXP_PERCENT2		"경험치(%)2"
#define	AGCD_UI_CHAR_DISP_NAME_EXP_BAR			"EXP_Bar"
#define AGCD_UI_CHAR_DISP_NAME_CON				"생명"
#define AGCD_UI_CHAR_DISP_NAME_WIS				"지혜"
#define AGCD_UI_CHAR_DISP_NAME_DEX				"민첩"
#define AGCD_UI_CHAR_DISP_NAME_STR				"힘"
#define AGCD_UI_CHAR_DISP_NAME_INT				"지식"
#define AGCD_UI_CHAR_DISP_NAME_CHA				"카리스마"
#define AGCD_UI_CHAR_DISP_NAME_HP				"HP"
#define AGCD_UI_CHAR_DISP_NAME_HP_MAX			"HP_Max"
#define AGCD_UI_CHAR_DISP_NAME_HP_ALL			"HP_All"
#define	AGCD_UI_CHAR_DISP_NAME_HP_BAR			"HP_Bar"
#define AGCD_UI_CHAR_DISP_NAME_MP				"MP"
#define AGCD_UI_CHAR_DISP_NAME_MP_MAX			"MP_Max"
#define AGCD_UI_CHAR_DISP_NAME_MP_ALL			"MP_All"
#define	AGCD_UI_CHAR_DISP_NAME_MP_PERCENT		"MP_Percent"
#define	AGCD_UI_CHAR_DISP_NAME_MP_BAR			"MP_Bar"
#define AGCD_UI_CHAR_DISP_NAME_SP				"SP"
#define AGCD_UI_CHAR_DISP_NAME_SP_MAX			"SP_Max"
#define AGCD_UI_CHAR_DISP_NAME_SP_ALL			"SP_All"
#define	AGCD_UI_CHAR_DISP_NAME_SP_PERCENT		"SP_Percent"
#define AGCD_UI_CHAR_DISP_NAME_DEFENSE_PHYSICAL	"물리 방어력"
#define AGCD_UI_CHAR_DISP_NAME_DEFENSE_MAGIC	"마법 방어력"
#define AGCD_UI_CHAR_DISP_NAME_DEFENSE_FIRE		"불 방어력"
#define AGCD_UI_CHAR_DISP_NAME_DEFENSE_WATER	"물 방어력"
#define AGCD_UI_CHAR_DISP_NAME_DEFENSE_AIR		"공기 방어력"
#define AGCD_UI_CHAR_DISP_NAME_DEFENSE_EARTH	"땅 방어력"
#define AGCD_UI_CHAR_DISP_NAME_DEFENSE_PARTY	"파티 방어력"
#define AGCD_UI_CHAR_DISP_NAME_DAMAGE_PHYSICAL_MIN	"물리 공격력 최소"
#define AGCD_UI_CHAR_DISP_NAME_DAMAGE_PHYSICAL_MAX	"물리 공격력 최대"
#define	AGCD_UI_CHAR_DISP_NAME_DAMAGE_PHYSICAL_ALL	"물리 공격력 모두"
#define AGCD_UI_CHAR_DISP_NAME_DAMAGE_MAGIC_MIN		"마법 공격력 최소"
#define AGCD_UI_CHAR_DISP_NAME_DAMAGE_MAGIC_MAX		"마법 공격력 최대"
#define AGCD_UI_CHAR_DISP_NAME_DAMAGE_MAGIC_ALL		"마법 공격력 모두"
#define AGCD_UI_CHAR_DISP_NAME_DAMAGE_FIRE_MIN		"불 공격력 최소"
#define AGCD_UI_CHAR_DISP_NAME_DAMAGE_FIRE_MAX		"불 공격력 최대"
#define AGCD_UI_CHAR_DISP_NAME_DAMAGE_FIRE_ALL		"불 공격력 모두"
#define AGCD_UI_CHAR_DISP_NAME_DAMAGE_WATER_MIN		"물 공격력 최소"
#define AGCD_UI_CHAR_DISP_NAME_DAMAGE_WATER_MAX		"물 공격력 최대"
#define AGCD_UI_CHAR_DISP_NAME_DAMAGE_WATER_ALL		"물 공격력 모두"
#define AGCD_UI_CHAR_DISP_NAME_DAMAGE_AIR_MIN		"공기 공격력 최소"
#define AGCD_UI_CHAR_DISP_NAME_DAMAGE_AIR_MAX		"공기 공격력 최대"
#define AGCD_UI_CHAR_DISP_NAME_DAMAGE_AIR_ALL		"공기 공격력 모두"
#define AGCD_UI_CHAR_DISP_NAME_DAMAGE_EARTH_MIN		"땅 공격력 최소"
#define AGCD_UI_CHAR_DISP_NAME_DAMAGE_EARTH_MAX		"땅 공격력 최대"
#define AGCD_UI_CHAR_DISP_NAME_DAMAGE_EARTH_ALL		"땅 공격력 모두"
#define AGCD_UI_CHAR_DISP_NAME_DAMAGE_PARTY		"파티 공격력"
#define AGCD_UI_CHAR_DISP_NAME_DAMAGE_BASIC_SKILL	"스킬 기본 공격력"

#define AGCD_UI_CHAR_DISP_NAME_TARGET_CHAR_NAME		"캐릭터메뉴 타겟 이름"
//#define AGCD_UI_CHAR_DISP_NAME_TARGET_CHAR_NAME		"charactermenu target name"

#define	AGCD_UI_CHAR_DISP_NAME_MESSAGE_DATA_LEVEL_UP	"레벨 변경값"
//#define	AGCD_UI_CHAR_DISP_NAME_MESSAGE_DATA_LEVEL_UP	"level change result"
#define	AGCD_UI_CHAR_DISP_NAME_MESSAGE_DATA_BONUS_EXP	"보너스 EXP"
//#define	AGCD_UI_CHAR_DISP_NAME_MESSAGE_DATA_BONUS_EXP	"Bonus EXP"
#define	AGCD_UI_CHAR_DISP_NAME_MESSAGE_DATA_BONUS_PCBANG_EXP	"보너스 EXP (PC방)"
//#define	AGCD_UI_CHAR_DISP_NAME_MESSAGE_DATA_BONUS_PCBANG_EXP	"Bonus EXP (PCBang)"

typedef enum
{
	E_AGCD_UI_CHAR_DISP_CHAR_NAME	= 1,
	E_AGCD_UI_CHAR_DISP_CLASS_NAME,
	E_AGCD_UI_CHAR_DISP_RACE_NAME,
	E_AGCD_UI_CHAR_DISP_GENDER_NAME,
	E_AGCD_UI_CHAR_DISP_RACE_CLASS,
	E_AGCD_UI_CHAR_DISP_CUR_LEVEL,
	E_AGCD_UI_CHAR_DISP_CUR_EXP,
	E_AGCD_UI_CHAR_DISP_MAX_EXP,
	E_AGCD_UI_CHAR_DISP_EXP_PERCENT,
	E_AGCD_UI_CHAR_DISP_EXP_PERCENT2,
	E_AGCD_UI_CHAR_DISP_EXP_BAR,
	E_AGCD_UI_CHAR_DISP_CON,
	E_AGCD_UI_CHAR_DISP_WIS,
	E_AGCD_UI_CHAR_DISP_DEX,
	E_AGCD_UI_CHAR_DISP_STR,
	E_AGCD_UI_CHAR_DISP_INT,
	E_AGCD_UI_CHAR_DISP_CHA,
	E_AGCD_UI_CHAR_DISP_HP,
	E_AGCD_UI_CHAR_DISP_HP_MAX,
	E_AGCD_UI_CHAR_DISP_HP_ALL,
	E_AGCD_UI_CHAR_DISP_HP_BAR,
	E_AGCD_UI_CHAR_DISP_MP,
	E_AGCD_UI_CHAR_DISP_MP_MAX,
	E_AGCD_UI_CHAR_DISP_MP_ALL,
	E_AGCD_UI_CHAR_DISP_MP_PERCENT,
	E_AGCD_UI_CHAR_DISP_MP_BAR,
	E_AGCD_UI_CHAR_DISP_SP,
	E_AGCD_UI_CHAR_DISP_SP_MAX,
	E_AGCD_UI_CHAR_DISP_SP_ALL,
	E_AGCD_UI_CHAR_DISP_SP_PERCENT,
	E_AGCD_UI_CHAR_DISP_AR,
	E_AGCD_UI_CHAR_DISP_DR,
	E_AGCD_UI_CHAR_DISP_MOVEFAST,
	E_AGCD_UI_CHAR_DISP_ATTACkSPEED,
	E_AGCD_UI_CHAR_DISP_DEFENSE_PHYSICAL,
	E_AGCD_UI_CHAR_DISP_DEFENSE_MAGIC,
	E_AGCD_UI_CHAR_DISP_DEFENSE_FIRE,
	E_AGCD_UI_CHAR_DISP_DEFENSE_WATER,
	E_AGCD_UI_CHAR_DISP_DEFENSE_AIR,
	E_AGCD_UI_CHAR_DISP_DEFENSE_EARTH,
	E_AGCD_UI_CHAR_DISP_DEFENSE_PARTY,
	E_AGCD_UI_CHAR_DISP_DAMAGE_PHYSICAL_MIN,
	E_AGCD_UI_CHAR_DISP_DAMAGE_PHYSICAL_MAX,
	E_AGCD_UI_CHAR_DISP_DAMAGE_PHYSICAL_ALL,
	E_AGCD_UI_CHAR_DISP_DAMAGE_MAGIC_MIN,
	E_AGCD_UI_CHAR_DISP_DAMAGE_MAGIC_MAX,
	E_AGCD_UI_CHAR_DISP_DAMAGE_MAGIC_ALL,
	E_AGCD_UI_CHAR_DISP_DAMAGE_FIRE_MIN,
	E_AGCD_UI_CHAR_DISP_DAMAGE_FIRE_MAX,
	E_AGCD_UI_CHAR_DISP_DAMAGE_FIRE_ALL,
	E_AGCD_UI_CHAR_DISP_DAMAGE_WATER_MIN,
	E_AGCD_UI_CHAR_DISP_DAMAGE_WATER_MAX,
	E_AGCD_UI_CHAR_DISP_DAMAGE_WATER_ALL,
	E_AGCD_UI_CHAR_DISP_DAMAGE_AIR_MIN,
	E_AGCD_UI_CHAR_DISP_DAMAGE_AIR_MAX,
	E_AGCD_UI_CHAR_DISP_DAMAGE_AIR_ALL,
	E_AGCD_UI_CHAR_DISP_DAMAGE_EARTH_MIN,
	E_AGCD_UI_CHAR_DISP_DAMAGE_EARTH_MAX,
	E_AGCD_UI_CHAR_DISP_DAMAGE_EARTH_ALL,
	E_AGCD_UI_CHAR_DISP_DAMAGE_PARTY,
	E_AGCD_UI_CHAR_DISP_DAMAGE_BASIC_SKILL,

	E_AGCD_UI_CHAR_DISP_TARGET_CHAR_NAME,

	E_AGCD_UI_CHAR_DISP_MESSAGE_DATA_LEVEL_UP,
	E_AGCD_UI_CHAR_DISP_MESSAGE_DATA_BONUS_EXP,
	E_AGCD_UI_CHAR_DISP_MESSAGE_DATA_BONUS_PCBANG_EXP,
	E_AGCD_UI_CHAR_DISP_NUM
};

typedef enum {
	AGCD_UI_CHAR_EDIT_CON			= 0,
	AGCD_UI_CHAR_EDIT_WIS,
	AGCD_UI_CHAR_EDIT_DEX,
	AGCD_UI_CHAR_EDIT_STR,
	AGCD_UI_CHAR_EDIT_INT,
	AGCD_UI_CHAR_EDIT_CHAR,

	AGCD_UI_CHAR_EDIT_NORMAL_ATTACK,				// 물리공격력
	AGCD_UI_CHAR_EDIT_DEFENSE,						// 물리방어력
	AGCD_UI_CHAR_EDIT_SKILL_BLOCK,					// 스킬블럭률
	AGCD_UI_CHAR_EDIT_PHYSICAL_RES,					// 물리저항력
	AGCD_UI_CHAR_EDIT_AR,							// 공격률
	AGCD_UI_CHAR_EDIT_ADDITIONAL_AR,				// 추가명중률
	AGCD_UI_CHAR_EDIT_BLOCK,						// 방어율
	AGCD_UI_CHAR_EDIT_ADDITIONAL_EVADE,				// 추가회피율
	AGCD_UI_CHAR_EDIT_ATTACK_SPEED,					// 공격속도
	AGCD_UI_CHAR_EDIT_MOVEMENT,						// 이동속도
	AGCD_UI_CHAR_EDIT_BLOCK_RATE,					// 블럭률 (방패)
	AGCD_UI_CHAR_EDIT_IGNORE_TARGET_PHYSICAL,		// 물리방어무시
	AGCD_UI_CHAR_EDIT_IGNORE_TARGET_REGIST,			// 속성저항무시
	AGCD_UI_CHAR_EDIT_DECREASE_ENEMY_CRITICAL_RATE,	// 크리티컬감소
	AGCD_UI_CHAR_EDIT_REGIST_STUN,					// 스턴저항력
	AGCD_UI_CHAR_EDIT_RANGE,						// 사정거리
	//AGCD_UI_CHAR_EDIT_SKILL_ATTACK,

	AGCD_UI_CHAR_EDIT_DAMAGE_MAGIC,
	AGCD_UI_CHAR_EDIT_DAMAGE_FIRE,
	AGCD_UI_CHAR_EDIT_DAMAGE_AIR,
	AGCD_UI_CHAR_EDIT_DAMAGE_WATER,
	AGCD_UI_CHAR_EDIT_DAMAGE_EARTH,

	AGCD_UI_CHAR_EDIT_DEFENSE_MAGIC,
	AGCD_UI_CHAR_EDIT_DEFENSE_FIRE,
	AGCD_UI_CHAR_EDIT_DEFENSE_AIR,
	AGCD_UI_CHAR_EDIT_DEFENSE_WATER,
	AGCD_UI_CHAR_EDIT_DEFENSE_EARTH,

	AGCD_UI_CHAR_EDIT_CRIMINAL_TIME,
	AGCD_UI_CHAR_EDIT_MURDERER_POINT,
	AGCD_UI_CHAR_EDIT_MURDERER_TIME,
	AGCD_UI_CHAR_EDIT_MURDERER_LEVEL,

	AGCD_UI_CHAR_EDIT_MAX
};

typedef struct
{
	INT32	m_lMinimapIndex;
} AgcdUICharacterADBase;

typedef struct AgcdUICharacterLevelupMessage
{
	CHAR *				m_szMessage1;
	CHAR *				m_szMessage2;
	DWORD				m_dwColor1;
	DWORD				m_dwColor2;

	AgcdUICharacterLevelupMessage()
	{
		m_szMessage1 = NULL;
		m_dwColor1 = -1;
		m_szMessage2 = NULL;
		m_dwColor2 = -1;
	}
} AgcdUICharacterLevelupMessage;

typedef struct
{
	AgcdUICharacterLevelupMessage *	m_pstLevelUpMessage;
} AgcdUICharacterADCharacterTemplate;

#endif // __AGCD_UI_CHARACTER_H__