#ifndef	__AGCMUIITEM_H__
#define	__AGCMUIITEM_H__

#include "ApDefine.h"

const int		AGCMUIITEM_MAX_TOOLTIP					= 60;
const int		AGCMUIITEM_MAX_TOOLTIP_TEXT_LENGTH		= 384;
const int		AGCMUIITEM_MAX_SHOW_TOOLTIP				= 24;

typedef enum	AgcdUIItem_Tooltip_Type {
	AGCDUIITEM_TOOLTIP_INDEX_WEAPON						= 0,
	AGCDUIITEM_TOOLTIP_INDEX_SHIELD,
	AGCDUIITEM_TOOLTIP_INDEX_ARMOUR,
	AGCDUIITEM_TOOLTIP_INDEX_RING,
	AGCDUIITEM_TOOLTIP_INDEX_AMULET,
	AGCDUIITEM_TOOLTIP_INDEX_POTION,
	AGCDUIITEM_TOOLTIP_INDEX_SPIRITSTONE,
	AGCDUIITEM_TOOLTIP_INDEX_TELEPORTSCROLL,
	AGCDUIITEM_TOOLTIP_INDEX_ARROW,
	AGCDUIITEM_TOOLTIP_INDEX_BOLT,
	AGCDUIITEM_TOOLTIP_INDEX_TRANSFORMPOTION,
	AGCDUIITEM_TOOLTIP_INDEX_CATALYST,
	AGCDUIITEM_TOOLTIP_INDEX_RUNE,
	AGCDUIITEM_TOOLTIP_INDEX_RECEIPT,
	AGCDUIITEM_TOOLTIP_INDEX_SKILLBOOK,
	AGCDUIITEM_TOOLTIP_INDEX_SKILLSCROLL,
	AGCDUIITEM_TOOLTIP_INDEX_ETC,
	AGCDUIITEM_TOOLTIP_INDEX_RIDE,
	AGCDUIITEM_TOOLTIP_INDEX_LANCER,
	AGCDUIITEM_TOOLTIP_INDEX_MOVESPEED,
	AGCDUIITEM_TOOLTIP_INDEX_AVATAR,
	AGCDUIITEM_TOOLTIP_INDEX_MAX
} AgcdUIItem_Tooltip_Type;

#define	AGCDUIITEM_TOOLTIP_NAME_WEAPON					"무기"
#define	AGCDUIITEM_TOOLTIP_NAME_SHIELD					"방패"
#define	AGCDUIITEM_TOOLTIP_NAME_ARMOUR					"방어구"
#define	AGCDUIITEM_TOOLTIP_NAME_RING					"반지"
#define	AGCDUIITEM_TOOLTIP_NAME_AMULET					"목걸이"
#define	AGCDUIITEM_TOOLTIP_NAME_POTION					"물약"
#define	AGCDUIITEM_TOOLTIP_NAME_SPIRITSTONE				"정령석"
#define	AGCDUIITEM_TOOLTIP_NAME_TELEPORTSCROLL			"이동문서"
#define	AGCDUIITEM_TOOLTIP_NAME_ARROW					"화살"
#define	AGCDUIITEM_TOOLTIP_NAME_BOLT					"볼트"
#define	AGCDUIITEM_TOOLTIP_NAME_TRANSFORMPOTION			"변신물약"
#define	AGCDUIITEM_TOOLTIP_NAME_CATALYST				"강화축성제"
#define	AGCDUIITEM_TOOLTIP_NAME_RUNE					"기원석"
#define	AGCDUIITEM_TOOLTIP_NAME_RECEIPT					"변신물약레시피"
#define	AGCDUIITEM_TOOLTIP_NAME_SKILLBOOK				"스킬북"
#define	AGCDUIITEM_TOOLTIP_NAME_SKILLSCROLL				"스킬스크롤"
#define	AGCDUIITEM_TOOLTIP_NAME_ETC						"잡템(가죽)"

#define	AGCDUIITEM_TOOLTIP_NAME_RIDE					"탈것"
#define	AGCDUIITEM_TOOLTIP_NAME_LANCER					"마상무기"
#define AGCDUIITEM_TOOLTOP_NAME_AVATAR					"아바타"

//	그냥 내용이 아니고 뭔가 데이타를 같이 출력해 줘야 하는 넘들을 여기 정의한다.
#define	AGCDUIITEM_TOOLTIP_NAME_NEW_LINE				"줄바꿈"
#define	AGCDUIITEM_TOOLTIP_NAME_NAME					"이름"
#define	AGCDUIITEM_TOOLTIP_NAME_SECOND_CATEGORY			"2차카테고리"
#define	AGCDUIITEM_TOOLTIP_NAME_PRICE					"판매가격"
#define	AGCDUIITEM_TOOLTIP_NAME_TYPE					"아이템 타입"
#define	AGCDUIITEM_TOOLTIP_NAME_ITEM_RANK				"강화가능 등급"
#define	AGCDUIITEM_TOOLTIP_NAME_ATTACK_RANGE			"공격거리"
#define	AGCDUIITEM_TOOLTIP_NAME_DAMAGE					"물리공격력"
#define	AGCDUIITEM_TOOLTIP_NAME_ATTACK_SPEED			"공격 속도"
#define	AGCDUIITEM_TOOLTIP_NAME_DEFENSE					"물리방어력"
#define	AGCDUIITEM_TOOLTIP_NAME_BLOCK					"블럭률"
#define	AGCDUIITEM_TOOLTIP_NAME_DURABILITY				"내구도"
#define	AGCDUIITEM_TOOLTIP_NAME_RESTORE_HP				"생명 회복"
#define	AGCDUIITEM_TOOLTIP_NAME_RESTORE_MP				"마나 회복"
#define	AGCDUIITEM_TOOLTIP_NAME_REDUCE_POISON			"독 효과를 감소시킴"
#define	AGCDUIITEM_TOOLTIP_NAME_PHYSICAL_AR				"공격률"
#define	AGCDUIITEM_TOOLTIP_NAME_MAGICAL_AR				"마법공격 명중률"
#define	AGCDUIITEM_TOOLTIP_NAME_PHYSICAL_DR				"방어율"

#define	AGCDUIITEM_TOOLTIP_NAME_HEROIC_DAMAGE			"히로익공격력"
#define	AGCDUIITEM_TOOLTIP_NAME_HEROIC_DEFENSE			"히로익방어력"

#define	AGCDUIITEM_TOOLTIP_NAME_DURATION				"지속시간"
#define	AGCDUIITEM_TOOLTIP_NAME_RESTRICT_LEVEL			"착용 레벨"
#define	AGCDUIITEM_TOOLTIP_NAME_RESTRICT_RACE			"착용 종족"
#define	AGCDUIITEM_TOOLTIP_NAME_RESTRICT_CLASS			"착용 클래스"
#define	AGCDUIITEM_TOOLTIP_NAME_USE_LEVEL				"사용 레벨"
#define	AGCDUIITEM_TOOLTIP_NAME_USE_RACE				"사용 종족"
#define	AGCDUIITEM_TOOLTIP_NAME_ITEM_CONVERT			"개조 내용"

#define	AGCDUIITEM_TOOLTIP_NAME_SPIRIT_STONE_INFO		"정령석정보"
#define	AGCDUIITEM_TOOLTIP_NAME_RING_INFO				"반지속성정보"
#define	AGCDUIITEM_TOOLTIP_NAME_AMULET_INFO				"목걸이속성정보"

//#define	AGCDUIITEM_TOOLTIP_NAME_SS_DAMAGE_FIRE			"무기: 추가 불 공격력"
//#define	AGCDUIITEM_TOOLTIP_NAME_SS_DAMAGE_WATER			"무기: 추가 물 공격력"
//#define	AGCDUIITEM_TOOLTIP_NAME_SS_DAMAGE_AIR			"무기: 추가 공기 공격력"
//#define	AGCDUIITEM_TOOLTIP_NAME_SS_DAMAGE_EARTH			"무기: 추가 땅 공격력"
//#define	AGCDUIITEM_TOOLTIP_NAME_SS_DAMAGE_MAGIC			"무기: 추가 마법 공격력"
//#define	AGCDUIITEM_TOOLTIP_NAME_SS_DAMAGE_POISON		"무기: 추가 독 공격력, 생명 지속 손실"
//#define	AGCDUIITEM_TOOLTIP_NAME_SS_DAMAGE_LIGHTENING	"무기: 추가 번개 공격, 마비"
//#define	AGCDUIITEM_TOOLTIP_NAME_SS_DAMAGE_ICE			"무기: 추가 얼음 공격, 속도감소"

//#define	AGCDUIITEM_TOOLTIP_NAME_SS_DEFENSE_FIRE			"방어구: 추가 불 방어력"
//#define	AGCDUIITEM_TOOLTIP_NAME_SS_DEFENSE_WATER		"방어구: 추가 물 방어력"
//#define	AGCDUIITEM_TOOLTIP_NAME_SS_DEFENSE_AIR			"방어구: 추가 공기 방어력"
//#define	AGCDUIITEM_TOOLTIP_NAME_SS_DEFENSE_EARTH		"방어구: 추가 땅 방어력"
//#define	AGCDUIITEM_TOOLTIP_NAME_SS_DEFENSE_MAGIC		"방어구: 추가 마법 방어력"
//#define	AGCDUIITEM_TOOLTIP_NAME_SS_DEFENSE_STR			"방어구: 추가 힘"
//#define	AGCDUIITEM_TOOLTIP_NAME_SS_DEFENSE_CON			"방어구: 추가 체력"
//#define	AGCDUIITEM_TOOLTIP_NAME_SS_DEFENSE_INT			"방어구: 추가 지식"
//#define	AGCDUIITEM_TOOLTIP_NAME_SS_DEFENSE_WIS			"방어구: 추가 지혜"
//#define	AGCDUIITEM_TOOLTIP_NAME_SS_DEFENSE_DEX			"방어구: 추가 민첩"

//#define	AGCDUIITEM_TOOLTIP_NAME_DEFENSE_FIRE			"불 방어"
//#define	AGCDUIITEM_TOOLTIP_NAME_DEFENSE_WATER			"물 방어"
//#define	AGCDUIITEM_TOOLTIP_NAME_DEFENSE_AIR				"공기 방어"
//#define	AGCDUIITEM_TOOLTIP_NAME_DEFENSE_EARTH			"땅 방어"
//#define	AGCDUIITEM_TOOLTIP_NAME_DEFENSE_MAGIC			"마법 방어"

//#define	AGCDUIITEM_TOOLTIP_NAME_STR						"힘"
//#define	AGCDUIITEM_TOOLTIP_NAME_CON						"체력"
//#define	AGCDUIITEM_TOOLTIP_NAME_INT						"지식"
//#define	AGCDUIITEM_TOOLTIP_NAME_WIS						"지혜"
//#define	AGCDUIITEM_TOOLTIP_NAME_DEX						"민첩"

#define	AGCDUIITEM_TOOLTIP_NAME_USE_RUNE_LEVEL			"장착 레벨"
#define	AGCDUIITEM_TOOLTIP_NAME_MAX_HP					"최대 생명"
#define	AGCDUIITEM_TOOLTIP_NAME_MAX_MP					"최대 마나"
#define	AGCDUIITEM_TOOLTIP_NAME_ADD_DAMAGE				"추가 물리공격력"
#define	AGCDUIITEM_TOOLTIP_NAME_ADD_DEFENSE				"추가 물리방어력"
#define	AGCDUIITEM_TOOLTIP_NAME_REPAIR_COST				"수리비"
#define	AGCDUIITEM_TOOLTIP_NAME_MOVE_SPEED				"이동속도"

#define	AGCDUIITEM_TOOLTIP_NAME_RUNE_USE_WEAPON			"무기에 사용"
#define	AGCDUIITEM_TOOLTIP_NAME_RUNE_USE_ARMOUR			"갑옷에 사용"
#define	AGCDUIITEM_TOOLTIP_NAME_RUNE_USE_SHIELD			"방패에 사용"
#define	AGCDUIITEM_TOOLTIP_NAME_RUNE_USE_RING			"반지에 사용"
#define	AGCDUIITEM_TOOLTIP_NAME_RUNE_USE_AMULET			"목걸이에 사용"

#define AGCDUIITEM_TOOLTIP_NAME_BOW_SERIES	"활 계열용"
#define AGCDUIITEM_TOOLTIP_NAME_CROSSBOW_SERIES		"석궁 계열용"
#define AGCDUIITEM_TOOLTIP_NAME_DRAG_BUILDUP_ITEM		"아이템위로 드래그해서 강화 가능"
#define AGCDUIITEM_TOOLTIP_NAME_SMITH_BUILDUP_ITEM		"대장장이를 통해 강화 가능"

class AgcdUIItemTooltip {
public:
	INT16		m_alTooltipIndex[AGCMUIITEM_MAX_SHOW_TOOLTIP];
	INT16		m_nNumTooltip;
};

class AgcdUIItemTooltipDesc {
public:
	CHAR		m_szDescription[AGCMUIITEM_MAX_TOOLTIP_TEXT_LENGTH + 1];
};

#endif	//__AGCMUIITEM_H__