#ifndef _AGCD_UI_SYSTEM_MESSAGE_H_
#define _AGCD_UI_SYSTEM_MESSAGE_H_

// UI Messages
#define UI_MESSAGE_LOTTERYBOX_CONVERION_DONE		"LOTTERYBOX_CONVERSION_DONE"
#define UI_MESSAGE_LOTTERY_KEY_NOT_USABLE			"LOTTERY_KEY_NOT_USABLE"
#define UI_MESSAGE_LOTTERYBOX_NEEDS_GOLD_KEY		"LOTTERYBOX_NEEDS_GOLD_KEY"
#define UI_MESSAGE_LOTTERYBOX_NEEDS_SILVER_KEY		"LOTTERYBOX_NEEDS_SILVER_KEY"
#define UI_MESSAGE_LOTTERYBOX_NEEDS_BRONZE_KEY		"LOTTERYBOX_NEEDS_BRONZE_KEY"
#define UI_MESSAGE_LOTTERYBOX_NEEDS_PLATINUM_KEY	"LOTTERYBOX_NEEDS_PLATINUM_KEY"

#define UI_MESSAGE_CASH_ITEM_STOP_USING_ITEM			"CASH_ITEM_STOP_USING_ITEM"				// %s 아이템이 사용 중지 되었습니다.
#define UI_MESSAGE_CASH_ITEM_END_USING_ITEM				"CASH_ITEM_END_USING_ITEM"				// %s 아이템이 사용 중지 되었습니다.
#define UI_MESSAGE_CASH_ITEM_CANNOT_UNUSE_ITEM			"CASH_ITEM_CANNOT_UNUSE_ITEM"			// 캐쉬 아이템은 사용 중지가 불가능합니다.
#define UI_MESSAGE_CASH_ITEM_SAME_KIND_ALREADY_IN_USE	"CASH_ITEM_SAME_KIND_ALREADY_IN_USE"	// 같은 기능의 아이템이 이미 사용중입니다.
#define UI_MESSAGE_CASH_ITEM_PAUSE_ITEM					"CASH_ITEM_PAUSE_ITEM"					// %s 아이템이 일시 정지 되었습니다.
#define UI_MESSAGE_CASH_ITEM_CANNOT_UNUSE_STATUS		"CASH_ITEM_CANNOT_UNUSE_STATUS"			// 캐쉬 아이템을 사용 중지 할 수 없는 상태입니다.

#define UI_MESSAGE_TAME_FAILURE_MAX_COUNT			"TameFailureMaxCount"
#define UI_MESSAGE_TAME_FAILURE_INVALID_TARGET		"TameFailureInvalidTarget"
#define UI_MESSAGE_TAME_FAILURE_ALREADY_TAMING		"TameFailureAlreadyTaming"
#define UI_MESSAGE_TAME_FAILURE_MISS				"TameFailureMiss"
#define UI_MESSAGE_FIXED_FAILURE_MAX_COUNT			"FixedFailureMaxCount"
#define UI_MESSAGE_SUMMONS_FAILURE_MAX_COUNT		"SummonsFailureMaxCount"

#define UI_MESSAGE_TRANSPARENT_FAILURE_FOR_COMBAT	"TransparentFailureForCombat"

#define UI_MESSAGE_MUTATION_FAILURE_INVALID_TARGET	"MutationFailureInvalidTarget"

#define UI_MESSAGE_ITEM_CANNOT_BUY					"ItemCannotBuy"
#define UI_MESSAGE_ITEM_FOR_GUILDMASTER				"ItemForGuildMaster"

#define UI_MESSAGE_CANNOT_USE_BY_STATUS				"CannotUseByStatus"
#define UI_MESSAGE_CANNOT_USE_BY_REUSE_INTERVAL		"CannotUseByReuseInterval"
#define UI_MESSAGE_JUMP_ITEM_USED					"JumpItemUsed"

#define UI_MESSAGE_CANNOT_RIDE_WHILE_COMBAT			"CannotRideWhileCombat"
#define UI_MESSAGE_CANNOT_ATTACKABLE_TARGET			"CannotAttackableTarget"

#define UI_MESSAGE_SKILL_INITIALIZE_NO_OWN_SKILL	"SkillInitNoOwnSkill"
#define UI_MESSAGE_SKILL_INITIALIZE_CONFIRM			"SkillInitConfirm"

#define UI_MESSAGE_PARTY_PORTAL_ERROR_DEAD_MEMBER		"PartyPortalError_DeadMember"
#define UI_MESSAGE_PARTY_PORTAL_ERROR_IN_SECRET_DUNGEON	"PartyPortalError_InSecretDungeon"
#define UI_MESSAGE_PARTY_PORTAL_ERROR_IN_SIEGE_WAR		"PartyPortalError_InSiegeWar"
#define UI_MESSAGE_PARTY_PORTAL_ERROR_LACK_OF_LEVEL		"PartyPortalError_LackOfLevel"

#define UI_MESSAGE_GO_COMMAND_LACK_OF_LEVEL				"GoCommand_LackOfLevel"
#define UI_MESSAGE_CANNOT_USE_WANGBOK_SCROLL			"CannotUseWangbokScroll"

#endif // _AGCD_UI_SYSTEM_MESSAGE_H_