#pragma once

#define PATCHCLIENT_OPTION_FILENAME	".\\Ini\\COption.ini"

#define PATCHCLIENT_OPTION_HIGH		" /Oqh"
#define PATCHCLIENT_OPTION_LOW		" /Oql"
#define PATCHCLIENT_OPTION_NOSAVE	" /Ons"
#define PATCHCLIENT_LOGIN_SERVER	" /L"

//. 2006. 4. 20. nonstopdj
#define PATCHCLIENT_OPTION_FORCEEXIT " /Exit"


typedef enum
{
	AGCM_OPTION_STARTUP_NORMAL = 0,
	AGCM_OPTION_STARTUP_LOW,
	AGCM_OPTION_STARTUP_HIGH
} AgcmOptionStartup;

typedef enum
{
	AGCD_OPTION_TEXTURE_HIGH = 0,
	AGCD_OPTION_TEXTURE_MEDIUM,
	AGCD_OPTION_TEXTURE_LOW,
} AgcdUIOptionTexture;

typedef enum
{
	AGCD_OPTION_TYPE_VIEW	= 0,
	AGCD_OPTION_TYPE_TOGGLE,
	AGCD_OPTION_TYPE_NATURE,
	AGCD_OPTION_TYPE_EFFECT,
	AGCD_OPTION_TYPE_EFFECT2,
	AGCD_OPTION_MAX_TYPE
} AgcdUIOptionType;

typedef enum
{
	AGCD_OPTION_VIEW_NONE	= -1,
	AGCD_OPTION_VIEW_NEAR,
	AGCD_OPTION_VIEW_NORMAL,
	AGCD_OPTION_VIEW_FAR,
	AGCD_OPTION_VIEW_ALL,
	AGCD_OPTION_MAX_VIEW
} AgcdUIOptionView;

typedef enum
{
	AGCD_OPTION_TOGGLE_NONE	= -1,
	AGCD_OPTION_TOGGLE_OFF,
	AGCD_OPTION_TOGGLE_ON,
	AGCD_OPTION_MAX_TOGGLE
} AgcdUIOptionToggle;

typedef enum
{
	AGCD_OPTION_NATURE_NONE	= -1,
	AGCD_OPTION_NATURE_LOW,
	AGCD_OPTION_NATURE_MEDIUM,
	AGCD_OPTION_NATURE_HIGH,
	AGCD_OPTION_MAX_NATURE
} AgcdUIOptionNature;

typedef enum
{
	AGCD_OPTION_EFFECT_NONE	= -1,
	AGCD_OPTION_EFFECT_OFF,
	AGCD_OPTION_EFFECT_LOW,
	AGCD_OPTION_EFFECT_MEDIUM,
	AGCD_OPTION_EFFECT_HIGH,
	AGCD_OPTION_MAX_EFFECT
} AgcdUIOptionEffect;

typedef enum
{
	AGCD_OPTION_EFFECT2_NONE = -1,
	AGCD_OPTION_EFFECT2_OFF,
	AGCD_OPTION_EFFECT2_TYPE1,
	AGCD_OPTION_EFFECT2_TYPE2,
	AGCD_OPTION_EFFECT2_TYPE3,
	AGCD_OPTION_EFFECT2_TYPE4,
	AGCD_OPTION_MAX_EFFECT2
} AgcdUIOptionEffect2;
