#ifndef	__AGPDCHARACTERIMPORTDATA_H__
#define __AGPDCHARACTERIMPORTDATA_H__

#include "ApDefine.h"

#define AGPMCHAR_IMPORT_CHAR_TYPE						"Type"
#define AGPMCHAR_IMPORT_CHAR_RACE						"Race"
#define AGPMCHAR_IMPORT_CHAR_GENDER						"Gender"
#define AGPMCHAR_IMPORT_CHAR_CLASS						"Class"
#define AGPMCHAR_IMPORT_CHAR_LEVEL						"LVL"
#define AGPMCHAR_IMPORT_CHAR_STR						"STR"
#define AGPMCHAR_IMPORT_CHAR_DEX						"DEX"
#define AGPMCHAR_IMPORT_CHAR_INT						"INT"
#define AGPMCHAR_IMPORT_CHAR_WIS						"Wis"
#define AGPMCHAR_IMPORT_CHAR_CON						"CON"
#define AGPMCHAR_IMPORT_CHAR_CHA						"CHA"
#define AGPMCHAR_IMPORT_CHAR_AC							"AC"
#define AGPMCHAR_IMPORT_CHAR_HP_MAX						"MAX_HP"
#define AGPMCHAR_IMPORT_CHAR_SP_MAX						"MAX_SP"
#define AGPMCHAR_IMPORT_CHAR_MP_MAX						"MAX_MP"
#define AGPMCHAR_IMPORT_CHAR_MOVEMENT_WALK				"Movement Walk"
#define AGPMCHAR_IMPORT_CHAR_MOVEMENT_RUN				"Movement Run"
#define AGPMCHAR_IMPORT_CHAR_MIN_DMG					"Min_Damage"
#define AGPMCHAR_IMPORT_CHAR_MAX_DMG					"Max_Damage"
#define AGPMCHAR_IMPORT_CHAR_ATTACK_RANGE				"Range"
#define AGPMCHAR_IMPORT_CHAR_DEFENSE_RATE				"DEFENSE RATE"
#define AGPMCHAR_IMPORT_CHAR_ATK_SPEED					"ATK Speed"
//#define AGPMCHAR_IMPORT_CHAR_ATK_POINT					"ATK point"
//#define AGPMCHAR_IMPORT_CHAR_MAGIC_ATK_POINT			"Magic ATK"
#define AGPMCHAR_IMPORT_CHAR_AR							"AR"
#define AGPMCHAR_IMPORT_CHAR_DR							"DR"
#define AGPMCHAR_IMPORT_CHAR_MAR						"MAR"
#define AGPMCHAR_IMPORT_CHAR_MDR						"MDR"
#define AGPMCHAR_IMPROT_CHAR_EXP						"Exp"
#define AGPMCHAR_IMPORT_CHAR_MAGIC_INTENSITY			"MAGIC INTENSITY"
#define AGPMCHAR_IMPORT_CHAR_LAND_ATTACH_TYPE			"LandAttachType"
/*
#define AGPMCHAR_IMPORT_CHAR_FIRE_DMG					"FIRE DMG"
#define AGPMCHAR_IMPORT_CHAR_WATER_DMG					"WATER DMG"
#define AGPMCHAR_IMPORT_CHAR_AIR_DMG					"AIR DMG"
#define AGPMCHAR_IMPORT_CHAR_EARTH_DMG					"EARTH DMG"
#define AGPMCHAR_IMPORT_CHAR_MAGIC_DMG					"MAGIC DMG"
*/
#define	AGPMCHAR_IMPORT_CHAR_FIRE_MIN_DMG				"Fire Min_Damage"
#define	AGPMCHAR_IMPORT_CHAR_WATER_MIN_DMG				"Water Min_Damage"
#define	AGPMCHAR_IMPORT_CHAR_AIR_MIN_DMG				"Air Min_Damage"
#define	AGPMCHAR_IMPORT_CHAR_EARTH_MIN_DMG				"Earth Min_Damage"
#define	AGPMCHAR_IMPORT_CHAR_MAGIC_MIN_DMG				"Magic Min_Damage"
#define	AGPMCHAR_IMPORT_CHAR_POISON_MIN_DMG				"Poison Min_Damage"
#define	AGPMCHAR_IMPORT_CHAR_ICE_MIN_DMG				"Ice Min_Damage"
#define	AGPMCHAR_IMPORT_CHAR_THUNDER_MIN_DMG			"Thunder Min_Damage"
#define	AGPMCHAR_IMPORT_CHAR_FIRE_MAX_DMG				"Fire Max_Damage"
#define	AGPMCHAR_IMPORT_CHAR_WATER_MAX_DMG				"Water Max_Damage"
#define	AGPMCHAR_IMPORT_CHAR_AIR_MAX_DMG				"Air Max_Damage"
#define	AGPMCHAR_IMPORT_CHAR_EARTH_MAX_DMG				"Earth Max_Damage"
#define	AGPMCHAR_IMPORT_CHAR_MAGIC_MAX_DMG				"Magic Max_Damage"
#define	AGPMCHAR_IMPORT_CHAR_POISON_MAX_DMG				"Poison Max_Damage"
#define	AGPMCHAR_IMPORT_CHAR_ICE_MAX_DMG				"Ice Max_Damage"
#define	AGPMCHAR_IMPORT_CHAR_THUNDER_MAX_DMG			"Thunder Max_Damage"

#define AGPMCHAR_IMPORT_CHAR_PHYSICAL_RES				"Physical_Resistance"
#define AGPMCHAR_IMPORT_CHAR_FIRE_RES					"Fire Res."
#define AGPMCHAR_IMPORT_CHAR_WATER_RES					"Water Res."
#define AGPMCHAR_IMPORT_CHAR_AIR_RES					"Air Res."
#define AGPMCHAR_IMPORT_CHAR_EARTH_RES					"Earth Res."
#define AGPMCHAR_IMPORT_CHAR_MAGIC_RES					"Magic Res."
#define AGPMCHAR_IMPORT_CHAR_POISON_RES					"Poison Res."
#define AGPMCHAR_IMPORT_CHAR_ICE_RES					"Ice Res."
#define AGPMCHAR_IMPORT_CHAR_THUNDER_RES				"Thunder Res."

#define	AGPMCHAR_IMPORT_CHAR_SKILL_BLOCK				"Skill_Block"

#define AGPMCHAR_IMPORT_CHAR_GHELLD_MIN					"Geld_Min"
#define AGPMCHAR_IMPORT_CHAR_GHELLD_MAX					"Geld_Max"
#define AGPMCHAR_IMPORT_CHAR_DROP_TID					"Drop_TID"

#define AGPMCHAR_IMPORT_CHAR_SLOW_PERCENT				"slow_percent"
#define AGPMCHAR_IMPORT_CHAR_SLOW_TIME					"slow_time"
#define AGPMCHAR_IMPORT_CHAR_FAST_PERCENT				"fast_percent"
#define AGPMCHAR_IMPORT_CHAR_FAST_TIME					"fast_time"

#define	AGPMCHAR_IMPORT_CHAR_ATTRIBUTE_TYPE				"attribute_type"

#define	AGPMCHAR_IMPORT_CHAR_ID_COLOR					"name_color"

#define AGPMCHAR_IMPORT_CHAR_TAMABLE					"Tamable"		// 2005.10.04. steeple.

#define AGPMCHAR_IMPORT_CHAR_RANGE_TYPE					"RangeType"		// 2007.12.05. steeple.

#define AGPMCHAR_IMPORT_CHAR_STAMINA_POINT				"StaminaPoint"	// 2008.06.19. steeple.
#define AGPMCHAR_IMPORT_CHAR_PET_TYPE					"PetType"		// 2008.06.23. steeple.
#define AGPMCHAR_IMPORT_CHAR_START_STAMINA_POINT		"StartStamina"	// 2008.07.08. steeple.

#define AGPMCHAR_IMPORT_CHAR_HEROIC_MIN_DAMAGE			"Heroic_Min_Damage"
#define AGPMCHAR_IMPORT_CHAR_HEROIC_MAX_DAMAGE			"Heroic_Max_Damage"
#define AGPMCHAR_IMPORT_CHAR_HEROIC_DEFENSE_POINT		"Heroic_Defense_Point"
#define AGPMCHAR_IMPORT_CHAR_HEROIC_MELEE_RESISTANCE	"Heroic_Melee_Resistance"
#define AGPMCHAR_IMPORT_CHAR_HEROIC_RANGED_RESISTANCE	"Heroic_Ranged_Resistance"
#define AGPMCHAR_IMPORT_CHAR_HEROIC_MAGIC_RESISTANCE	"Heroic_Magic_Resistance"


#endif	//__AGPDCHARACTERIMPORTDATA_H__