#ifndef	__AGPDSKILLIMPORTDATA_H__
#define	__AGPDSKILLIMPORTDATA_H__

#define AGPMITEM_IMPORT_CHAR_PRODUCT_SKIN		"Product_Skin"
#define AGPMITEM_IMPORT_CHAR_PRODUCT_MEAT		"Product_Meat"

#endif	//__AGPDSKILLIMPORTDATA_H__

