#if !defined(__AGPDTITLETEMPLATE_H__)
#define __AGPDTITLETEMPLATE_H__

#include "ApBase.h"

#include <vector>

const INT32 AGPDTITLE_MAX_TITLE_CLASS_LENTH		= 50;
const INT32 AGPDTITLE_MAX_TITLE_NAME_LENTH		= 50;
const INT32 AGPDTITLE_MAX_TITLE_CHECK			= 5;
const INT32 AGPDTITLE_MAX_TITLE_SKILLEFFECT		= 10;
const INT32 AGPDTITLE_MAX_TITLE_EFFECT			= 10; 

const INT32 AGPDTITLE_MAX_TITLE_REQUIRE_ITEM	= 5;
const INT32 AGPDTITLE_MAX_TITLE_REQUIRE_TITLE	= 5;

const INT32 AGPDTITLE_MAX_TITLE_REWARD_ITEM		= 5;

const INT32 AGPDTITLE_MAX_TITLE_NECESSARY_CONDITION_DESC	= 1024;
const INT32 AGPDTITLE_MAX_TITLE_EFFECT_DESC					= 256; 

const enum eAGPMTITLE_TITLE_DATA_EXCEL_COLUMN
{
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLETID	= 0,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_CLASS,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLENAME,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_STRING_TID,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_REQUIRE_LEVEL,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_REQUIRE_CLASS,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_REQUIRE_GUILDMASTER,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_REQUIRE_CLASS_ARCHLORD,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_REQUIRE_CON,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_REQUIRE_STR,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_REQUIRE_INT,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_REQUIRE_DEX,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_REQUIRE_WIS,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_REQUIRE_CHA,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_COST_GHELD,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_COST_CASH,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_COST_ITEM1,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_COST_ITEM1_COUNT,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_COST_ITEM1_TYPE,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_COST_ITEM2,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_COST_ITEM2_COUNT,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_COST_ITEM2_TYPE,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_COST_ITEM3,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_COST_ITEM3_COUNT,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_COST_ITEM3_TYPE,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_COST_ITEM4,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_COST_ITEM4_COUNT,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_COST_ITEM4_TYPE,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_COST_ITEM5,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_COST_ITEM5_COUNT,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_COST_ITEM5_TYPE,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_FIRST_TITLE1,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_FIRST_TITLE2,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_FIRST_TITLE3,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_FIRST_TITLE4,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_FIRST_TITLE5,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_CHECK_TYPE1,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_CHECK_SET1,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_CHECK_VALUE1,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_CHECK_TYPE2,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_CHECK_SET2,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_CHECK_VALUE2,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_CHECK_TYPE3,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_CHECK_SET3,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_CHECK_VALUE3,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_CHECK_TYPE4,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_CHECK_SET4,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_CHECK_VALUE4,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_CHECK_TYPE5,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_CHECK_SET5,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_CHECK_VALUE5,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_TRADE_POSSIBILITY,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_DURATION,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_REWARD_MONEY,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_REWARD_ITEM1,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_REWARD_ITEM2,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_REWARD_ITEM3,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_REWARD_ITEM4,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_REWARD_ITEM5,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_SKILL_TID1,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_SKILL_TID2,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_SKILL_TID3,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_SKILL_TID4,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_SKILL_TID5,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_SKILL_TID6,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_SKILL_TID7,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_SKILL_TID8,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_SKILL_TID9,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_SKILL_TID10,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_EFFECT_1_TYPE,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_EFFECT_1_SET,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_EFFECT_1_VALUE1,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_EFFECT_1_VALUE2,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_EFFECT_2_TYPE,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_EFFECT_2_SET,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_EFFECT_2_VALUE1,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_EFFECT_2_VALUE2,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_EFFECT_3_TYPE,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_EFFECT_3_SET,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_EFFECT_3_VALUE1,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_EFFECT_3_VALUE2,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_EFFECT_4_TYPE,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_EFFECT_4_SET,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_EFFECT_4_VALUE1,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_EFFECT_4_VALUE2,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_EFFECT_5_TYPE,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_EFFECT_5_SET,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_EFFECT_5_VALUE1,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_EFFECT_5_VALUE2,
	AGPMTITLE_TITLE_EXCEL_COLUMN_TITLE_COMMENT,
};

const enum eAGPMTITLE_TITLE_STRING_EXCEL_COLUMN
{
	AGPMTITLE_TITLE_STRING_EXCEL_COLUMN_TITLE_TID	= 0,
	AGPMTITLE_TITLE_STRING_EXCEL_COLUMN_TITLE_FIRST_CATEGORY,
	AGPMTITLE_TITLE_STRING_EXCEL_COLUMN_TITLE_CLASS_KOREA,
	AGPMTITLE_TITLE_STRING_EXCEL_COLUMN_TITLE_SECOND_CATEGORY,
	AGPMTITLE_TITLE_STRING_EXCEL_COLUMN_TITLE_NAME_KOREA,
	AGPMTITLE_TITLE_STRING_EXCEL_COLUMN_TITLE_CLASS_ENGLISH,
	AGPMTITLE_TITLE_STRING_EXCEL_COLUMN_TITLE_NAME_ENGLISH,
	AGPMTITLE_TITLE_STRING_EXCEL_COLUMN_TITLE_CLASS_JAPAN,
	AGPMTITLE_TITLE_STRING_EXCEL_COLUMN_TITLE_NAME_JAPAN,
	AGPMTITLE_TITLE_STRING_EXCEL_COLUMN_TITLE_CLASS_CHINA,
	AGPMTITLE_TITLE_STRING_EXCEL_COLUMN_TITLE_NAME_CHINA,
	AGPMTITLE_TITLE_STRING_EXCEL_COLUMN_TITLE_CLASS_FRANCE,
	AGPMTITLE_TITLE_STRING_EXCEL_COLUMN_TITLE_NAME_FRANCE,
	AGPMTITLE_TITLE_STRING_EXCEL_COLUMN_TITLE_CLASS_GERMAN,
	AGPMTITLE_TITLE_STRING_EXCEL_COLUMN_TITLE_NAME_GERMAN,
	AGPMTITLE_TITLE_STRING_EXCEL_COLUMN_TITLE_NECESSARY_CONDITION_DESC_KOREA,
	AGPMTITLE_TITLE_STRING_EXCEL_COLUMN_TITLE_EFFECT_DESC_KOREA,
	AGPMTITLE_TITLE_STRING_EXCEL_COLUMN_TITLE_NECESSARY_CONDITION_DESC_ENGLISH,
	AGPMTITLE_TITLE_STRING_EXCEL_COLUMN_TITLE_EFFECT_DESC_ENGLISH,
	AGPMTITLE_TITLE_STRING_EXCEL_COLUMN_TITLE_NECESSARY_CONDITION_DESC_JAPAN,
	AGPMTITLE_TITLE_STRING_EXCEL_COLUMN_TITLE_EFFECT_DESC_JAPAN,
	AGPMTITLE_TITLE_STRING_EXCEL_COLUMN_TITLE_NECESSARY_CONDITION_DESC_CHINA,
	AGPMTITLE_TITLE_STRING_EXCEL_COLUMN_TITLE_EFFECT_DESC_CHINA,
	AGPMTITLE_TITLE_STRING_EXCEL_COLUMN_TITLE_NECESSARY_CONDITION_DESC_FRANCE,
	AGPMTITLE_TITLE_STRING_EXCEL_COLUMN_TITLE_EFFECT_DESC_FRANCE,
	AGPMTITLE_TITLE_STRING_EXCEL_COLUMN_TITLE_NECESSARY_CONDITION_DESC_GERMAN,
	AGPMTITLE_TITLE_STRING_EXCEL_COLUMN_TITLE_EFFECT_DESC_GERMAN,
};

const enum eAGPMTITLE_TITLE_CHECK_TYPE
{
	AGPMTITLE_TITLE_CHECK_TYPE_NONE		= 0,
	AGPMTITLE_TITLE_CHECK_TYPE_COLLECTOR			= 1,
	AGPMTITLE_TITLE_CHECK_TYPE_NUMBER_OF_GATHER		= 10001,
	AGPMTITLE_TITLE_CHECK_TYPE_ALCHEMIST			= 20001,
	AGPMTITLE_TITLE_CHECK_TYPE_NATURAL_ENEMY		= 30001,
	AGPMTITLE_TITLE_CHECK_TYPE_ADDICT				= 40001,
	AGPMTITLE_TITLE_CHECK_TYPE_BIG_EATER			= 50001,
	AGPMTITLE_TITLE_CHECK_TYPE_RECONSTRUCTSPECIALIST= 60001,
	AGPMTITLE_TITLE_CHECK_TYPE_SCROLLER				= 70001,
	AGPMTITLE_TITLE_CHECK_TYPE_TRASFORMSPECIALIST	= 80001,
	AGPMTITLE_TITLE_CHECK_TYPE_MERDER				= 90001,
	AGPMTITLE_TITLE_CHECK_TYPE_REPAIRSPECIALIST		= 100001,
	AGPMTITLE_TITLE_CHECK_TYPE_RICH					= 110001,
	AGPMTITLE_TITLE_CHECK_TYPE_AUTHORITY			= 120001,
	AGPMTITLE_TITLE_CHECK_TYPE_TELEPORT				= 130001,
	AGPMTITLE_TITLE_CHECK_TYPE_ADVANCED				= 140001,
	AGPMTITLE_TITLE_CHECK_TYPE_MAGICTYPEATTACK		= 150001,
	AGPMTITLE_TITLE_CHECK_TYPE_FIRETYPEATTACK		= 150002,
	AGPMTITLE_TITLE_CHECK_TYPE_WINDTYPEATTACK		= 150003,
	AGPMTITLE_TITLE_CHECK_TYPE_WATERTYPEATTACK		= 150004,
	AGPMTITLE_TITLE_CHECK_TYPE_EARTHTYPEATTACK		= 150005,
	AGPMTITLE_TITLE_CHECK_TYPE_GHELD_EATER			= 160001,
	AGPMTITLE_TITLE_CHECK_TYPE_QUEST_COMPLETE_NUMBER= 170001,
	AGPMTITLE_TITLE_CHECK_TYPE_KILL_MONSTER			= 180001,
	AGPMTITLE_TITLE_CHECK_TYPE_BLABBER				= 190001,
	AGPMTITLE_TITLE_CHECK_TYPE_LEVEL_OF_ALCHEMIST	= 200001,
	AGPMTITLE_TITLE_CHECK_TYPE_LEVEL_OF_COOKING		= 200002,
	AGPMTITLE_TITLE_CHECK_TYPE_LEVEL_OF_HUNT		= 200003,
};

const enum eAGPMTITLE_TITLE_REQUIRE_CLASS
{
	AGPMTITLE_REQUIRE_CLASS_ALL						= 0,
	AGPMTITLE_REQUIRE_CLASS_KNIGHT					= 101,
	AGPMTITLE_REQUIRE_CLASS_ARCHER					= 201,
	AGPMTITLE_REQUIRE_CLASS_WIZARD					= 301,
	AGPMTITLE_REQUIRE_CLASS_BERSERKER				= 401,
	AGPMTITLE_REQUIRE_CLASS_HUNTER					= 501,
	AGPMTITLE_REQUIRE_CLASS_SORCERER				= 601,
	AGPMTITLE_REQUIRE_CLASS_SWASHBUCKLER			= 701,
	AGPMTITLE_REQUIRE_CLASS_RANGER					= 801,
	AGPMTITLE_REQUIRE_CLASS_ELEMENTALER				= 901,
	AGPMTITLE_REQUIRE_CLASS_SCION					= 1001,
	AGPMTITLE_REQUIRE_CLASS_SLAYER					= 1101,
	AGPMTITLE_REQUIRE_CLASS_ORBITER					= 1201,
	AGPMTITLE_REQUIRE_CLASS_SUMMONER				= 1301,
};

const enum eAGPMTITLE_TITLE_EFFECT_TYPE
{
	AGPMTITLE_TITLE_EFFECT_NONE						= 0,
	AGPMTITLE_TITLE_EFFECT_QUEST_BONUS_EXP			= 1,
	AGPMTITLE_TITLE_EFFECT_QUEST_BONUS_GHELD		= 2,
	AGPMTITLE_TITLE_EFFECT_ALCHEMIST_BONUS_RATE		= 3,
	AGPMTITLE_TITLE_EFFECT_EXTRA_COOK				= 4,
	AGPMTITLE_TITLE_EFFECT_GATHER_BONUS_RATE		= 5,
	AGPMTITLE_TITLE_EFFECT_CONVERT_BONUS_RATE		= 6,
	AGPMTITLE_TITLE_EFFECT_GATHER_BONUS_ITEM		= 7,
	AGPMTITLE_TITLE_EFFECT_HUNT_BONUS_EXP			= 8,
	AGPMTITLE_TITLE_EFFECT_POTION_BONUS				= 9,
};

class AgpdTitleRequireCondition : public ApBase
{
public:
	INT32 m_nRequireLevel;
	INT32 m_nRequireClass;
	INT32 m_nRequireGuildMaster;
	BOOL m_nRequireClassArchlord;
	INT32 m_nRequireCon;
	INT32 m_nRequireStr;
	INT32 m_nRequireInt;
	INT32 m_nRequireDex;
	INT32 m_nRequireWis;
	INT32 m_nRequireCha;
	INT32 m_nRequireGheld;
	INT32 m_nRequireCash;
	INT32 m_nRequireItemTid[AGPDTITLE_MAX_TITLE_REQUIRE_ITEM][3]; //[0]은 아이템 TID, [1]은 아이템 카운트 [2]은 소진(0)/소유(1) 여부
	INT32 m_nRequireTitleTid[AGPDTITLE_MAX_TITLE_REQUIRE_TITLE];

	AgpdTitleRequireCondition() :	m_nRequireLevel(0), m_nRequireCon(0), m_nRequireStr(0), m_nRequireInt(0),
									m_nRequireDex(0), m_nRequireWis(0), m_nRequireCha(0), m_nRequireGheld(0), 
									m_nRequireCash(0), m_nRequireClass(0), m_nRequireGuildMaster(0)
	{
		m_nRequireClassArchlord = FALSE;
	}
};

class AgpdTitleCheck : public ApBase
{
public:
	INT32 m_nTitleCheckType;
	INT32 m_nTitleCheckSet;
	INT32 m_nTitleCheckValue;

	AgpdTitleCheck() : m_nTitleCheckType(0), m_nTitleCheckSet(0), m_nTitleCheckValue(0)
	{
	}
};

class AgpdTitleSkillEffect : public ApBase
{
public:
	INT32 m_nSkillTid;

	AgpdTitleSkillEffect() : m_nSkillTid(0)
	{
	}
};


class AgpdTitleEffect : public ApBase
{
public:
	INT32	m_nEffectType;
	INT32	m_nEffectSet;
	INT32	m_nEffectValue1;
	INT32	m_nEffectValue2;

	AgpdTitleEffect() : m_nEffectType(AGPMTITLE_TITLE_EFFECT_NONE), m_nEffectSet(0), m_nEffectValue1(0), m_nEffectValue2(0)
	{
	}
};

class AgpdTitleReward : public ApBase
{
public:
	INT32 m_nRewardMoney;
	INT32 m_nRewardItemTid[AGPDTITLE_MAX_TITLE_REWARD_ITEM];

	AgpdTitleReward() : m_nRewardMoney(0)
	{
	}
};

typedef vector<AgpdTitleCheck> VectorTitleCheck;
typedef VectorTitleCheck::iterator IterTitleCheck;

typedef vector<AgpdTitleEffect> VectorTitleEffect;
typedef VectorTitleEffect::iterator IterTitleEffect;

typedef vector<AgpdTitleSkillEffect> VectorTitleSkillEffect;
typedef VectorTitleSkillEffect::iterator IterTitleSkillEffect;

class AgpdTitleTemplate : public ApBase
{
public:

	INT32	m_nTitleTid;
	CHAR	m_szTitleClass[AGPDTITLE_MAX_TITLE_CLASS_LENTH+1];
	CHAR	m_szTitleName[AGPDTITLE_MAX_TITLE_NAME_LENTH+1];
	INT32	m_nStringTid;
	BOOL	m_bDuration;
	BOOL	m_bTradePossibility;

	AgpdTitleRequireCondition m_stRequireCondition;

	AgpdTitleReward m_stReward;

	VectorTitleCheck		m_vtTitleCheck;
	VectorTitleEffect		m_vtTitleEffect;
	VectorTitleSkillEffect	m_vtTitleSkillEffect;

public:
	AgpdTitleTemplate() : m_nTitleTid(0), m_nStringTid(0)
	{
		m_bDuration = FALSE;
		m_bTradePossibility = FALSE;

		ZeroMemory(m_szTitleClass, sizeof(m_szTitleClass));
		ZeroMemory(m_szTitleName, sizeof(m_szTitleName));

		m_vtTitleCheck.reserve(AGPDTITLE_MAX_TITLE_CHECK);
		m_vtTitleCheck.clear();

		m_vtTitleEffect.reserve(AGPDTITLE_MAX_TITLE_EFFECT);
		m_vtTitleEffect.clear();

		m_vtTitleSkillEffect.reserve(AGPDTITLE_MAX_TITLE_SKILLEFFECT);
		m_vtTitleSkillEffect.clear();
	}
};

class AgpdTitleStringTemplate
{
public:
	INT32 m_nTitleTid;
	INT32 m_nFirstCategory;
	INT32 m_nSecondCategory;
	CHAR m_szTitleName[AGPDTITLE_MAX_TITLE_NAME_LENTH+1];
	CHAR m_szTitleNecessaryConditionDesc[AGPDTITLE_MAX_TITLE_NECESSARY_CONDITION_DESC+1];
	CHAR m_szTitleEffectDesc[AGPDTITLE_MAX_TITLE_EFFECT_DESC+1];

public:
	AgpdTitleStringTemplate(): m_nTitleTid(0), m_nFirstCategory(0), m_nSecondCategory(0)
	{
		ZeroMemory(m_szTitleNecessaryConditionDesc, sizeof(m_szTitleNecessaryConditionDesc));
		ZeroMemory(m_szTitleEffectDesc, sizeof(m_szTitleEffectDesc));
	}
};

typedef vector<AgpdTitleStringTemplate> vectorTitleStringTemplate;
typedef vectorTitleStringTemplate::iterator iterTitleStringTemplate;

class AgpdTitleCategory
{
public:
	INT32 m_nFirstCategory;
	CHAR m_szTitleClass[AGPDTITLE_MAX_TITLE_CLASS_LENTH+1];

public:
	AgpdTitleCategory() : m_nFirstCategory(0)
	{
		ZeroMemory(m_szTitleClass, sizeof(m_szTitleClass));
	}

};

typedef vector<AgpdTitleCategory> VectorTitleCategory;
typedef VectorTitleCategory::iterator iterTitleCategory;

#endif //__AGPDTITLETEMPLATE_H__