#ifndef __AGPM_RECRUIT_H__
#define __AGPM_RECRUIT_H__

#define	MAX_RECRUIT_CONNECTION_COUNT				10000	//10000명까지 리쿠르트 서버에 접속 가능함.
#define	MAX_RECRUIT_QUEUE_COUNT						1000	//1000개의 Queue(SQL쿼리)를 두고 처리를 함.

#define MAX_RECRUIT_ROW								5
#define AGPMRECRUIT_CLASS_FIGHTER					0x00000001
#define AGPMRECRUIT_CLASS_RANGER					0x00000002
#define AGPMRECRUIT_CLASS_MONK						0x00000004
#define AGPMRECRUIT_CLASS_MAGE						0x00000008

typedef enum
{
	AGPMRECRUIT_ADD_TO_RECRUIT = 0,	//Recruit Server에 내 클라이언트를 등록한다.
	AGPMRECRUIT_REGISTER_LFP,		//Recruit DB에 넣어줘~
	AGPMRECRUIT_CANCEL_LFP,			//Recruit DB에서 빼줘~
	AGPMRECRUIT_SEARCH_LFP_BY_PAGE,	//Recruit DB에서 Page단위로 검색한다.
	AGPMRECRUIT_REGISTER_LFM,		//Recruit DB에 넣어줘~
	AGPMRECRUIT_CANCEL_LFM,			//Recruit DB에서 빼줘~
	AGPMRECRUIT_SEARCH_LFM_BY_PAGE,	//Recruit DB에서 Page단위로 검색한다.
	AGPMRECRUIT_UPDATE_LFP,			//Recruit DB에 Data를 update한다.
	AGPMRECRUIT_RESULT,				//Recruit 결과를 보냄.
} AgpdRecruitOperation;


typedef enum
{
	AGPMRECRUIT_RESULT_FAILED = 0,
	AGPMRECRUIT_RESULT_LFP_REGISTER_SUCCEEDED,
	AGPMRECRUIT_RESULT_LFP_REGISTER_FAILED,
	AGPMRECRUIT_RESULT_LFP_CANCEL_SUCCEEDED,
	AGPMRECRUIT_RESULT_LFP_CANCEL_FAILED,
	AGPMRECRUIT_RESULT_LFM_REGISTER_SUCCEEDED,
	AGPMRECRUIT_RESULT_LFM_REGISTER_FAILED,
	AGPMRECRUIT_RESULT_LFM_CANCEL_SUCCEEDED,
	AGPMRECRUIT_RESULT_LFM_CANCEL_FAILED,
	AGPMRECRUIT_RESULT_NO_SEARCH_RESULT,
	AGPMRECRUIT_RESULT_QUEUE_FULL,					//Recruit Server의 Queue가 꽉차서 클라이언트요청을 받을수 없음.
	AGPMRECRUIT_RESULT_ERROR
} AgpdRecruitResult;

#endif
