#ifndef _AGSPGUILD_H
#define _AGSPGUILD_H

#include "AgsdRelay2.h"

enum eWorldChampionshipRelayType
{
	AGSMRELAY_PARAM_WORLD_CHAMPIONSHIP_REQUEST = 1,
	AGSMRELAY_PARAM_WORLD_CHAMPIONSHIP_ENTER,
	AGSMRELAY_PARAM_WORLD_CHAMPIONSHIP_REQUEST_RESULT,
};

struct PACKET_AGSMGUILD_RELAY : public PACKET_HEADER
{
	CHAR	FlagLow;

	INT16	nParam;

	PACKET_AGSMGUILD_RELAY()
		: nParam(0), FlagLow(1)
	{
		cType			= AGSMRELAY_PACKET_TYPE;
		unPacketLength	= (UINT16)sizeof(PACKET_AGSMGUILD_RELAY);
	}
};

struct PACKET_AGSMGUILD_RELAY_WORLD_CHAMPIONSHIP : public PACKET_AGSMGUILD_RELAY
{
	INT16 nOperation;

	PACKET_AGSMGUILD_RELAY_WORLD_CHAMPIONSHIP()
	{
		nParam			= AGSMRELAY_PARAM_WORLD_CHAMPIONSHIP;
		unPacketLength	= (UINT16)sizeof(PACKET_AGSMGUILD_RELAY_WORLD_CHAMPIONSHIP);
	}
};

struct PACKET_AGSMGUILD_RELAY_WORLD_CHAMPIONSHIP_REQUEST : PACKET_AGSMGUILD_RELAY_WORLD_CHAMPIONSHIP
{
	CHAR	strCharName[AGPDCHARACTER_NAME_LENGTH+1];
	CHAR	strGuildName[AGPMGUILD_MAX_GUILD_ID_LENGTH+1];

	PACKET_AGSMGUILD_RELAY_WORLD_CHAMPIONSHIP_REQUEST(CHAR* CharName, CHAR* GuildName)
	{
		nOperation = AGSMRELAY_PARAM_WORLD_CHAMPIONSHIP_REQUEST;
		unPacketLength = (UINT16)sizeof(PACKET_AGSMGUILD_RELAY_WORLD_CHAMPIONSHIP_REQUEST);

		memset(strCharName, 0, sizeof(strCharName));
		strcpy(strCharName, CharName);
		memset(strGuildName, 0, sizeof(strGuildName));
		strcpy(strGuildName, GuildName);
	}
};

struct PACKET_AGSMGUILD_RELAY_WORLD_CHAMPIONSHIP_ENTER : PACKET_AGSMGUILD_RELAY_WORLD_CHAMPIONSHIP
{
	CHAR	strCharName[AGPDCHARACTER_NAME_LENGTH+1];
	CHAR	m_szWorld[AGSM_MAX_SERVER_NAME+1];
	INT32	m_lServerID;

	PACKET_AGSMGUILD_RELAY_WORLD_CHAMPIONSHIP_ENTER(CHAR* CharName, INT32 lServerID, CHAR* WorldName)
	{
		nOperation = AGSMRELAY_PARAM_WORLD_CHAMPIONSHIP_ENTER;
		unPacketLength = (UINT16)sizeof(PACKET_AGSMGUILD_RELAY_WORLD_CHAMPIONSHIP_ENTER);

		memset(strCharName, 0, sizeof(strCharName));
		strcpy(strCharName, CharName);

		m_lServerID = lServerID;

		memset(m_szWorld, 0, sizeof(m_szWorld));
		strcpy(m_szWorld, WorldName);
	}
};

struct PACKET_AGSMGUILD_RELAY_WORLD_CHAMPIONSHIP_RESULT : PACKET_AGSMGUILD_RELAY_WORLD_CHAMPIONSHIP
{
	CHAR	strCharName[AGPDCHARACTER_NAME_LENGTH+1];
	INT16	m_nCode;

	PACKET_AGSMGUILD_RELAY_WORLD_CHAMPIONSHIP_RESULT(CHAR* CharName, INT16 Code)
	{
		nOperation = AGSMRELAY_PARAM_WORLD_CHAMPIONSHIP_REQUEST_RESULT;
		unPacketLength = (UINT16)sizeof(PACKET_AGSMGUILD_RELAY_WORLD_CHAMPIONSHIP_RESULT);

		memset(strCharName, 0, sizeof(strCharName));
		strcpy(strCharName, CharName);

		m_nCode = Code;
	}
};

#endif // _AGSPGUILD_H