// XTPDockingPaneResource.h
//
// This file is a part of the XTREME DOCKINGPANE MFC class library.
// (c)1998-2007 Codejock Software, All Rights Reserved.
//
// THIS SOURCE FILE IS THE PROPERTY OF CODEJOCK SOFTWARE AND IS NOT TO BE
// RE-DISTRIBUTED BY ANY MEANS WHATSOEVER WITHOUT THE EXPRESSED WRITTEN
// CONSENT OF CODEJOCK SOFTWARE.
//
// THIS SOURCE CODE CAN ONLY BE USED UNDER THE TERMS AND CONDITIONS OUTLINED
// IN THE XTREME TOOLKIT PRO LICENSE AGREEMENT. CODEJOCK SOFTWARE GRANTS TO
// YOU (ONE SOFTWARE DEVELOPER) THE LIMITED RIGHT TO USE THIS SOFTWARE ON A
// SINGLE COMPUTER.
//
// CONTACT INFORMATION:
// support@codejock.com
// http://www.codejock.com
//
/////////////////////////////////////////////////////////////////////////////

#define XTP_DOCKINGPANE_RESOURCE_FIRST         9450
#define XTP_DOCKINGPANE_RESOURCE_LAST          9499

#define XTP_IDB_DOCKINGPANE_VISIOGRIPPER       9450
#define XTP_IDB_DOCKINGPANE_STICKER_CLIENT     9451
#define XTP_IDB_DOCKINGPANE_STICKERS_BLUE      9452
#define XTP_IDB_DOCKINGPANE_STICKERS_OLIVE     9453
#define XTP_IDB_DOCKINGPANE_STICKERS_SILVER    9454
#define XTP_IDB_DOCKINGPANE_STICKERS_2005      9455

#define XTP_IDS_DOCKINGPANE_AUTOHIDE           9456
#define XTP_IDS_DOCKINGPANE_CLOSE              9457
#define XTP_IDS_DOCKINGPANE_MAXIMIZE           9458
#define XTP_IDS_DOCKINGPANE_RESTORE            9459
#define XTP_IDS_DOCKINGPANE_MENU               9460
#define XTP_IDS_DOCKINGPANE_SELECTWINDOW_ACTIVETOOLS  9461
#define XTP_IDS_DOCKINGPANE_SELECTWINDOW_ACTIVEFILES  9462
