//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by XTPCommandBarsResource.rc
//
// This file is a part of the XTREME COMMANDBARS MFC class library.
// (c)1998-2007 Codejock Software, All Rights Reserved.
//
// THIS SOURCE FILE IS THE PROPERTY OF CODEJOCK SOFTWARE AND IS NOT TO BE
// RE-DISTRIBUTED BY ANY MEANS WHATSOEVER WITHOUT THE EXPRESSED WRITTEN
// CONSENT OF CODEJOCK SOFTWARE.
//
// THIS SOURCE CODE CAN ONLY BE USED UNDER THE TERMS AND CONDITIONS OUTLINED
// IN THE XTREME TOOLKIT PRO LICENSE AGREEMENT. CODEJOCK SOFTWARE GRANTS TO
// YOU (ONE SOFTWARE DEVELOPER) THE LIMITED RIGHT TO USE THIS SOFTWARE ON A
// SINGLE COMPUTER.
//
// CONTACT INFORMATION:
// support@codejock.com
// http://www.codejock.com
//
/////////////////////////////////////////////////////////////////////////////

#define XTP_RIBBON_RESOURCE_FIRST                 9600
#define XTP_RIBBON_RESOURCE_LAST                  9649


#define XTP_IDD_RIBBONCUSTOMIZE_QUICKACCESS       9600
#define XTP_IDC_RIBBONLIST_COMMANDS               100
#define XTP_IDC_RIBBONLIST_QUICKACCESS            101
#define XTP_IDC_RIBBONCOMBO_CATEGORIES            102
#define XTP_IDC_RIBBONCHECK_SHOWQUICKACCESSBELOW  103
#define XTP_IDC_RIBBONBUTTON_ADD                  104
#define XTP_IDC_RIBBONBUTTON_REMOVE               105
#define XTP_IDC_RIBBONBUTTON_RESET                106

#define XTP_IDR_RIBBONCUSTOMIZEMENUMORE           9601
#define XTP_IDR_RIBBONCUSTOMIZEMENU               9602

#define XTP_ID_RIBBONCONTROLQUICKACCESS           9603
#define XTP_ID_RIBBONCONTROLTAB                   9604
#define XTP_ID_RIBBONCUSTOMIZE_REMOVE             9605
#define XTP_ID_RIBBONCUSTOMIZE_ADD                9606
#define XTP_ID_RIBBONCUSTOMIZE                    9607
#define XTP_ID_RIBBONCUSTOMIZE_QUICKACCESSBELOW   9608
#define XTP_ID_RIBBONCUSTOMIZE_QUICKACCESSABOVE   9610
#define XTP_ID_RIBBONCONTROLQUICKACCESSMORE       9611

#define XTP_ID_RIBBONCUSTOMIZE_MINIMIZE           9612
#define XTP_ID_RIBBONCUSTOMIZE_COMMANDS           9613
#define XTP_ID_RIBBONCUSTOMIZE_LABEL              9614
#define XTP_IDS_RIBBONCUSTOMIZE_CONFIRMRESET      9615
