//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ModelTool.rc
//
#define IDD_MODELTOOL_DIALOG            102
#define IDC_POINTER_COPY                105
#define IDC_NODROP                      106
#define IDR_MAINFRAME                   128
#define IDD_MODELTOOL_FORM              129
#define IDB_RESOURCE_TOOLBAR            130
#define IDD_RESOURCE_FORM               131
#define IDD_PROPERTY_FORM               132
#define IDD_RENDER_FORM                 133
#define IDD_TITLE_FORM                  134
#define IDD_MENU_FORM                   135
#define IDD_TOOL_FORM                   136
#define IDB_MENU_TOOLBAR                137
#define IDD_LOGIN                       139
#define IDD_STRING                      140
#define IDD_CREATE_OBJECT               141
#define IDD_CO_PROPERTY_CHARACTER       142
#define IDD_CO_PROPERTY_ITEM            143
#define IDD_CO_PROPERTY_OBJECT          144
#define IDC_CURSOR1                     145
#define IDD_SAVE                        146
#define IDD_DETAIL_INFO                 147
#define IDD_EDIT                        148
#define IDD_MERGE                       149
#define IDD_OBJECT                      151
#define IDD_OFFSET                      152
#define IDD_RENDER                      153
#define IDD_RENDER_OPTION               153
#define IDB_MENU_TOOLBAR2               155
#define IDD_ANIMATION                   157
#define IDD_EDIT_EQUIPMENTS             158
#define IDD_CO_PROPERTY_SKILL           159
#define IDD_DEFAULT_EQUIPMENTS          160
#define IDD_ITEM_TEMPLATE_LIST          161
#define IDD_ITEM_TEMPLATES_LIST         162
#define IDD_LOCK_OBJECT                 164
#define IDD_UPLOAD_RESOURCE_KEEPER      166
#define IDI_ICON1                       169
#define IDD_UPLORD_ALL_RS               172
#define IDD_TREE                        173
#define IDD_LOCK                        178
#define IDD_EDIT_FACE                   182
#define IDD_ATTACH_FACE                 183
#define IDD_TARGET_OPTION               184
#define IDD_EDIT_HAIR                   185
#define IDD_ATTACH_HAIR                 186
#define IDD_OPEN_FILES                  187
#define IDD_DEFAULT_HEAD_RENDER_TYPE    188
#define IDD_CUSTOMIZE_PREVIEW           190
#define IDD_EDIT_RIDE                   191
#define IDI_ICON2                       193
#define IDB_TRUNK_ONLY                  194
#define IDD_LIGHT_OPTION                195
#define IDC_ITEM_TEMPLATE_LIST          1000
#define IDC_CUR_STR                     1002
#define IDC_EDIT_CO_NAME                1005
#define IDC_COMBO_CO_TYPE               1006
#define IDC_BUTTON_CO_PROPERTY          1007
#define IDC_COMBO_CO_ITEM_KIND          1007
#define IDC_BUTTON_CO_MORE              1007
#define IDC_COMBO_CO_ITEM_PART          1008
#define IDC_EDIT_CO_NAME2               1008
#define IDC_EDIT_CO_ID                  1008
#define IDC_EDIT_CO_CHAR_DEF_ANIM       1011
#define IDC_EDIT_CO_CHAR_DEF_ARMOUR     1012
#define IDC_BUTTON_CO_CHAR_SET_DEF_ANIM 1013
#define IDC_BUTTON_CO_CHAR_SET_DEF_ARMOUR 1014
#define IDC_COMBO_CO_ITEM_TYPE          1014
#define IDC_STATIC_CO_ITEM_KIND         1015
#define IDC_STATIC_CO_ITEM_PART         1016
#define IDC_CHECK_CO_ITEM_TWO_HANDS     1017
#define IDC_EDIT_CO_OBJ_CATEGORY        1018
#define IDC_BUTTON_CO_OBJ_SET_CATEGORY  1019
#define IDC_EDIT_PASSWORD               1019
#define IDC_EDIT_CO_ITEM_SECOND_DFF_NAME 1020
#define IDC_EDIT_CO_OBJ_COLLISION_CLUMP 1020
#define IDC_EDIT_MERGE_2                1020
#define IDC_BUTTON_CO_ITEM_SET_SECOND_DFF_NAME 1021
#define IDC_BUTTON_CO_OBJ_SET_COLLISION_CLUMP 1021
#define IDC_BUTTON_SET_MERGE_2          1021
#define IDC_EDIT_CO_ITEM_FIELD_DFF_NAME 1022
#define IDC_EDIT_MERGE_3                1022
#define IDC_BUTTON_CO_ITEM_SET_FIELD_DFF_NAME 1023
#define IDC_BUTTON_SET_MERGE_3          1023
#define IDC_BUTTON_SAVE_CHECK_ALL       1024
#define IDC_EDIT_MERGE_4                1024
#define IDC_EDIT_ID                     1024
#define IDC_CHECK_SAVE_CHAR_TEMPLATE    1025
#define IDC_BUTTON_SET_MERGE_4          1025
#define IDC_CHECK_SAVE_ITEM_TEMPLATE    1026
#define IDC_LIST_DETAIL_INFO            1026
#define IDC_EDIT_MERGE_5                1026
#define IDC_CHECK_SAVE_OBJT_TEMPLATE    1027
#define IDC_EDIT_                       1027
#define IDC_BUTTON_SET_MERGE_5          1027
#define IDC_CHECK_SAVE_LOD_CHARACTER    1028
#define IDC_EDIT_MERGE_6                1028
#define IDC_CHECK_SAVE_LOD_ITEM         1029
#define IDC_BUTTON_SET_MERGE_6          1029
#define IDC_CHECK_SAVE_LOD_OBJECT       1030
#define IDC_EDIT_MERGE_7                1030
#define IDC_BUTTON_SAVE_CHECK_TEMPLATE  1031
#define IDC_BUTTON_SET_MERGE_7          1031
#define IDC_BUTTON_SAVE_CHECK_LOD       1032
#define IDC_EDIT_MERGE_8                1032
#define IDC_BUTTON_SET_MERGE_8          1033
#define IDC_BUTTON_SAVE_CHECK_CHARACTER 1033
#define IDC_EDIT_MERGE_9                1034
#define IDC_BUTTON_SAVE_CHECK_Item      1034
#define IDC_BUTTON_SET_MERGE_9          1035
#define IDC_BUTTON_SAVE_CHECK_OBJECT    1035
#define IDC_EDIT_MERGE_1                1036
#define IDC_CHECK_SAVE_SKILL_TEMPLATE   1036
#define IDC_BUTTON_SET_MERGE_1          1037
#define IDC_BUTTON_SAVE_CHECK_SKILL     1037
#define IDC_TREE_OBJECT_LIST            1038
#define IDC_CHECK_GEN_LOD_BOUNDARY      1038
#define IDC_CHECK_CHECK_LEVEL           1039
#define IDC_CHECK_CHAR_GEN_HEIGHT       1040
#define IDC_EDIT_OFFSET_CAMERA_ROTATE   1041
#define IDC_CHECK_CHAR_GEN_HIT_RANGE    1041
#define IDC_EDIT_OFFSET_CAMERA_ZOOM     1042
#define IDC_SHOW_FPS                    1042
#define IDC_CHECK_CHAR_GEN_BSPHERE      1042
#define IDC_EDIT_OFFSET_CAMERA_MOVE     1043
#define IDC_SHOW_COLLISION_CLUMP        1043
#define IDC_CHECK_ITEM_GEN_BSPHERE      1043
#define IDC_EDIT_OFFSET_EDIT_POSIT      1044
#define IDC_SHOW_CAMERA_POS             1044
#define IDC_CHECK_OBJ_GEN_BSPHERE       1044
#define IDC_EDIT_OFFSET_EDIT_ROTATE     1045
#define IDC_SHOW_BLOCKING               1045
#define IDC_CHECK_CHAR_GEN_COLL_DATA    1045
#define IDC_CHECK_SAVE_CHAR_GEOM_DATA   1045
#define IDC_EDIT_OFFSET_EDIT_SCALE      1046
#define IDC_SHOW_CLUMP_POLYGONS         1046
#define IDC_CHECK_ITEM_GEN_COLL_DATA    1046
#define IDC_CHECK_SAVE_ITEM_GEOM_DATA   1046
#define IDC_SHOW_CLUMP_VERTICES         1047
#define IDC_CHECK_OBJ_GEN_COLL_DATA     1047
#define IDC_CHECK_SAVE_OBJT_GEOM_DATA   1047
#define IDC_SHOW_PICK_CLUMP             1048
#define IDC_BUTTON_SAVE_CHECK_BSPHERE   1048
#define IDC_EDIT_ANIMATION_SPEED        1049
#define IDC_SHOW_WIREFRAME              1049
#define IDC_BUTTON_SAVE_CHECK_GEOMETRY  1049
#define IDC_EDIT_POSIT_RIGHT            1050
#define IDC_BUTTON_SAVE_CHECK_OCTREE    1050
#define IDC_EDIT_POSIT_UP               1051
#define IDC_CHECK_SAVE_CHAR_OCTREE_DATA 1051
#define IDC_EDIT_POSIT_AT               1052
#define IDC_CHECK_SAVE_ITEM_OCTREE_DATA 1052
#define IDC_EDIT_SCALE_RIGHT            1053
#define IDC_CHECK_SAVE_OBJT_OCTREE_DATA 1053
#define IDC_EDIT_SCALE_UP               1054
#define IDC_EDIT_SCALE_AT               1055
#define IDC_RADIO_ROTATE_RIGHT          1056
#define IDC_RADIO_ROTATE_UP             1057
#define IDC_RADIO_ROTATE_AT             1058
#define IDC_EDIT_ROTATE_DEGREE          1059
#define IDC_BUTTON_EDIT_EQUIP_APPLY     1060
#define IDC_CHECK_EDIT_EQUIP_PICK_MODE  1061
#define IDC_BUTTON_EDIT_EQUIP_RESET     1062
#define IDC_EDIT_CO_SKILL_DESCRIPTION   1062
#define IDC_CHECK_EDIT_EQUIP_MOUSE_MODE 1063
#define IDC_EDIT_DE_BODY                1063
#define IDC_BUTTON_DE_SET_BODY          1064
#define IDC_RADIO_MOUSE_MODE_AXIS_RIGHT 1064
#define IDC_BUTTON_EDIT_EQUIP_COPY      1065
#define IDC_BUTTON_DE_DEL_BODY          1065
#define IDC_CHECK_CO_OBJ_BLOCKING       1066
#define IDC_RADIO_MOUSE_MODE_AXIS_UP    1066
#define IDC_EDIT_DE_BODY2               1066
#define IDC_CHECK_CO_OBJ_RIDABLE        1067
#define IDC_BUTTON_SET_CLIENT_DATA      1067
#define IDC_RADIO_MOUSE_MODE_AXIS_AT    1067
#define IDC_BUTTON_DE_SET_BODY2         1067
#define IDC_EDIT_CO_ITEM_MAX_STACKABLE  1068
#define IDC_RADIO_MOUSE_MODE_AXIS_ALL   1068
#define IDC_BUTTON_DE_DEL_BODY2         1068
#define IDC_EDIT_DE_HEAD                1069
#define IDC_COMBO_MOUSE_MODE            1069
#define IDC_BUTTON_DE_SET_HEAD          1070
#define IDC_CHECK_LO_CHAR_TEMPLATE      1070
#define IDC_EDIT_DE_ARMS                1071
#define IDC_CHECK_LO_ITEM_TEMPLATE      1071
#define IDC_BUTTON_DE_SET_ARMS          1072
#define IDC_CHECK_LO_OBJT_TEMPLATE      1072
#define IDC_CHECK_LO_SKILL_TEMPLATE     1073
#define IDC_BUTTON_DE_DEL_HEAD          1073
#define IDC_BUTTON_DE_DEL_ARMS          1074
#define IDC_EDIT_DE_HEAD2               1075
#define IDC_BUTTON_DE_SET_HEAD2         1076
#define IDC_EDIT_DE_ARMS2               1077
#define IDC_BUTTON_DE_SET_ARMS2         1078
#define IDC_EDIT_DE_HANDS               1079
#define IDC_BUTTON_DE_SET_HANDS         1080
#define IDC_EDIT_DE_LEGS                1081
#define IDC_BUTTON_DE_SET_LEGS          1082
#define IDC_EDIT_DE_FOOT                1083
#define IDC_BUTTON_DE_SET_FOOT          1084
#define IDC_EDIT_DE_CLOAK               1085
#define IDC_BUTTON_DE_SET_CLOAK         1086
#define IDC_EDIT_DE_WEAPON              1087
#define IDC_BUTTON_DE_SET_WEAPON        1088
#define IDC_EDIT_DE_SHIELD              1089
#define IDC_BUTTON_DE_SET_SHIELD        1090
#define IDC_EDIT_DE_RING1               1091
#define IDC_BUTTON_DE_SET_RING1         1092
#define IDC_EDIT_DE_RING2               1093
#define IDC_BUTTON_DE_SET_RING2         1094
#define IDC_EDIT_DE_AMULET              1095
#define IDC_BUTTON_DE_SET_AMULET        1096
#define IDC_EDIT_RESOURCE_TITLE         1097
#define IDC_BUTTON_DE_DEL_HANDS         1097
#define ID_AMT_DLG_RESOURCE_FORM        1098
#define IDC_BUTTON_DE_DEL_LEGS          1098
#define ID_AMT_RESOURCE_TOOLBAR_DATA    1099
#define IDC_BUTTON_DE_DEL_FOOT          1099
#define IDC_BUTTON_DE_DEL_CLOAK         1100
#define ID_AMT_RESOURCE_TOOLBAR_CHARACTER 1101
#define IDC_BUTTON_DE_DEL_WEAPON        1101
#define ID_AMT_RESOURCE_TOOLBAR_ITEM    1102
#define IDC_BUTTON_DE_DEL_SHIELD        1102
#define ID_AMT_RESOURCE_TOOLBAR_OBJECT  1103
#define IDC_BUTTON_DE_DEL_RING1         1103
#define ID_AMT_MENU_TOOLBAR_SAVE        1104
#define IDC_BUTTON_DE_DEL_RING2         1104
#define ID_AMT_MENU_TOOLBAR_IMPORT      1105
#define IDC_BUTTON_DE_DEL_AMULET        1105
#define ID_AMT_MENU_TOOLBAR_EXPORT      1106
#define IDC_EDIT_DE_HANDS2              1106
#define ID_AMT_MENU_TOOLBAR_SET_MERGE_DATA 1107
#define IDC_BUTTON_DE_SET_HANDS2        1107
#define ID_AMT_MENU_TOOLBAR_MERGE       1108
#define IDC_EDIT_DE_LEGS2               1108
#define ID_AMT_MENU_TOOLBAR_TEST        1109
#define IDC_BUTTON_DE_SET_LEGS2         1109
#define ID_AMT_MENU_TOOLBAR_RK          1110
#define IDC_EDIT_DE_FOOT2               1110
#define ID_AMT_MENU_TOOLBAR_LOCK        1111
#define IDC_BUTTON_DE_SET_FOOT2         1111
#define ID_AMT_RESOURCE_TOOLBAR_SKILL   1112
#define IDC_EDIT_DE_CLOAK2              1112
#define IDC_BUTTON_DE_SET_CLOAK2        1113
#define IDC_EDIT_DE_WEAPON2             1114
#define IDC_BUTTON_DE_SET_WEAPON2       1115
#define IDC_EDIT_DE_SHIELD2             1116
#define IDC_BUTTON_DE_SET_SHIELD2       1117
#define IDC_EDIT_DE_RING3               1118
#define IDC_BUTTON_DE_SET_RING3         1119
#define IDC_EDIT_DE_RING4               1120
#define IDC_SLIDER_ANIM_TIME            1121
#define IDC_BUTTON_DE_SET_RING4         1121
#define IDC_EDIT_ANIM_CUR_TIME          1122
#define IDC_EDIT_DE_AMULET2             1122
#define IDC_BUTTON_DE_SET_AMULET2       1123
#define IDC_CHECK_MAKE_TEMPORARY_TEMPLATE 1124
#define IDC_BUTTON_DE_DEL_HEAD2         1124
#define IDC_CHECK_ANIM_PLAY             1125
#define IDC_BUTTON_DE_DEL_ARMS2         1125
#define IDC_CHECK_ANIM_STOP             1126
#define IDC_CHECK_URK_CLUMP             1126
#define IDC_BUTTON_DE_DEL_HANDS2        1126
#define IDC_CHECK_URK_LOD               1127
#define IDC_BUTTON_DE_DEL_LEGS2         1127
#define IDC_CHECK_URK_ANIMATION         1128
#define IDC_BUTTON_DE_DEL_FOOT2         1128
#define IDC_CHECK_URK_SKILL             1129
#define IDC_BUTTON_DE_DEL_CLOAK2        1129
#define IDC_CHECK_URK_EFFECT            1130
#define IDC_BUTTON_DE_DEL_WEAPON2       1130
#define IDC_BUTTON_URK_ALL              1131
#define IDC_BUTTON_DE_DEL_SHIELD2       1131
#define IDC_CHECK_URK_UI_TEXTURE        1132
#define IDC_CHECK_OFFSET_CHARACTER_TARGET 1132
#define IDC_BUTTON_DE_DEL_RING3         1132
#define IDC_CHECK_URK_UI_TEXTURE2       1133
#define IDC_UARS_UI_IMAGE               1133
#define IDC_BUTTON_DE_DEL_RING4         1133
#define IDC_TREE_ITEM                   1134
#define IDC_BUTTON_DE_DEL_AMULET2       1134
#define IDC_LIST_LOCK                   1135
#define IDC_EDIT_FACE_ADD               1137
#define IDC_EDIT_FACE_DELETE            1138
#define IDC_LIST1                       1140
#define IDC_EDIT_FACE_LISTBOX           1140
#define IDC_ATTACK_FACE_LIST            1140
#define IDC_EDIT_HAIR_LISTBOX           1140
#define IDC_ATTACH_HAIR_LIST            1140
#define IDC_TARGET_TID                  1142
#define IDC_TARGET_NUM                  1143
#define IDC_EDIT_HAIR_ADD               1143
#define IDC_TARGET_OFFSET_X             1144
#define IDC_EDIT_HAIR_DELETE            1144
#define IDC_TARGET_OFFSET_Y             1145
#define IDC_OPEN_FILES_TREE             1145
#define IDC_TARGET_OFFSET_X3            1146
#define IDC_TARGET_OFFSET_Z             1146
#define IDC_CHECK1                      1146
#define IDC_SHOW_BOUNDING_SPHERE        1146
#define IDC_CHECK_SAVE_RIDE_LIST        1146
#define IDC_BUTTON1                     1147
#define IDC_EDIT_HAIR_DELETE_ALL        1147
#define IDC_PREVIEW                     1147
#define IDC_CUSTOMIZE_PREVIEW_SETNEAR   1147
#define IDC_VIEW_HELMET                 1147
#define IDC_RIDE_ADD                    1147
#define IDC_BUTTON_SAVE                 1147
#define IDC_BUTTON_DEATCH_RIDE          1147
#define IDC_SHOW_HIT_RANGE              1147
#define IDC_LIGHT_COLOR_OPEN            1147
#define IDC_EDIT_FACE_DELETE_ALL        1148
#define IDC_RENDER_MATD3DFX             1163
#define IDC_CUSTOMIZE_PREVIEW_SETTING   1164
#define IDC_RENDER_MATD3DFX2            1164
#define IDC_ENABLE_SOUND                1164
#define IDC_CUSTOMIZE_PREVIEW_PREVIEW   1165
#define IDC_BUTTON2                     1166
#define IDC_CUSTOMIZE_PREVIEW_SETFAR    1166
#define IDC_RIDE_DELETE                 1166
#define IDC_RIDE_DELTE_ALL              1167
#define IDC_RIDE_PRIVATE_TYPE           1168
#define IDC_CHECK2                      1169
#define IDC_SHOW_TEXT_BOARDER           1169
#define IDC_OLDTYPESAVE                 1169
#define IDC_ANIMATIONRATECOMBO          1170
#define IDC_SHOW_TEXT_BOARDER2          1171
#define IDC_SAVE_CUSTOM_ANIMFILE        1171
#define IDC_NCODE_COMBO                 1171
#define IDC_SHOW_SIEGEWAR_COLL_OBJ      1172
#define IDC_RESOUCE_TREE_RECT           1174
#define IDC_LIGHT_LIST                  1176
#define IDC_LIGHT_TYPE                  1178
#define IDC_LIGHT_RADIUS                1179
#define IDC_LIGHT_ANGLE                 1180
#define IDC_LIGHT_COLOR                 1181
#define IDC_STATIC_COLOR                1182
#define IDC_SAVE_LIST                   1183
#define ID_AMT_COMMAND_RESOURCE_TREE_CONTEXT_MENU_EDIT_LABEL 1967
#define ID_AMT_COMMAND_RESOURCE_TREE_CONTEXT_MENU_DELETE_LABEL 1968
#define ID_AMT_COMMAND_RESOURCE_TREE_CONTEXT_MENU_INSERT_LABEL 1969
#define ID_AMT_COMMAND_RESOURCE_TREE_CONTEXT_MENU_COPY_ITEM 1970
#define ID_AMT_COMMAND_RESOURCE_TREE_CONTEXT_MENU_DELETE_ITEM 1971
#define ID_AMT_COMMAND_RESOURCE_TREE_CONTEXT_MENU_MOVE_ITEM 1972
#define ID_AMT_COMMAND_RESOURCE_TREE_CONTEXT_MENU_UPDATE_RESOURCE 1973
#define ID_AMT_COMMAND_RESOURCE_TREE_CONTEXT_MENU_TRUNK_ONLY 1974
#define ID_AMT_COMMAND_RESOURCE_TREE_CONTEXT_MENU_SAVE 1975
#define IDC_CHAR_RIDE_TREE              5001
#define IDD_CHAR_RIDE_DLG               5010
#define IDC_COMBO_RENDER_TYPE           5633
#define IDC_COMBO_BLEND_MODE            5634
#define IDC_RENDER_DETAILINFO           5635
#define IDC_TERRAIN_TEXTURE             5636
#define IDC_BTN_TERRAIN_TEXTURE         5637

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        196
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1184
#define _APS_NEXT_SYMED_VALUE           1121
#endif
#endif
