/****************************************************************************
 *
 * This file is a product of Criterion Software Ltd.
 *
 * This file is provided as is with no warranties of any kind and is
 * provided without any obligation on Criterion Software Ltd.
 * or Canon Inc. to assist in its use or modification.
 *
 * Criterion Software Ltd. and Canon Inc. will not, under any
 * circumstances, be liable for any lost revenue or other damages
 * arising from the use of this file.
 *
 * Copyright (c) 2001 Criterion Software Ltd.
 * All Rights Reserved.
 *
 */

/****************************************************************************
 *
 * ptankplatform.h
 *
 * Copyright (C) 2001 Criterion Technologies.
 *
 * Purpose: D3D9 specific include for ptank
 *
 ****************************************************************************/
#ifndef PTANKPLATFORM_H
#define PTANKPLATFORM_H

/* RWPUBLIC */

/**
 * \defgroup rpptankd3d9 D3D9
 * \ingroup rpptank
 *
 * D3D9 specific documentation.
 */

/**
 * \ingroup rpptankd3d9
 * \par D3D9 specific data flags
 *
 * <ul>
 * <li> rpPTANKD3D9FLAGSUSEPOINTSPRITES selects the D3D9 optimized pipeline. At the 
 * moment, this pipeline use point sprites when the hardware supports them,
 * which don't allow use of all the PTank flags. Only the following flags are
 * supported when using the D3D9 optimized pipes:
 *
 * <ul>
 * <li> rpPTANKDFLAGPOSITION
 * <li> rpPTANKDFLAGNORMAL
 * <li> rpPTANKDFLAGSIZE (if the hardware supports the D3DFVF_PSIZE vertex format flag)
 * <li> rpPTANKDFLAGCOLOR
 * <li> rpPTANKDFLAGUSECENTER
 * <li> rpPTANKDFLAGCNSVTX2TEXCOORDS
 * <li> rpPTANKDFLAGARRAY
 * <li> rpPTANKDFLAGSTRUCTURE
 * </ul>
 *
 * The texture coordinates are generated by the hardware and can't be specified,
 * but rpPTANKDFLAGCNSVTX2TEXCOORDS need to be used tp specify that the point sprites 
 * are textured.
 * </ul>
 *
 * If the hardware does not support point sprites, the default pipeline is used
 * instead.
 * 
 */

enum RpPTankD3D9Flags
{
    rpPTANKD3D9FLAGSUSEPOINTSPRITES = 0x00000001,

    rpPTANKD3D9FLAGFORCEENUMSIZEINT = RWFORCEENUMSIZEINT
};

typedef enum RpPTankD3D9Flags RpPTankD3D9Flags;

/* RWPUBLICEND */

#endif /* PTANKPLATFORM_H */
