/****************************************************************************
 *
 * This file is a product of Criterion Software Ltd.
 *
 * This file is provided as is with no warranties of any kind and is
 * provided without any obligation on Criterion Software Ltd.
 * or Canon Inc. to assist in its use or modification.
 *
 * Criterion Software Ltd. and Canon Inc. will not, under any
 * circumstances, be liable for any lost revenue or other damages
 * arising from the use of this file.
 *
 * Copyright (c) 2001 Criterion Software Ltd.
 * All Rights Reserved.
 *
 */
/****************************************************************************
 *
 * ptankd3d9.c
 *
 * Copyright (C) 2001 Criterion Technologies.
 *
 *
 * Purpose: D3D9 Billboard implementation.
 *
 ****************************************************************************/

/**
 * \ingroup rpptankd3d9
 *
 * \page rpptankd3d9overview D3D9 RpPTank Overview
 *
 * The D3D9 optimized verion of RpPTank uses point sprites when the hardware supports them.
 * Please note that point sprites severely limits the capabilities of the billboards.
 * Due to hardware limitations, only the following flags are respected:
 *
 * \li rpPTANKDFLAGPOSITION
 * \li rpPTANKDFLAGNORMAL
 * \li rpPTANKDFLAGSIZE (if the hardware supports the D3DFVF_PSIZE vertex format flag)
 * \li rpPTANKDFLAGCOLOR
 * \li rpPTANKDFLAGUSECENTER
 * \li rpPTANKDFLAGCNSVTX2TEXCOORDS
 * \li rpPTANKDFLAGARRAY
 * \li rpPTANKDFLAGSTRUCTURE
 *
 * All the other flags are ignored. You can also specify a constant color or a constant
 * size for all the billboards.
 *
 * \note As the D3D9 point sprites are always square, only the x size of the constant size
 * will be taken into account.
 * \note As the texture coordinates are generated by the hardware and can't be specified, 
 * calls to RpPTankAtomicSetConstantVtx2TexCoords are ignored, but the flag is 
 * needed to specify that the point sprites are textured.
 *
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <d3d9.h>

#include "rwcore.h"
#include "rpworld.h"
#include "rpplugin.h"
#include "rpdbgerr.h"
#include "ptank.h"
#include "ptankprv.h"
#include "ptankg.h"

#include "ptankd3d9.h"
#include "ptankplatform.h"

#define ALIGNPAD 16

#define FLOATASINT(f) (*((const RwInt32 *)&(f)))

#define VALIDPOINTSPRITESFLAGS  (rpPTANKDFLAGPOSITION |         \
                                 rpPTANKDFLAGNORMAL |           \
                                 rpPTANKDFLAGCOLOR |            \
                                 rpPTANKDFLAGUSECENTER |        \
                                 rpPTANKDFLAGCNSVTX2TEXCOORDS | \
                                 rpPTANKDFLAGARRAY |            \
                                 rpPTANKDFLAGSTRUCTURE)

#define VALIDPOINTSPRITESSIZEFLAGS  (rpPTANKDFLAGPOSITION |         \
                                     rpPTANKDFLAGNORMAL |           \
                                     rpPTANKDFLAGCOLOR |            \
                                     rpPTANKDFLAGSIZE |             \
                                     rpPTANKDFLAGUSECENTER |        \
                                     rpPTANKDFLAGCNSVTX2TEXCOORDS | \
                                     rpPTANKDFLAGARRAY |            \
                                     rpPTANKDFLAGSTRUCTURE)

#define RGBATOD3D9COLOR(_col)    ( (((RwUInt32)((_col)->alpha)) << 24) |  \
                                 (((RwUInt32)((_col)->red)) << 16) |     \
                                 (((RwUInt32)((_col)->green)) << 8) |    \
                                 ((RwUInt32)((_col)->blue)) )


#if (0)

static RwBool
rpPTankD3D9Instance(RpAtomic *atomic,
                    RpPTankData *ptankGlobal,
                    RwInt32 actPCount,
                    RwUInt32 instFlags);

static void
rpPTankD3D9InsPosNCCSPR(RpPTankLockStruct *dstCluster,
                        RwV3d *right,
                        RwV3d *up,
                        RwInt32 pCount,
                        RpPTankData *ptankGlobal);

static void
rpPTankD3D9InsPosNCPSPR(RpPTankLockStruct *dstCluster,
                        RwV3d *right,
                        RwV3d *up,
                        RwInt32 pCount,
                        RpPTankData *ptankGlobal);

static void
rpPTankD3D9InsPosCCCSPR(RpPTankLockStruct *dstCluster,
                        RwV3d *right,
                        RwV3d *up,
                        RwInt32 pCount,
                        RpPTankData *ptankGlobal);

#endif /* (0) */

static RwBool
rpPTankD3D9Create(RpAtomic *atomic,
                  RpPTankData *ptankGlobal,
                  RwInt32 maxPCount,
                  RwUInt32 dataFlags,
                  RwUInt32 platFlags);


static RwBool
rpPTankD3D9RenderCallBack(RpAtomic *atomic,
                          RpPTankData *ptankGlobal,
                          RwInt32 actPCount);
static void
rpPTankD3D9InsPosNCCSNR_spr(RpPTankLockStruct *dstCluster,
                        RwV3d *right,
                        RwV3d *up,
                        RwInt32 pCount,
                        RpPTankData *ptankGlobal);
static void
rpPTankD3D9InsPosCCCSNR_spr(RpPTankLockStruct *dstCluster,
                        RwV3d *right,
                        RwV3d *up,
                        RwInt32 pCount,
                        RpPTankData *ptankGlobal);

static void
rpPTankD3D9InsPosNCPSNR_spr(RpPTankLockStruct *dstCluster,
                        RwV3d *right,
                        RwV3d *up,
                        RwInt32 pCount,
                        RpPTankData *ptankGlobal);
static void
rpPTankD3D9InsPosCCPSNR_spr(RpPTankLockStruct *dstCluster,
                        RwV3d *right,
                        RwV3d *up,
                        RwInt32 pCount,
                        RpPTankData *ptankGlobal);

static void
rpPTankD3D9InsNormals_spr(RpPTankLockStruct *dstCluster,
                        RwInt32 pCount,
                        RpPTankData *ptankGlobal);

static void
rpPTankD3D9InsColor_spr(RpPTankLockStruct *dstCluster,
                        RwInt32 pCount,
                        RpPTankData *ptankGlobal);


RpPTankCallBacks defaultCB =
{
    NULL,                       /* Alloc, using default one */
    rpPTankD3D9Create,
    _rpPTankGENInstance,
    rpPTankD3D9RenderCallBack
};

/*
 * Global static variables
 */
static LPDIRECT3DINDEXBUFFER9 rpTankD3D9IndexBuffer = NULL;
static RwInt32 rpTankD3D9MaxIndex = 0;

static LPDIRECT3DVERTEXBUFFER9 rpTankD3D9DynamicVertexBuffer = NULL;
static RwUInt32 rpTankD3D9BaseIndex = 0;

static RwReal rpTankD3D9VideoCardMaxPointSize = 1.f;
static RwBool rpTankD3D9VideoCardSizePerParticle = FALSE;

RwBool rpTankD3D9UsePointSprites = FALSE;

/*
 *****************************************************************************
 */
static __inline void
SinCos(float angle, float *sine, float *cosine)
{
    RWFUNCTION(RWSTRING("SinCos"));

#if defined(NOASM)
    *sine = (RwReal)RwSin(angle);
    *cosine = (RwReal)RwCos(angle);
#else
    __asm
    {
        fld        dword ptr angle
        fsincos
        mov        eax, sine
        mov        edx, cosine
        fstp    dword ptr [edx]
        fstp    dword ptr [eax]
    }
#endif

    RWRETURNVOID();
}

void
rpPTankD3D9InsEnding(RpPTANKInstanceSetupData *data,
                RpAtomic *atomic,
                RpPTankData *ptankGlobal,
                RwInt32 actPCount,
                RwUInt32 instFlags)
{
    RWFUNCTION( RWSTRING( "rpPTankD3D9InsEnding" ) );

    RwD3D9DynamicVertexBufferUnlock(rpTankD3D9DynamicVertexBuffer);

    RWRETURNVOID();
}

void
rpPTankD3D9InsSetup(RpPTANKInstanceSetupData *data,
                RpAtomic *atomic,
                RpPTankData *ptankGlobal,
                RwInt32 actPCount,
                RwUInt32 instFlags)
{
    RwInt32         numVertices;
    RpGeometry      *geom;
    RpGeometryFlag  flags;
    RpMaterial      *material;
    RwV3d           *right = &data->right;
    RwV3d           *up = &data->up;
    RwUInt32        strideVertex;
    const RwMatrix  *camLTM;
    RwUInt8         *vertexData = NULL;
    RwUInt32        fvf;


    RWFUNCTION(RWSTRING("rpPTankD3D9InsSetup"));

    RWASSERT(atomic);
    RWASSERT(RpAtomicIsPTank(atomic));

    numVertices = actPCount * 4;

    geom = RpAtomicGetGeometry(atomic);

    flags = (RpGeometryFlag)RpGeometryGetFlags(geom);

    material = RpGeometryGetMaterial(geom, 0);

    if (material->texture)
    {
    if ( (flags & rxGEOMETRY_TEXTURED) == 0)
    {
        RpGeometrySetFlags(geom, flags | rxGEOMETRY_TEXTURED);
    }
    }
    else
    {
        if ( (flags & rxGEOMETRY_TEXTURED) != 0)
        {
            RpGeometrySetFlags(geom, flags & ~rxGEOMETRY_TEXTURED);
        }
    }

    /* Get current camera matrix */
    camLTM = RwFrameGetLTM(RwCameraGetFrame((RwCamera *)RWSRCGLOBAL(curCamera)));

    /*
     * Calculate FVF and Stride
     */
    flags = (RpGeometryFlag)RpGeometryGetFlags(geom);

    /* What do we instance ?? */
    /* Well every thing as it's a DYNAMIC buffer */

    /* Positions */
    strideVertex = sizeof(RwV3d);
    fvf = D3DFVF_XYZ;
    data->instancePositions = TRUE;

    /* Normals */
    if (flags & rxGEOMETRY_NORMALS)
    {
        strideVertex += sizeof(RwV3d);
        fvf |= D3DFVF_NORMAL;

        data->instanceNormals = TRUE;
    }

    /* Pre-lighting */
    if (flags & rxGEOMETRY_PRELIT)
    {
        strideVertex += sizeof(RwRGBA);
        fvf |= D3DFVF_DIFFUSE;
        data->instanceColors = TRUE;
    }

    /* Texture coordinates */
    if (flags & rxGEOMETRY_TEXTURED)
    {
        strideVertex += sizeof(RwTexCoords);
        fvf |= D3DFVF_TEX1;
        data->instanceUVs = TRUE;
    }

    /* Request and lock the needed vertex buffer */
    /*Setting up right and up vectors */
    if((ptankGlobal->format.dataFlags & rpPTANKDFLAGCNSMATRIX )
                                            == rpPTANKDFLAGCNSMATRIX)
    {
        RwV3dAssign(right, RwMatrixGetRight(&ptankGlobal->cMatrix));
        RwV3dAssign(up, RwMatrixGetUp(&ptankGlobal->cMatrix));
    }
    else if((ptankGlobal->format.dataFlags & rpPTANKDFLAGCNS2DROTATE)
                                            == rpPTANKDFLAGCNS2DROTATE)
    {
        RwV3d   rightCamera;
        RwV3d   upCamera;
        RwReal  sinA, cosA;

        rightCamera.x = -camLTM->right.x;
        rightCamera.y = -camLTM->right.y;
        rightCamera.z = -camLTM->right.z;

        upCamera.x = camLTM->up.x;
        upCamera.y = camLTM->up.y;
        upCamera.z = camLTM->up.z;

        SinCos(ptankGlobal->cRotate, &sinA, &cosA);

        /* Calculate world space size vectors */
        right->x = (+ cosA) * rightCamera.x + (- sinA) * upCamera.x;
        right->y = (+ cosA) * rightCamera.y + (- sinA) * upCamera.y;
        right->z = (+ cosA) * rightCamera.z + (- sinA) * upCamera.z;

        up->x = (+ sinA) * rightCamera.x + (+ cosA) * upCamera.x;
        up->y = (+ sinA) * rightCamera.y + (+ cosA) * upCamera.y;
        up->z = (+ sinA) * rightCamera.z + (+ cosA) * upCamera.z;
    }
    else
    {
        right->x = -camLTM->right.x;
        right->y = -camLTM->right.y;
        right->z = -camLTM->right.z;

        up->x = camLTM->up.x;
        up->y = camLTM->up.y;
        up->z = camLTM->up.z;
    }

    if(RwD3D9DynamicVertexBufferLock(strideVertex,
                                      numVertices,
                                      (void **)&rpTankD3D9DynamicVertexBuffer,
                                      (void **)&vertexData,
                                      &rpTankD3D9BaseIndex))
    {
        RwUInt32 offset = 0;

        if( data->instancePositions )
        {
            data->positionOut.data = (RwUInt8 *)vertexData;
            data->positionOut.stride = strideVertex;
        }

        offset = sizeof(RwV3d);

        if( data->instanceNormals )
        {
            data->normalsOut.data = (RwUInt8 *)(vertexData + sizeof(RwV3d));
            data->normalsOut.stride =  strideVertex;
        }

        if(flags & rxGEOMETRY_NORMALS)
        {
            offset += sizeof(RwV3d);
        }

        if( data->instanceColors )
        {
            data->colorsOut.data = (RwUInt8 *)(vertexData + offset);
            data->colorsOut.stride = strideVertex;
        }

        if( flags & rxGEOMETRY_PRELIT)
        {
            offset += sizeof(RwRGBA);
        }

        if( data->instanceUVs )
        {
                data->UVOut.data = (RwUInt8 *)(vertexData + offset);
                data->UVOut.stride = strideVertex;
        }
    }

    rpTankD3D9UsePointSprites = FALSE;

    RWRETURNVOID();
}

void
rpPTankD3D9InsSetup_spr(RpPTANKInstanceSetupData *data,
                RpAtomic *atomic,
                RpPTankData *ptankGlobal,
                RwInt32 actPCount,
                RwUInt32 instFlags)
{
    RpGeometryFlag  flags;
    RwUInt32        strideVertex;
    RwInt32         numVertices;
    RwUInt8         *vertexData = NULL;
    RwUInt32        fvf;
    RpGeometry      *geom;
#if (0)
    RwV3d           *right = &data->right;
    RwV3d           *up = &data->up;
#endif /* (0) */
    RWFUNCTION(RWSTRING("rpPTankD3D9InsSetup_spr"));

    RWASSERT(atomic);
    RWASSERT(RpAtomicIsPTank(atomic));

    geom = RpAtomicGetGeometry(atomic);
    numVertices = actPCount;

    flags = (RpGeometryFlag)RpGeometryGetFlags(geom);

    if ( (flags & rxGEOMETRY_TEXTURED) != 0)
    {
        RpGeometrySetFlags(geom, flags & ~rxGEOMETRY_TEXTURED);
    }

    /*
     * Calculate FVF and Stride
     */
    flags = (RpGeometryFlag)RpGeometryGetFlags(geom);

    /* Positions */
    strideVertex = sizeof(RwV3d);
    fvf = D3DFVF_XYZ;

    data->instancePositions = TRUE;

    /* Normals */
    if (flags & rxGEOMETRY_NORMALS)
    {
        strideVertex += sizeof(RwV3d);
        fvf |= D3DFVF_NORMAL;

        data->instanceNormals = TRUE;
    }

    /* Pre-lighting */
    if (flags & rxGEOMETRY_PRELIT)
    {
        strideVertex += sizeof(RwRGBA);
        fvf |= D3DFVF_DIFFUSE;

        data->instanceColors = TRUE;
    }

    if ((ptankGlobal->format.dataFlags & rpPTANKDFLAGSIZE) != 0)
    {
        strideVertex += sizeof(RwReal);
        fvf |= D3DFVF_PSIZE;
    }

    /* Request and lock the needed vertex buffer */
    if(RwD3D9DynamicVertexBufferLock(strideVertex,
                                      numVertices,
                                      (void **)&rpTankD3D9DynamicVertexBuffer,
                                      (void **)&vertexData,
                                      &rpTankD3D9BaseIndex))
    {
        RwUInt32 offset = 0;

        if( data->instancePositions )
        {
            data->positionOut.data = (RwUInt8 *)vertexData;
            data->positionOut.stride = strideVertex;
        }

        offset = sizeof(RwV3d);

        if( data->instanceNormals )
        {
            data->normalsOut.data = (RwUInt8 *)(vertexData + sizeof(RwV3d));
            data->normalsOut.stride =  strideVertex;
        }

        if(flags & rxGEOMETRY_NORMALS)
        {
            offset += sizeof(RwV3d);
        }

        if ((ptankGlobal->format.dataFlags & rpPTANKDFLAGSIZE) != 0)
        {
            offset += sizeof(RwReal);
        }

        if( data->instanceColors )
        {
            data->colorsOut.data = (RwUInt8 *)(vertexData + offset);
            data->colorsOut.stride = strideVertex;
        }

    }

    rpTankD3D9UsePointSprites = TRUE;

    RWRETURNVOID();
}

/*
 ***************************************************************************
 */
static RwBool
rpPTankD3D9RenderCallBack(RpAtomic *atomic,
                          RpPTankData *ptankGlobal,
                          RwInt32 actPCount)
{
    RwBool          lighting;
    RpGeometry      *geom;
    RpMaterial      *material;
    RpGeometryFlag  flags;
    RwUInt32        fvf;
    RwUInt32        stride;
    RwUInt32        shadeMode;
    RwBool          useConstantColor = FALSE;
    RwBlendFunction srcBlend, dstBlend;
    RwInt32         numVertices;
    RwInt32         firstVertex;

    RWFUNCTION(RWSTRING("rpPTankD3D9RenderCallBack"));

    geom = RpAtomicGetGeometry(atomic);
    material = RpGeometryGetMaterial(geom,0);
    flags = (RpGeometryFlag)RpGeometryGetFlags(geom);

    /*
     * Calculate FVF and Stride
     */

    /* Positions */
    stride = sizeof(RwV3d);
    fvf = D3DFVF_XYZ;

    /* Normals */
    if (flags & rxGEOMETRY_NORMALS)
    {
        stride += sizeof(RwV3d);
        fvf |= D3DFVF_NORMAL;
    }

    /* Pre-lighting */
    if (flags & rxGEOMETRY_PRELIT)
    {
        stride += sizeof(RwRGBA);
        fvf |= D3DFVF_DIFFUSE;
    }

    /* Texture coordinates */
    if (flags & rxGEOMETRY_TEXTURED)
    {
        stride += sizeof(RwTexCoords);
        fvf |= D3DFVF_TEX1;
    }

    if (rpTankD3D9UsePointSprites &&
        (ptankGlobal->format.dataFlags & rpPTANKDFLAGSIZE) != 0)
    {
        stride += sizeof(RwReal);
        fvf |= D3DFVF_PSIZE;
    }

    /* Set lights */
    _rwD3D9AtomicDefaultLightingCallback((void *)atomic);

    /*
     * Set the world transform to identity
     */
    RwD3D9SetTransformWorld(NULL);


    /*
     * Set needed render states
     */
    RwD3D9GetRenderState(D3DRS_LIGHTING, &lighting);
    RwD3D9GetRenderState(D3DRS_SHADEMODE, &shadeMode);

    RwD3D9SetRenderState(D3DRS_NORMALIZENORMALS, FALSE);

    if (lighting == FALSE)
    {
        if ((flags & rxGEOMETRY_PRELIT) == 0)
        {
            RwUInt32 color;

            useConstantColor = TRUE;

            color = RGBATOD3D9COLOR(&(ptankGlobal->cColor));

            RwD3D9SetRenderState(D3DRS_TEXTUREFACTOR, color);

            RwD3D9SetRenderState(D3DRS_SHADEMODE, D3DSHADE_FLAT);

            if (material->texture)
            {
                RwD3D9SetTextureStageState(0, D3DTSS_COLOROP,   D3DTOP_MODULATE);
                RwD3D9SetTextureStageState(0, D3DTSS_ALPHAOP,   D3DTOP_MODULATE);
            }
            else
            {
                RwD3D9SetTextureStageState(0, D3DTSS_COLOROP,   D3DTOP_SELECTARG2);
                RwD3D9SetTextureStageState(0, D3DTSS_ALPHAOP,   D3DTOP_SELECTARG2);
            }

            RwD3D9SetTextureStageState(0, D3DTSS_COLORARG1, D3DTA_TEXTURE);
            RwD3D9SetTextureStageState(0, D3DTSS_COLORARG2, D3DTA_TFACTOR);

            RwD3D9SetTextureStageState(0, D3DTSS_ALPHAARG1, D3DTA_TEXTURE);
            RwD3D9SetTextureStageState(0, D3DTSS_ALPHAARG2, D3DTA_TFACTOR);
        }
        else if( (ptankGlobal->format.dataFlags &
                 (rpPTANKDFLAGVTXCOLOR | rpPTANKDFLAGCNSVTXCOLOR)) == 0)
        {
            RwD3D9SetRenderState(D3DRS_SHADEMODE, D3DSHADE_FLAT);
        }
    }

    if (!useConstantColor)
    {
        if (material->texture)
        {
            RwD3D9SetTextureStageState(0, D3DTSS_COLOROP,   D3DTOP_MODULATE);
            RwD3D9SetTextureStageState(0, D3DTSS_ALPHAOP,   D3DTOP_MODULATE);
        }
        else
        {
            RwD3D9SetTextureStageState(0, D3DTSS_COLOROP,   D3DTOP_SELECTARG2);
            RwD3D9SetTextureStageState(0, D3DTSS_ALPHAOP,   D3DTOP_SELECTARG2);
        }

        RwD3D9SetTextureStageState(0, D3DTSS_COLORARG1, D3DTA_TEXTURE);
        RwD3D9SetTextureStageState(0, D3DTSS_COLORARG2, D3DTA_DIFFUSE);

        RwD3D9SetTextureStageState(0, D3DTSS_ALPHAARG1, D3DTA_TEXTURE);
        RwD3D9SetTextureStageState(0, D3DTSS_ALPHAARG2, D3DTA_DIFFUSE);
    }

    /* As I don't relly in the bounding sphere I'll force clipping */
    RwD3D9SetRenderState(D3DRS_CLIPPING, TRUE);

    /*
     * Set the Default Pixel shader
     */
    RwD3D9SetPixelShader(0);

    /*
     * Vertex shader
     */
    RwD3D9SetVertexShader(NULL);

    /*
     * Vertex format
     */
    RwD3D9SetFVF(fvf);

    /*
     * Texture
     */
    RwD3D9SetTexture(material->texture, 0);

    /*
     * Enable vertex alpha blend if needed
     */
    if (ptankGlobal->vertexAlphaBlend)
    {
        RwRenderStateGet(rwRENDERSTATESRCBLEND, (void *)&srcBlend);
        RwRenderStateSet(rwRENDERSTATESRCBLEND, (void *)(ptankGlobal->srcBlend));

        RwRenderStateGet(rwRENDERSTATEDESTBLEND, (void *)&dstBlend);
        RwRenderStateSet(rwRENDERSTATEDESTBLEND, (void *)(ptankGlobal->dstBlend));

        RwRenderStateSet(rwRENDERSTATEVERTEXALPHAENABLE, (void *)TRUE);
    }
    else
    {
        RwRenderStateSet(rwRENDERSTATEVERTEXALPHAENABLE, (void *)FALSE);
    }

    if (lighting)
    {
        RwD3D9SetSurfaceProperties(&(material->surfaceProps),
                                    &(material->color),
                                    flags);
    }

    /* Set the stream source */
    RwD3D9SetStreamSource(0, rpTankD3D9DynamicVertexBuffer, 0, stride);

    /* render particles */
    if (rpTankD3D9UsePointSprites)
    {
        RwReal temp;

        RwD3D9SetRenderState(D3DRS_POINTSPRITEENABLE, TRUE);
        RwD3D9SetRenderState(D3DRS_POINTSCALEENABLE,  TRUE);

        temp = ptankGlobal->cSize.x;
        RwD3D9SetRenderState(D3DRS_POINTSIZE,     *((RwUInt32 *)(&temp)));

        temp = 0.00f;
        RwD3D9SetRenderState(D3DRS_POINTSIZE_MIN, *((RwUInt32 *)(&temp)));

        temp = rpTankD3D9VideoCardMaxPointSize;
        RwD3D9SetRenderState(D3DRS_POINTSIZE_MAX, *((RwUInt32 *)(&temp)));

        temp = 0.00f;
        RwD3D9SetRenderState(D3DRS_POINTSCALE_A,  *((RwUInt32 *)(&temp)));

        temp = 0.00f;
        RwD3D9SetRenderState(D3DRS_POINTSCALE_B,  *((RwUInt32 *)(&temp)));

        temp = 0.50f;
        RwD3D9SetRenderState(D3DRS_POINTSCALE_C,  *((RwUInt32 *)(&temp)));

        /* Draw the points sprites */
        numVertices = actPCount;
        firstVertex = rpTankD3D9BaseIndex;

        while (1)
        {
            if (numVertices <= 0xffff)
            {
                RwD3D9DrawPrimitive(D3DPT_POINTLIST, firstVertex, numVertices);

                break;
            }
            else
            {
                RwD3D9DrawPrimitive(D3DPT_POINTLIST, firstVertex, 0xffff);

                firstVertex += 0xffff;
                numVertices -= 0xffff;
            }
        }

        RwD3D9SetRenderState(D3DRS_POINTSPRITEENABLE, FALSE);
        RwD3D9SetRenderState(D3DRS_POINTSCALEENABLE,  FALSE);
    }
    else
    {
        const RwInt32 MaxVerticesPacket = (0xffff & (~3));

        numVertices = actPCount * 4;
        firstVertex = rpTankD3D9BaseIndex;

        RWASSERT(rpTankD3D9IndexBuffer != NULL);

        /* Set the Index buffer */
        RwD3D9SetIndices(rpTankD3D9IndexBuffer);

        /* Draw the quads */
        while (1)
        {
            /* Draw the indexed primitives */
            if (numVertices <= MaxVerticesPacket) /* Check num of triangles */
            {
                RwD3D9DrawIndexedPrimitive(D3DPT_TRIANGLELIST,
                                           firstVertex,
                                           0, numVertices,
                                           0, (numVertices / 2));

                break;
            }
            else
            {

                RwD3D9DrawIndexedPrimitive(D3DPT_TRIANGLELIST,
                                           firstVertex,
                                           0, MaxVerticesPacket,
                                           0, (MaxVerticesPacket / 2));

                numVertices -= MaxVerticesPacket;
                firstVertex += MaxVerticesPacket;
           }
        }
    }

    /* Restore render states */
    RwD3D9SetRenderState(D3DRS_SHADEMODE, shadeMode);

    if (ptankGlobal->vertexAlphaBlend)
    {
        RwRenderStateSet(rwRENDERSTATESRCBLEND, (void *)srcBlend);
        RwRenderStateSet(rwRENDERSTATEDESTBLEND, (void *)dstBlend);
    }

    RWRETURN(FALSE);
}

/*
 ***************************************************************************
 */
static RwBool
rpPTankD3D9Create(RpAtomic *atomic, RpPTankData *ptankGlobal,
            RwInt32 maxPCount, RwUInt32 dataFlags,
            RwUInt32 platFlags)
{
    RwBool              result = TRUE;
    RpGeometry          *geom = NULL;
    RwSurfaceProperties surfProp;
    RpMaterial          *material;
    RwUInt32            geomFlag;
    RpTriangle          triangle;

    RWFUNCTION(RWSTRING("rpPTankD3D9Create"));

    RWASSERT(atomic);
    RWASSERT(RpAtomicIsPTank(atomic));

    geomFlag = rpGEOMETRYPOSITIONS;

    if( (dataFlags & rpPTANKDFLAGNORMAL) == rpPTANKDFLAGNORMAL )
    {
        geomFlag |= rpGEOMETRYLIGHT
                    | rpGEOMETRYNORMALS
                    | rpGEOMETRYMODULATEMATERIALCOLOR;
    }

    if( (dataFlags &
        (rpPTANKDFLAGCOLOR | rpPTANKDFLAGVTXCOLOR | rpPTANKDFLAGCNSVTXCOLOR)) != 0 )
    {
        geomFlag |= rpGEOMETRYPRELIT;
    }

    /* Check point sprites */
    if((platFlags & rpPTANKD3D9FLAGSUSEPOINTSPRITES)
                                        == rpPTANKD3D9FLAGSUSEPOINTSPRITES)
    {
        if (rpTankD3D9VideoCardMaxPointSize <= 1.f)
        {
            RWMESSAGE(("Point Sprites not supported by current 3D Hardware"));

            platFlags &= ~rpPTANKD3D9FLAGSUSEPOINTSPRITES;
        }
        else if ((ptankGlobal->format.dataFlags & (~VALIDPOINTSPRITESFLAGS))
                                                != 0)
        {
            if ( (ptankGlobal->format.dataFlags & (~VALIDPOINTSPRITESSIZEFLAGS)) != 0 ||
                 !rpTankD3D9VideoCardSizePerParticle )
            {
                RWMESSAGE(("dataFlag not valid for Point Sprites"));

                platFlags &= ~rpPTANKD3D9FLAGSUSEPOINTSPRITES;
            }
        }
    }

    if((platFlags & rpPTANKD3D9FLAGSUSEPOINTSPRITES)
                                            != rpPTANKD3D9FLAGSUSEPOINTSPRITES)
    {
        geomFlag |= rpGEOMETRYTEXTURED;
    }

    geom = RpGeometryCreateSpace(1.f);

    RpGeometrySetFlags(geom, geomFlag);

    /*
     * Create the material
     */
    material = RpMaterialCreate();

    /*
     * Set the surface reflection coefficients...
     */
    surfProp.ambient = 0.3f;
    surfProp.diffuse = 1.0f;
    surfProp.specular = 1.0f;
    RpMaterialSetSurfaceProperties(material, &surfProp);

    /* Add the material to a dummy triangle */
    RpGeometryTriangleSetMaterial(geom, &triangle, material);

    /*
     * Associate the geom with the atomic. This will increment the
     * geom's reference count by 1...
     */
    RpAtomicSetGeometry(atomic, geom, 0);

    /*
     * As a convenience, we can remove the application's ownership of the
     * geom, materials and textures it created by calling the corresponding
     * destroy functions. This will decrement their reference counts
     * without actually deleting the resources because they now have other
     * owners (the atomic owns the geom, the geom and its triangles
     * own the materials, each material owns a texture). Now we can simply use
     * RpClumpDestroy later when the application has finished with it...
     */
    RpGeometryDestroy(geom);

    RpMaterialDestroy(material);

    if (result)
    {
        /*
         * Check index buffer size if needed
         */
        if((platFlags & rpPTANKD3D9FLAGSUSEPOINTSPRITES)
                        != rpPTANKD3D9FLAGSUSEPOINTSPRITES)
        {
            if (rpTankD3D9IndexBuffer == NULL ||
                rpTankD3D9MaxIndex < (maxPCount * 2 * 3))
            {
                if (rpTankD3D9IndexBuffer != NULL)
                {
                    IDirect3DIndexBuffer9_Release(rpTankD3D9IndexBuffer);
                    rpTankD3D9IndexBuffer = NULL;
                }

                rpTankD3D9MaxIndex = (maxPCount * 2 * 3);

                if (RwD3D9IndexBufferCreate(rpTankD3D9MaxIndex, (void **)&rpTankD3D9IndexBuffer))
                {
                    RxVertexIndex   *indexData;

                    if (SUCCEEDED(IDirect3DIndexBuffer9_Lock(rpTankD3D9IndexBuffer,
                                                            0, 0,
                                                            (RwUInt8 **)&indexData,
                                                            0)))
                    {
                        RwInt32 i;

                        for (i=0; i < maxPCount; i++)
                        {
                            indexData[0] = i * 4 + 0;
                            indexData[1] = i * 4 + 1;
                            indexData[2] = i * 4 + 2;

                            indexData[3] = i * 4 + 0;
                            indexData[4] = i * 4 + 2;
                            indexData[5] = i * 4 + 3;

                            indexData += 2 * 3;
                        }

                        IDirect3DIndexBuffer9_Unlock(rpTankD3D9IndexBuffer);
                    }
                }
            }
        }
    }

    /* Initialize constant color to black opaque */
    ptankGlobal->cColor.red = 0;
    ptankGlobal->cColor.green = 0;
    ptankGlobal->cColor.blue = 0;
    ptankGlobal->cColor.alpha = 0xff;

    _rpPTankGENInstanceSelectCB(atomic);


    /* Instancing Callback Patch */
    {
        RpPTankAtomicExtPrv *PTankPrv;

        PTankPrv = RPATOMICPTANKPLUGINDATA(atomic);

        if((platFlags & rpPTANKD3D9FLAGSUSEPOINTSPRITES)
                                            == rpPTANKD3D9FLAGSUSEPOINTSPRITES)
        {
            PTankPrv->insSetupCB =
                    (RpPTankGENInstanceSetupCallback)rpPTankD3D9InsSetup_spr;

            if ((ptankGlobal->format.dataFlags & rpPTANKDFLAGSIZE) != 0)
            {
                if( PTankPrv->insPosCB == (RpPTankGENInstancePosCallback)
                                                rpPTankGENInsPosNCPSNR )
                {
                    PTankPrv->insPosCB = (RpPTankGENInstancePosCallback)
                                                rpPTankD3D9InsPosNCPSNR_spr;
                }
                else if( PTankPrv->insPosCB == (RpPTankGENInstancePosCallback)
                                                rpPTankGENInsPosCCPSNR )
                {
                    PTankPrv->insPosCB = (RpPTankGENInstancePosCallback)
                                                rpPTankD3D9InsPosCCPSNR_spr;
                }
                else
                {
                    RWASSERT(FALSE && "Not supported point sprites instance funtion.");
                }
            }
            else
            {
                if( PTankPrv->insPosCB == (RpPTankGENInstancePosCallback)
                                                rpPTankGENInsPosNCCSNR )
                {
                    PTankPrv->insPosCB = (RpPTankGENInstancePosCallback)
                                                rpPTankD3D9InsPosNCCSNR_spr;
                }
                else if( PTankPrv->insPosCB == (RpPTankGENInstancePosCallback)
                                                rpPTankGENInsPosCCCSNR )
                {
                    PTankPrv->insPosCB = (RpPTankGENInstancePosCallback)
                                                rpPTankD3D9InsPosCCCSNR_spr;
                }
                else
                {
                    RWASSERT(FALSE && "Not supported point sprites instance funtion.");
                }
            }

            if( PTankPrv->insNormalsCB == (RpPTankGENInstanceCallback)
                                            rpPTankGENInsNormals)
            {
                PTankPrv->insNormalsCB = (RpPTankGENInstanceCallback)
                                            rpPTankD3D9InsNormals_spr;
            }

            if( PTankPrv->insColorsCB == (RpPTankGENInstanceCallback)
                                            rpPTankGENInsColorPP)
            {
                PTankPrv->insColorsCB = (RpPTankGENInstanceCallback)
                                            rpPTankD3D9InsColor_spr;
            }
        }
        else
        {
            PTankPrv->insSetupCB =
                    (RpPTankGENInstanceSetupCallback)rpPTankD3D9InsSetup;
        }

        PTankPrv->insEndingCB =
                        (RpPTankGENInstanceSetupCallback)rpPTankD3D9InsEnding;
    }


    RWRETURN(result);
}


/*
 *****************************************************************************
 */
static void
rpPTankD3D9InsPosNCCSNR_spr(RpPTankLockStruct *dstCluster,
                        RwV3d *right,
                        RwV3d *up,
                        RwInt32 pCount,
                        RpPTankData *ptankGlobal)
                        /* no center, constant size, no rotation */
{
    RwInt32 i;
    RwV3d *src;
    RwV3d *dst;
    RwUInt8 *uSrc;
    RwUInt32 uStride;
    RwUInt8 *uDst;
    RwUInt32 uDStride;

    RWFUNCTION(RWSTRING("rpPTankD3D9InsPosNCCSNR_spr"));
    RWASSERT(TRUE == rpTankD3D9UsePointSprites);

    uSrc = ptankGlobal->clusters[RPPTANKSIZEPOSITION].data;
    uStride = ptankGlobal->clusters[RPPTANKSIZEPOSITION].stride;

    uDst = dstCluster->data;
    uDStride = dstCluster->stride;

    if (uStride == uDStride &&
        uStride == sizeof(RwV3d))
    {
        memcpy(uDst, uSrc, pCount * sizeof(RwV3d));
    }
    else
    {
        for (i = 0 ; i < pCount ; i++)
        {
            src = (RwV3d*)uSrc;

            /* vtx 0 */
            dst = (RwV3d*)uDst;
            dst->x = src->x;
            dst->y = src->y;
            dst->z = src->z;
            uDst += uDStride;

            uSrc += uStride;

        }
    }

    RWRETURNVOID();
}

static void
rpPTankD3D9InsPosCCCSNR_spr(RpPTankLockStruct *dstCluster,
                        RwV3d *right,
                        RwV3d *up,
                        RwInt32 pCount,
                        RpPTankData *ptankGlobal)
                        /* no center, constant size, no rotation */
{
    RwInt32 i;
    RwV3d *src;
    RwV3d *dst;
    RwUInt8 *uSrc;
    RwUInt32 uStride;
    RwUInt8 *uDst;
    RwUInt32 uDStride;

    RWFUNCTION(RWSTRING("rpPTankD3D9InsPosCCCSNR_spr"));
    RWASSERT(TRUE == rpTankD3D9UsePointSprites);

    uSrc = ptankGlobal->clusters[RPPTANKSIZEPOSITION].data;
    uStride = ptankGlobal->clusters[RPPTANKSIZEPOSITION].stride;

    uDst = dstCluster->data;
    uDStride = dstCluster->stride;

    for (i = 0 ; i < pCount ; i++)
    {
        src = (RwV3d*)uSrc;

        /* vtx 0 */
        dst = (RwV3d*)uDst;
        dst->x = src->x + ptankGlobal->cCenter.x;
        dst->y = src->y + ptankGlobal->cCenter.y;
        dst->z = src->z ;
        uDst += uDStride;

        uSrc += uStride;

    }

    RWRETURNVOID();
}
static void
rpPTankD3D9InsPosNCPSNR_spr(RpPTankLockStruct *dstCluster,
                        RwV3d *right,
                        RwV3d *up,
                        RwInt32 pCount,
                        RpPTankData *ptankGlobal)
                        /* no center, constant size, no rotation */
{
    RwInt32 i;
    RwV3d *src;
    RwV2d *srcSize;
    RwV3d *dst;
    RwReal *dstSize;
    RwUInt8 *uSrc;
    RwUInt32 uStride;
    RwUInt8 *uSize;
    RwUInt32 uSStride;
    RwUInt8 *uDst;
    RwUInt32 uDStride;
    RwUInt8 *uDstSize;

    RWFUNCTION(RWSTRING("rpPTankD3D9InsPosNCPSNR_spr"));
    RWASSERT(TRUE == rpTankD3D9UsePointSprites);

    uSrc = ptankGlobal->clusters[RPPTANKSIZEPOSITION].data;
    uStride = ptankGlobal->clusters[RPPTANKSIZEPOSITION].stride;

    uSize = ptankGlobal->clusters[RPPTANKSIZESIZE].data;
    uSStride = ptankGlobal->clusters[RPPTANKSIZESIZE].stride;

    uDst = dstCluster->data;
    uDStride = dstCluster->stride;

    uDstSize = uDst + sizeof(RwV3d);
    if (ptankGlobal->format.dataFlags & rpPTANKDFLAGNORMAL)
    {
        uDstSize += sizeof(RwV3d);
    }

    for (i = 0 ; i < pCount ; i++)
    {
        src = (RwV3d*)uSrc;
        srcSize = (RwV2d*)uSize;

        /* vtx 0 */
        dst = (RwV3d*)uDst;
        dst->x = src->x;
        dst->y = src->y;
        dst->z = src->z;
        uDst += uDStride;

        dstSize = (RwReal*)uDstSize;
        *dstSize = srcSize->x;
        uDstSize += uDStride;

        uSrc += uStride;
        uSize += uSStride;
    }

    RWRETURNVOID();
}

static void
rpPTankD3D9InsPosCCPSNR_spr(RpPTankLockStruct *dstCluster,
                        RwV3d *right,
                        RwV3d *up,
                        RwInt32 pCount,
                        RpPTankData *ptankGlobal)
                        /* no center, constant size, no rotation */
{
    RwInt32 i;
    RwV3d *src;
    RwV2d *srcSize;
    RwV3d *dst;
    RwReal *dstSize;
    RwUInt8 *uSrc;
    RwUInt32 uStride;
    RwUInt8 *uSize;
    RwUInt32 uSStride;
    RwUInt8 *uDst;
    RwUInt32 uDStride;
    RwUInt8 *uDstSize;

    RWFUNCTION(RWSTRING("rpPTankD3D9InsPosCCPSNR_spr"));
    RWASSERT(TRUE == rpTankD3D9UsePointSprites);

    uSrc = ptankGlobal->clusters[RPPTANKSIZEPOSITION].data;
    uStride = ptankGlobal->clusters[RPPTANKSIZEPOSITION].stride;

    uSize = ptankGlobal->clusters[RPPTANKSIZESIZE].data;
    uSStride = ptankGlobal->clusters[RPPTANKSIZESIZE].stride;

    uDst = dstCluster->data;
    uDStride = dstCluster->stride;

    uDstSize = uDst + sizeof(RwV3d);
    if (ptankGlobal->format.dataFlags & rpPTANKDFLAGNORMAL)
    {
        uDstSize += sizeof(RwV3d);
    }

    for (i = 0 ; i < pCount ; i++)
    {
        src = (RwV3d*)uSrc;
        srcSize = (RwV2d*)uSize;

        /* vtx 0 */
        dst = (RwV3d*)uDst;
        dst->x = src->x + ptankGlobal->cCenter.x;
        dst->y = src->y + ptankGlobal->cCenter.y;
        dst->z = src->z ;
        uDst += uDStride;

        dstSize = (RwReal*)uDstSize;
        *dstSize = srcSize->x;
        uDstSize += uDStride;

        uSrc += uStride;
        uSize += uSStride;
    }

    RWRETURNVOID();
}

static void
rpPTankD3D9InsNormals_spr(RpPTankLockStruct *dstCluster,
                        RwInt32 pCount,
                        RpPTankData *ptankGlobal)
{
    RwInt32 i;
    RwUInt8 *uDst;
    RwUInt32 uDStride;
    RwUInt8 *uSrc;
    RwUInt32 uSStride;
    RwV3d *src,*dst;

    RWFUNCTION(RWSTRING("rpPTankD3D9InsNormals_spr"));
    RWASSERT(TRUE == rpTankD3D9UsePointSprites);

    uDst = dstCluster->data;
    uDStride = dstCluster->stride;

    uSrc = ptankGlobal->clusters[RPPTANKSIZENORMAL].data;
    uSStride = ptankGlobal->clusters[RPPTANKSIZENORMAL].stride;

    for(i=0;i<pCount;i++)
    {
        src = (RwV3d *)uSrc;

        dst = (RwV3d *)uDst;
        dst->x = src->x;
        dst->y = src->y;
        dst->z = src->z;
        uDst += uDStride;

        uSrc += uSStride;
    }

    RWRETURNVOID();
}

static void
rpPTankD3D9InsColor_spr(RpPTankLockStruct *dstCluster,
                        RwInt32 pCount,
                        RpPTankData *ptankGlobal)
                         /* 1 Color per particle*/
{
    RwInt32 i;
    RwRGBA *src;
    RwUInt32 *dst;
    RwUInt8 *uDst;
    RwUInt32 uDStride;
    RwUInt8 *uSrc;
    RwUInt32 uSStride;

    RWFUNCTION(RWSTRING("rpPTankD3D9InsColor_spr"));
    RWASSERT(TRUE == rpTankD3D9UsePointSprites);

    uDst = dstCluster->data;
    uDStride = dstCluster->stride;

    uSrc = ptankGlobal->clusters[RPPTANKSIZECOLOR].data;
    uSStride = ptankGlobal->clusters[RPPTANKSIZECOLOR].stride;

    for (i = 0 ; i < pCount ; i++)
    {
        src = (RwRGBA *)uSrc;

        /* vtx 0 */
        dst = (RwUInt32 *)uDst;
        *dst = RGBATOD3D9COLOR(src);
        uDst += uDStride;

        uSrc += uSStride;

    }

    RWRETURNVOID();
}


/*
 *****************************************************************************
 */
void *
PTankOpen(void *object,
                    RwInt32 __RWUNUSED__ offset,
                    RwInt32 __RWUNUSED__ size)
{
    const D3DCAPS9 *d3d9caps;

    RWFUNCTION(RWSTRING("PTankOpen"));

    d3d9caps = (const D3DCAPS9 *)RwD3D9GetCaps();

    rpTankD3D9VideoCardMaxPointSize =
                        (d3d9caps->MaxPointSize);

    rpTankD3D9VideoCardSizePerParticle =
                        ((d3d9caps->FVFCaps & D3DFVFCAPS_PSIZE) != 0);

    RWRETURN(object);
}


/*
 *****************************************************************************
 */
void        *
PTankClose(void *object,
                    RwInt32 __RWUNUSED__ offset,
                    RwInt32 __RWUNUSED__ size)
{
    RWFUNCTION(RWSTRING("PTankClose"));

    if (rpTankD3D9IndexBuffer != NULL)
    {
        IDirect3DIndexBuffer9_Release(rpTankD3D9IndexBuffer);
        rpTankD3D9IndexBuffer = NULL;
    }

    rpTankD3D9MaxIndex = 0;

    RWRETURN(object);
}
