//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by UITool.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_UITOOLTYPE                  129
#define IDD_UIT_WINDOW_PROPERTY         134
#define IDD_UIT_WP_WINDOW_DIALOG        134
#define IDR_CONTROLS                    139
#define IDD_DIALOG2                     141
#define IDD_UIT_MESSAGE_MAPS            141
#define IDD_UIT_DISPLAY_MAP             142
#define IDD_UIT_ACTION                  143
#define IDD_UIT_EVENT_MAPS              144
#define IDD_UIT_STATUS                  145
#define IDD_UIT_WP_MAP_DIALOG           146
#define IDD_UIT_WP_STYLE                147
#define IDD_UIT_WP_BUTTON               148
#define IDD_UIT_USER_DATA               150
#define IDD_UIT_WP_GRID                 152
#define IDD_UIT_WP_BAR                  153
#define IDD_UIT_WP_LIST                 154
#define IDD_UIT_WP_UI                   155
#define IDD_UIT_HOTKEY                  156
#define IDD_UIT_WP_SKILLTREE            157
#define IDD_UIT_WP_EDIT                 158
#define IDD_UIT_WP_SCROLL               159
#define IDD_UIT_SELECT_CUSTOM           160
#define IDD_UIT_UI_MODE                 161
#define IDD_UIT_WP_COMBO                162
#define IDD_UIT_WP_TREE                 164
#define IDD_UIT_WP_CLOCK                165
#define IDD_UIT_WP_ANIMATION            166
#define IDC_UIT_WINDOW_NAME             1000
#define IDC_UIT_WINDOW_X                1001
#define IDC_UIT_WINDOW_W                1002
#define IDC_UIT_WINDOW_Y                1003
#define IDC_UIT_WINDOW_H                1004
#define IDC_UIT_WINDOW_TEXTURE          1005
#define IDC_UIT_STRING_COLOR_R          1005
#define IDC_UIT_WINDOW_BROWSE           1006
#define IDC_UIT_STRING_COLOR_G          1006
#define IDC_UIT_WINDOW_RED              1007
#define IDC_UIT_STRING_COLOR_B          1007
#define IDC_UIT_WINDOW_GREEN            1008
#define IDC_UIT_WINDOW_BLUE             1009
#define IDC_UIT_WINDOW_ALPHA            1010
#define IDC_UIT_EDIT_MESSAGEMAP         1011
#define IDC_UIT_MESSAGE_LIST            1012
#define IDC_UIT_EDIT_DISPLAY            1012
#define IDC_UIT_ACTION_LIST             1013
#define IDC_UIT_SET_HANDLER             1013
#define IDC_UIT_MESSAGE_NAME            1014
#define IDC_UIT_EDIT_STATUS             1014
#define IDC_UIT_FUNCTIONS               1015
#define IDC_UIT_EVENT_DESCRIPTION       1015
#define IDC_UIT_EDIT_USER_DATA          1015
#define IDC_UIT_ARGS_1                  1016
#define IDC_UIT_ARGS_2                  1017
#define IDC_UIT_ARGS_3                  1018
#define IDC_UIT_ARGS_4                  1019
#define IDC_UIT_ARGS_5                  1020
#define IDC_UIT_ARG_DESCRIPTION         1021
#define IDC_UIT_UPDATE_MESSAGE_MAP      1022
#define IDC_UIT_ACTION_TYPE             1023
#define IDC_UIT_ACTION_UI               1024
#define IDC_UIT_DISPLAYMAP_TYPE         1024
#define IDC_UIT_CAPTION                 1025
#define IDC_UIT_ADD_ACTION              1025
#define IDC_UIT_ACTION_UI_TYPE          1025
#define IDC_UIT_DISPLAY_LIST            1026
#define IDC_UIT_DELETE_ACTION           1026
#define IDC_UIT_ACTION_CONTROL          1026
#define IDC_UIT_UPDATE_DISPLAY_MAP      1027
#define IDC_UIT_ACTION_CONTROL_STATUS   1027
#define IDC_UIT_EDIT_ACTION             1027
#define IDC_UIT_ACTION_CONTROL_STATUS_CURRENT1 1027
#define IDC_UIT_TEXTURE_LIST            1028
#define IDC_UIT_USER_DATA_LIST          1028
#define IDC_UIT_ADD_HOTKEY              1028
#define IDC_UIT_ACTION_CONTROL_STATUS_TARGET1 1028
#define IDC_UIT_ADD_TEXTURE             1029
#define IDC_UIT_FONT_TYPE               1029
#define IDC_UIT_ACTION_CONTROL_STATUS_CURRENT2 1029
#define IDC_UIT_USERDATA_LIST           1029
#define IDC_UIT_EDIT_TEXTURE            1030
#define IDC_UIT_ACTION_CONTROL_STATUS_TARGET2 1030
#define IDC_UIT_FONT_HALIGN             1030
#define IDC_UIT_EDIT_TEXTURE2           1031
#define IDC_UIT_DELETE_TEXTURE          1031
#define IDC_UIT_EVENT_NAME              1031
#define IDC_UIT_ACTION_CONTROL_STATUS_CURRENT3 1031
#define IDC_UIT_FONT_VALIGN             1031
#define IDC_UIT_EVENT_LIST              1032
#define IDC_UIT_SET_TEXTURE             1032
#define IDC_UIT_ACTION_CONTROL_STATUS_TARGET3 1032
#define IDC_UIT_STATUS_LIST             1033
#define IDC_UIT_DELETE                  1033
#define IDC_UIT_ACTION_DISPLAY_LIST     1033
#define IDC_UIT_STATUS_NAME             1034
#define IDC_UIT_SIZE_AS_IMAGE           1034
#define IDC_UIT_ACTION_UD_LIST          1034
#define IDC_UIT_ACTION_ATTACH_UI        1035
#define IDC_UIT_ADD_STATUS              1036
#define IDC_UIT_UPDATE_STATUS           1037
#define IDC_UIT_SAVE_STATUS             1037
#define IDC_UIT_DELETE_STATUS           1038
#define IDC_UIT_GROUP_ACTION            1038
#define IDC_UIT_SET_DEFAULT_STATUS      1039
#define IDC_UIT_WP_USE_INPUT            1039
#define IDC_UIT_SMOOTH_UI               1039
#define IDC_UIT_WP_MOVABLE              1040
#define IDC_UIT_BUTTON_NORMAL           1040
#define IDC_UIT_WP_MODAL                1041
#define IDC_UIT_BUTTON_ONMOUSE          1041
#define IDC_UIT_WP_TOPMOST              1042
#define IDC_UIT_BUTTON_CLICK            1042
#define IDC_UIT_WP_VISIBLE              1043
#define IDC_UIT_BUTTON_DISABLE          1043
#define IDC_UIT_BUTTON_APPLY            1044
#define IDC_UIT_WP_SHRINK               1044
#define IDC_UIT_BUTTON_CANCEL           1045
#define IDC_UIT_WP_ALIGN                1045
#define IDC_UIT_PUSH_BUTTON             1046
#define IDC_UIT_WP_CONDENSATION         1046
#define IDC_UIT_GRID_LIST               1047
#define IDC_UIT_BUTTON_CHECK_BOOLEAN    1047
#define IDC_UIT_WP_CLIPIMAGE            1047
#define IDC_UIT_GRID_START_X            1048
#define IDC_UIT_BAR_CURRENT             1048
#define IDC_UIT_BUTTON_CHECK_USERDATA   1048
#define IDC_UIT_GRID_START_Y            1049
#define IDC_UIT_CANCEL                  1049
#define IDC_UIT_BAR_IMAGE_HEAD          1049
#define IDC_UIT_BUTTON_ENABLE_BOOLEAN   1049
#define IDC_UIT_GRID_GAP_X              1050
#define IDC_UIT_APPLY                   1050
#define IDC_UIT_BAR_MAX                 1050
#define IDC_UIT_BUTTON_ENABLE_USERDATA  1050
#define IDC_UIT_GRID_GAP_Y              1051
#define IDC_UIT_BAR_IMAGE_BODY          1051
#define IDC_UIT_LIST_ITEM               1051
#define IDC_UIT_GRID_ITEM_WIDTH         1052
#define IDC_UIT_PARENT_UI               1052
#define IDC_UIT_LIST_ITEM_COLUMN        1052
#define IDC_UIT_GRID_ITEM_HEIGHT        1053
#define IDC_UIT_BAR_MAX_DISPLAY         1053
#define IDC_UIT_COORD_SYSTEM            1053
#define IDC_UIT_TREE_DEPTH_MARGIN       1053
#define IDC_UIT_BAR_CURRENT_DISPLAY     1054
#define IDC_UIT_GROUP_POSITION          1054
#define IDC_UIT_SKILLTREE_IMAGE_1_3     1054
#define IDC_UIT_FONT_RED                1055
#define IDC_UIT_MAIN_UI                 1055
#define IDC_UIT_SKILLTREE_IMAGE_2_3     1055
#define IDC_UIT_FONT_GREEN              1056
#define IDC_UIT_SKILLTREE_IMAGE_3_3     1056
#define IDC_UIT_UI_TYPE                 1056
#define IDC_UIT_FONT_BLUE               1057
#define IDC_UIT_SKILLTREE_IMAGE_1_10    1057
#define IDC_UIT_MODE_1024               1057
#define IDC_UIT_FONT_RED2               1058
#define IDC_UIT_SKILLTREE_IMAGE_1_2     1058
#define IDC_UIT_MODE_1280               1058
#define IDC_UIT_FONT_SHADOW             1059
#define IDC_UIT_SKILLTREE_IMAGE_2_2     1059
#define IDC_UIT_MODE_1600               1059
#define IDC_UIT_HOTKEY_LIST             1060
#define IDC_UIT_FONT_ALPHA              1060
#define IDC_UIT_AUTO_CLOSE              1060
#define IDC_UIT_HOTKEY_CODE             1061
#define IDC_UIT_EVENT_UI                1061
#define IDC_UIT_FONT_COMMA              1061
#define IDC_UIT_HOTKEY_STATUS           1062
#define IDC_UIT_UI_FOCUS_SET            1062
#define IDC_UIT_UI_FOCUS_KILL           1063
#define IDC_UIT_UI_TRANSPARENT          1064
#define IDC_UIT_WINDOW_VISIBLE          1065
#define IDC_UIT_EDIT_PASSWORD           1066
#define IDC_UIT_MOVABLE_GRID            1067
#define IDC_UIT_EDIT_MULTILINE          1067
#define IDC_UIT_ACTION_MS_TYPE          1068
#define IDC_UIT_EDIT_READONLY           1068
#define IDC_UIT_ACTION_MS_MS            1069
#define IDC_UIT_EDIT_AUTOLF             1069
#define IDC_UIT_ACTION_MS_COLOR_R       1070
#define IDC_UIT_EDIT_ENABLE_TAG         1070
#define IDC_UIT_ACTION_MS_COLOR_G       1071
#define IDC_UIT_EDIT_FILTER_CASE        1071
#define IDC_UIT_ACTION_MS_COLOR_B       1072
#define IDC_UIT_EDIT_FILTER_CASE2       1072
#define IDC_UIT_EDIT_RELEASE_INPUTEND   1072
#define IDC_UIT_ACTION_MS_COLOR_A       1073
#define IDC_UIT_EDIT_RELEASE_INPUTEND2  1073
#define IDC_UIT_EDIT_HOTKEY             1073
#define IDC_UIT_ITEMWRITECOUNT_GRID     1074
#define IDC_UIT_ACTION_SOUND            1074
#define IDC_UIT_ACTION_UI_POSX          1075
#define IDC_UIT_MOVEITEMCOPY_GRID       1076
#define IDC_UIT_ACTION_UI_POSY          1076
#define IDC_UIT_INIT_STATUS             1077
#define IDC_UIT_START_ACTIVE            1078
#define IDC_UIT_REUSABLE_DISPLAY        1079
#define IDC_UIT_SHOW_CB                 1080
#define IDC_UIT_SHOW_UD                 1081
#define IDC_UIT_SCROLL_VERTICAL         1082
#define IDC_UIT_SCROLL_MIN              1083
#define IDC_UIT_SCROLL_MAX              1084
#define IDC_UIT_SCROLL_UNIT             1085
#define IDC_UIT_SCROLL_BY_UNIT          1086
#define IDC_UIT_SCROLL_MAX_UD           1087
#define IDC_UIT_SCROLL_MAX_DISPLAY      1088
#define IDC_UIT_SCROLL_CURRENT_UD       1089
#define IDC_UIT_SCROLL_CURRENT_DISPLAY  1090
#define IDC_UIT_CUSTOM_CONTROL          1091
#define IDC_UIT_SCROLL_UP_BUTTON        1091
#define IDC_UIT_SCROLL_DOWN_BUTTON      1092
#define IDC_UIT_ACTION_ADD_VARIABLE     1093
#define IDC_UIT_DRAWFOREGROUND_GRID     1094
#define IDC_UIT_SOUND_BROWSE            1095
#define IDC_UIT_UI_MODES                1096
#define IDC_UIT_EDIT_LENGTH             1097
#define IDC_UIT_BUTTON_TEXT_OFFSET_X    1098
#define IDC_UIT_BUTTON_TEXT_OFFSET_Y    1099
#define IDC_UIT_BAR_VERTICAL            1099
#define IDC_UIT_BAR_CUT_HEAD            1100
#define IDC_UIT_BAR_SMOOTH              1101
#define IDC_UIT_COMBO_NORMAL            1105
#define IDC_UIT_COMBO_ONMOUSE           1106
#define IDC_UIT_COMBO_CLICK             1107
#define IDC_UIT_COMBO_HEIGHT            1108
#define IDC_UIT_LIST_START_BOTTOM       1109
#define IDC_UIT_COMBO_BOTTOM            1109
#define IDC_UIT_USER_DATA_INDEX         1111
#define IDC_UIT_TOOLTIP                 1112
#define IDC_UIT_TREE_DEPTH_USERDATA     1113
#define IDC_UIT_TREE_OPEN_BUTTON        1114
#define IDC_UIT_TREE_CLOSE_BUTTON       1115
#define IDC_UIT_CLOCK_MAX               1116
#define IDC_UIT_CLOCK_MAX_DISPLAY       1117
#define IDC_UIT_CLOCK_CURRENT           1118
#define IDC_UIT_CLOCK_CURRENT_DISPLAY   1119
#define IDC_UIT_CLOCK_IMAGE_ALPHA       1120
#define IDC_UIT_LIST_SELECTION_IMAGE    1122
#define IDC_UIT_ANIM_LIST               1124
#define IDC_UIT_ANIM_TEXTURE            1125
#define IDC_UIT_ANIM_CLOCK              1126
#define IDC_UIT_ANIM_STRING             1127
#define IDC_UIT_ANIM_BASE_TEXTURE       1128
#define IDC_UIT_ANIM_DEFAULT            1129
#define IDC_UIT_ANIM_ADD                1130
#define IDC_UIT_ANIM_REMOVE             1131
#define IDC_UIT_ANIM_UPDATE             1132
#define IDC_UIT_ANIM_START              1134
#define IDC_UIT_ANIM_STOP               1135
#define IDC_HOTKEY_DESCRIPTION          1135
#define IDC_HOTKEY_CUSTOMIZABLE         1136
#define ID_UIT_MENU_NEW                 32771
#define ID_CONTROL_STATIC               32772
#define ID_CONTROL_EDITBOX              32773
#define ID_CONTROL_BUTTON               32774
#define ID_CONTROL_COMBO                32775
#define ID_CONTROL_LIST                 32776
#define ID_UIT_SAVE                     32777
#define ID_UIT_LOAD                     32778
#define ID_BUTTON32780                  32780
#define ID_BUTTON32781                  32781
#define ID_MODE_EDIT                    32782
#define ID_MODE_RUN                     32783
#define ID_UIT_EDIT_EVENT               32784
#define ID_MODE_AREA                    32785
#define ID_CONTROL_GRID                 32787
#define ID_CONTROL_BAR                  32790
#define ID_CONNECT_SERVER               32791
#define ID_EDIT_DELETE                  32792
#define ID_CONTROL_SKILLTREE            32795
#define ID_UIT_EDIT_HOTKEY              32796
#define UIT_MODE_VIEW_GRID              32799
#define ID_UIT_MODE_VIEW_GRID           32800
#define ID_CONTROL_SCROLL               32801
#define ID_CONTROL_CUSTOM               32802
#define ID_SET_UI_MODE                  32803
#define ID_CONTROL_TREE                 32805
#define ID_CONTROL_CLOCK                32806
#define ID_VIEW_FITTOWINDOWSIZE         32808
#define ID_VIEW_1024                    32809
#define ID_VIEW_1280                    32810
#define ID_VIEW_1600                    32811
#define ID_Menu                         32812
#define ID_Menu32813                    32813
#define ID_UIT_COPY_UI                  32814

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        167
#define _APS_NEXT_COMMAND_VALUE         32816
#define _APS_NEXT_CONTROL_VALUE         1137
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
