# What plugin are we building ?

PLUGIN = rphanim

# Who are the maintainers ?
MAINTAINERS = blakem

CSRC =			\
    $(CURDIR)/stdkey.c	\
    $(CURDIR)/hanimopt.c

ifndef BASEDIR
BASEDIR = $(CURDIR)/../..
endif
include $(BASEDIR)/makeincl/makeplug
