# What plugin are we building ?

PLUGIN = rt2danim

# Who are the maintainers ?
MAINTAINERS = alexandreh gregb

CSRC =				\
	$(CURDIR)/anim.c	\
	$(CURDIR)/keyframe.c	\
	$(CURDIR)/props.c    	\
	$(CURDIR)/bucket.c	\
	$(CURDIR)/strlabel.c	\
	$(CURDIR)/button.c	\
	$(CURDIR)/message.c	\
	$(CURDIR)/maestro.c	\
	$(CURDIR)/handler.c	\
	$(CURDIR)/cel.c \
    $(CURDIR)/gstate.c

ifndef BASEDIR
BASEDIR = $(CURDIR)/../..
endif
include $(BASEDIR)/makeincl/maketool
