//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AlefAdminDLL.rc
//
#define IDD_CHARACTER                   101
#define IDC_CB_SEARCH_TYPE              2001
#define IDC_B_SEARCH                    2003
#define IDC_E_SEARCH_FIELD              2004
#define IDC_LC_SEARCH_RESULT            2005
#define IDC_MAIN_TAB                    2009
#define IDC_TAB_MAIN                    2009
#define IDC_TAB_CHAR                    2014
#define IDD_MAIN                        4000
#define IDC_CB_TYPE                     4000
#define IDC_CB_POS                      4000
#define IDR_MENU_MAIN                   4001
#define IDD_ITEM                        4001
#define IDC_B_REFRESH                   4001
#define IDC_LC_ITEM                     4002
#define IDD_SKILL                       4002
#define IDS_EDIT_RESULT_1               4003
#define IDC_S_ITEM_CONVERT              4004
#define IDS_EDIT_RESULT_2               4004
#define IDD_OPTION                      4004
#define IDC_B_REFRESH_CONVERT           4005
#define IDS_EDIT_RESULT_3               4005
#define IDD_NOTICE                      4005
#define IDC_B_DELETE                    4006
#define IDS_EDIT_RESULT_4               4006
#define IDD_CHARMACRO                   4006
#define IDC_CB_CONVERT_TYPE1            4007
#define IDS_EDIT_RESULT_FAILURE         4007
#define IDC_CB_CONVERT_PHYSICAL         4007
#define IDD_GUILD                       4007
#define IDC_CB_CONVERT_SOCKET           4008
#define IDC_S_CHAR_GRID_PLACE           4008
#define IDS_SKILL_LEARN_ALREADY         4008
#define IDD_ABOUT                       4008
#define IDC_CB_CONVERT_SPIRIT_STONE     4009
#define IDS_SKILL_LEARN_SUCCESS         4009
#define IDC_CB_CONVERT_STONE            4010
#define IDS_SKILL_LEARN_FAILURE         4010
#define IDC_B_CONVERT                   4011
#define IDS_SKILL_UPGRADE_FAILURE       4011
#define IDC_CB_CREATE_WEAPON            4012
#define IDC_CB_CREATE_FIRST             4012
#define IDS_SKILL_UPGRADE_SUCCESS       4012
#define IDC_CB_CREATE_ARMOR             4013
#define IDC_CB_CREATE_SECOND            4013
#define IDS_ITEM_CREATE_SUCCESS         4013
#define IDC_CB_CREATE_QUEST             4014
#define IDS_ITEM_CREATE_FAILURE         4014
#define IDC_CB_CREATE_USABLE            4015
#define IDC_CB_CREATE_THIRD             4015
#define IDS_ITEM_CONVERT_SUCCESS_PHY    4015
#define IDC_B_CREATE                    4016
#define IDS_ITEM_CONVERT_SUCCESS_SOCKET 4016
#define IDS_ITEM_CONVERT_SUCCESS_STONE  4017
#define IDC_E_CREATE_COUNT              4018
#define IDS_ITEM_CONVERT_FAILURE        4018
#define IDC_S_CREATE_TID                4019
#define IDS_ITEM_DELETE_SUCCESS         4019
#define IDC_S_CREATE_TID2               4020
#define IDS_ITEM_DELETE_FAILURE         4020
#define IDC_E_REMAIN_POINT              4021
#define IDS_MAIN_CURRENT_USER           4021
#define IDC_CB_COMBAT                   4022
#define IDS_NOTICE_ASK_APPLY            4022
#define IDC_B_LEVEL_UP                  4022
#define IDC_B_LEARN                     4023
#define IDS_ITEM_OPTION_ADD_SUCCESS     4023
#define IDC_CB_ENFORCE                  4024
#define IDS_ITEM_OPTION_REMOVE_SUCCESS  4024
#define IDC_B_LEVEL_DOWN                4024
#define IDC_CB_PRIVATE                  4025
#define IDS_ITEM_CREATE_OWNER           4025
#define IDC_E_PRODUCT_LEVEL             4025
#define IDC_CB_PASSIVE                  4026
#define IDS_ITEM_CREATE_ACCNAME_CONFIRM 4026
#define IDC_B_PRODUCT_EXP_CHANGE        4026
#define IDC_CB_PRODUCT                  4027
#define IDS_ITEM_CREATE_INVEN_FULL      4027
#define IDS_ITEM_DELETE_CONFIRM         4028
#define IDS_ITEM_REFRESH                4029
#define IDC_B_POINT_UP                  4030
#define IDS_EDIT_CONFIRM                4030
#define IDC_B_POINT_DOWN                4031
#define IDS_EDIT_DB_CHAR                4031
#define IDC_B_ROLLBACK                  4032
#define IDS_EDIT_DB_REFRESH             4032
#define IDC_TAB_SKILL                   4033
#define IDS_ITEM_CONVERT_CONFIRM        4033
#define IDS_ITEM_CONVERT_WARNING        4034
#define IDC_TAB_MESSAGE                 4035
#define IDS_ITEM_INIT_SOCKET            4035
#define IDC_L_ITEM_CONVERT              4036
#define IDS_NOT_PRIVILEGE               4036
#define IDC_SL_ALPHA                    4037
#define IDS_MAIN_SERVER                 4037
#define IDC_CH_USE_LAYERED              4038
#define IDS_ITEM_INSERT_DELETE_REASON   4038
#define IDC_S_ALPHA                     4039
#define IDS_ITEM_INSERT_CREATE_REASON   4039
#define IDC_E_NOTICE                    4040
#define IDC_CH_USE_LAYERED2             4040
#define IDC_CH_SAVE_WHISPER             4040
#define IDS_GUILD_DESTROY_CONFIRM       4040
#define IDC_B_SEND                      4041
#define IDS_GUILD_LEAVE_ONLY_MEMBER     4041
#define IDC_E_NOTICE_TEXT               4042
#define IDS_GUILD_MEMBER_FORCED_LEAVE   4042
#define IDC_L_NOTICE                    4043
#define IDS_GUILD_CHANGE_MASTER         4043
#define IDC_B_PLAY                      4044
#define IDS_GUILD_CHANGE_MASTER_CONFIRM 4044
#define IDC_B_PAUSE                     4045
#define IDS_GUILD_CHANGE_NOTICE_CONFIRM 4045
#define IDC_B_STOP                      4046
#define IDS_ITEM_UPDATE_CONFIRM         4046
#define IDC_B_SAVE                      4047
#define IDS_LOGIN_TIME                  4047
#define IDC_B_SAVE_AS                   4048
#define IDS_CHARNAME                    4048
#define IDC_B_LOAD                      4049
#define IDS_ACCNAME                     4049
#define IDC_B_HELP                      4050
#define IDC_B_ADD                       4050
#define IDS_RACE                        4050
#define IDC_E_NOTICE_FILENAME           4051
#define IDC_B_REMOVE                    4051
#define IDS_CLASS                       4051
#define IDC_S_CURRENT_USER              4052
#define IDS_SERVER                      4052
#define IDC_CH_SOS                      4053
#define IDS_LEVEL                       4053
#define IDC_L_MACRO                     4054
#define IDS_GUILD_NOTICE_EXCEED_MAX_LENGTH 4054
#define IDC_B_RUN_MACRO                 4055
#define IDS_EXP                         4055
#define IDS_CRIMINAL_STATUS             4056
#define IDC_S_MACRO_FILENAME            4057
#define IDS_MURDERER_POINT              4057
#define IDC_L_OPTION_ADDED              4058
#define IDS_RCF                         4058
#define IDC_L_OPTION_ALL                4059
#define IDS_RMF                         4059
#define IDC_E_OPTION_DESC               4060
#define IDS_CON                         4060
#define IDC_B_OPTION_ADD                4061
#define IDS_STR                         4061
#define IDC_B_OPTION_REMOVE             4062
#define IDC_CB_GUILD_SEARCH_TYPE        4062
#define IDS_INT                         4062
#define IDC_E_GUILD_SEARCH_FIELD        4063
#define IDS_WIS                         4063
#define IDC_L_SKILL_ADDED               4063
#define IDC_S_GUILD_COUNT               4064
#define IDS_DEX                         4064
#define IDC_L_SKILL_ALL                 4064
#define IDC_S_GUILD_COUNT2              4065
#define IDC_S_GUILD_MEMBER_COUNT        4065
#define IDS_CHA                         4065
#define IDC_B_SKILL_ADD                 4065
#define IDC_B_GUILD_INFO_REFRESH        4066
#define IDS_NORMAL_ATTACK               4066
#define IDC_B_SKILL_REMOVE              4066
#define IDC_B_GUILD_SEARCH              4067
#define IDS_DEFENSE                     4067
#define IDC_E_GUILD_NOTICE              4068
#define IDS_SKILL_BLOCK                 4068
#define IDS_PHYSICAL_RES                4069
#define IDC_S_GUILD_DATA                4070
#define IDS_AR                          4070
#define IDC_LV_MEMBER                   4071
#define IDS_ADDITIONAL_AR               4071
#define IDC_LV_MEMBER2                  4072
#define IDC_LV_GUILD                    4072
#define IDC_S_ITEM_OWNER                4072
#define IDS_BLOCK                       4072
#define IDC_EDIT1                       4073
#define IDC_E_CREATE_TID                4073
#define IDS_EVADE                       4073
#define IDC_E_WC_CONTENT                4073
#define IDC_TITLE_QUEST_CHECK_VALUE     4073
#define IDC_CB_ITEM_LIST                4074
#define IDS_ATTACK_SPEED                4074
#define IDC_CHK_USING                   4075
#define IDS_MOVE_SPEED                  4075
#define IDC_E_R_TIME_DAY                4076
#define IDS_CHAR_CREATION_DATE          4076
#define IDC_S_REMAIN_TIME               4077
#define IDS_LAST_IP                     4077
#define IDS_EDIT_EXP                    4078
#define IDC_S_R_TIME_DATE               4079
#define IDS_ATTACK_POWER                4079
#define IDC_E_R_TIME_HOUR               4080
#define IDS_RES_POWER                   4080
#define IDC_S_R_TIME_HOUR               4081
#define IDS_PLAY_TIME                   4081
#define IDC_E_R_TIME_MIN                4082
#define IDS_POSITION                    4082
#define IDC_S_R_TIME_MIN                4083
#define IDS_IP                          4083
#define IDC_E_R_TIME_SEC                4084
#define IDS_GUILD_ID                    4084
#define IDC_S_R_TIME_SEC                4085
#define IDS_INVENTORY                   4085
#define IDC_CB_E_DATE_YEAR              4086
#define IDS_BANK                        4086
#define IDC_CB_E_DATE_MONTH             4087
#define IDS_DELETE_REASON               4087
#define IDC_CB_E_DATE_DAY               4088
#define IDS_DELETE_REPAY                4088
#define IDC_CB_E_DATE_HOUR              4089
#define IDS_CREATE_REASON               4089
#define IDC_CB_E_DATE_MIN               4090
#define IDS_CREATE_REWARD               4090
#define IDC_B_ITEM_SEARCH               4091
#define IDS_ITEM_POS                    4091
#define IDC_B_ITEM_UPDATE               4092
#define IDS_ITEM_NAME                   4092
#define IDC_CB_EXPIRE_DATE_DEFAULT      4093
#define IDS_ITEM_COUNT                  4093
#define IDC_CB_DELETE_REASON            4094
#define IDS_ITEM_CONVERT                4094
#define IDC_CB_CREATE_REASON            4095
#define IDS_ITEM_SOCKET                 4095
#define IDC_B_GUILD_DESTROY             4096
#define IDS_ITEM_RANK                   4096
#define IDC_B_MEMBER_FORCED_LEAVE       4097
#define IDC_E_DURABILITY                4097
#define IDS_ITEM_USE                    4097
#define IDC_B_CHANGE_MASTER             4098
#define IDC_S_DURABILITY                4098
#define IDS_ITEM_REMAIN_TIME            4098
#define IDC_E_MAX_DURABILITY            4098
#define IDC_B_CHANGE_NOTICE             4099
#define IDS_ITEM_EXPIRE_DATE            4099
#define IDS_ITEM_USE_COUNT              4100
#define IDS_ITEM_EQUIP                  4101
#define IDC_CB_SKILL_TYPE               4101
#define IDS_ITEM_INVENTORY              4102
#define IDC_LV_OWN_SKILL                4102
#define IDS_ITEM_AUCTION                4103
#define IDC_CB_SKILL_CATEGORY           4103
#define IDS_ITEM_CASH_INVEN             4104
#define IDC_LV_ALL_SKILL                4104
#define IDS_ITEM_SOCKETED_ITEM          4105
#define IDC_B_INIT_SKILL_ALL            4105
#define IDS_ITEM_PHYSICAL_CONVERT       4106
#define IDC_B_INIT_SKILL_SPECIFIC       4106
#define IDS_ITEM_SPIRIT_STONE           4107
#define IDS_ITEM_RUNE                   4108
#define IDS_ITEM_SOLD_OUT               4109
#define IDC_CK_OWN_SKILL_ALL            4109
#define IDS_ITEM_PAUSED                 4110
#define IDC_CK_ALL_SKILL_ALL            4110
#define IDS_TIME_DAY                    4111
#define IDC_S_SKILL_CHARNAME            4111
#define IDS_EQUIP_RIGHT_HAND            4112
#define IDC_B_WC_REFRESH                4112
#define IDS_EQUIP_LEFT_HAND             4113
#define IDC_B_WC_DELETE                 4113
#define IDC_CB_SKILLPLUS                4113
#define IDS_EQUIP_HEAD                  4114
#define IDS_EQUIP_CHEST                 4115
#define IDS_EQUIP_PANTS                 4116
#define IDS_EQUIP_FEET                  4117
#define IDS_EQUIP_ARM                   4118
#define IDS_EQUIP_NECKLACE              4119
#define IDS_EQUIP_RING                  4120
#define IDS_EQUIP_STANDARD              4121
#define IDS_EQUIP_RIDE                  4122
#define IDS_SET_ON_INVENTORY            4123
#define IDS_MAX_OPTION                  4124
#define IDD_WC                          4124
#define IDS_CANNOT_ADD_OPTION_TO_LOGOUT_USER 4125
#define IDS_NOT_SELECTED_ITEM           4126
#define IDS_NOT_SUPPORTED_REMOVE_OPTION 4127
#define IDS_THIS_PLACE_NOTICE           4128
#define IDS_COLUMN                      4129
#define IDS_DATA                        4130
#define IDS_GUILD_BASIC                 4131
#define IDS_GUILD_MASTER_ID             4132
#define IDC_BUTTON1                     4132
#define IDC_B_OPT_SEARCH                4132
#define IDC_TITLE_QUEST_ADD             4132
#define IDS_GUILD_RANK                  4133
#define IDC_LIST1                       4133
#define IDC_B_SKILL_SEARCH              4133
#define IDC_TITLE_LIST                  4133
#define IDS_GUILD_CREATION_DATE         4134
#define IDC_LIST2                       4134
#define IDC_L_QUEST                     4134
#define IDC_TITLE_ALL_LIST              4134
#define IDS_GUILD_PASSWORD              4135
#define IDC_LIST3                       4135
#define IDC_TITLE_QUEST_LIST            4135
#define IDS_GUILD_MEMBER_COUNT          4136
#define IDC_LIST4                       4136
#define IDC_TITLE_ADD                   4136
#define IDS_GUILD_BATTLE                4137
#define IDC_LIST5                       4137
#define IDS_GUILD_BATTLE_STATUS         4138
#define IDC_LIST6                       4138
#define IDC_LISTVILLAGE                 4138
#define IDS_GUILD_BATTLE_RECORD         4139
#define IDC_USER_REQUEST                4139
#define IDS_GUILD_ENEMY_GUILD_ID        4140
#define IDC_STATIC_ALLUSER              4140
#define IDS_GUILD_BATTLE_ACCEPT_TIME    4141
#define IDC_STATIC_MAINUSER             4141
#define IDS_GUILD_BATTLE_START_TIME     4142
#define IDC_STATIC_DUNGEONUSER          4142
#define IDS_GUILD_BATTLE_DURATION       4143
#define IDC_STATIC_BATTLEUSER           4143
#define IDS_GUILD_BATTLE_SCORE          4144
#define IDC_STATIC_SPIRITUSER           4144
#define IDS_GUILD_BATTLE_ENEMY_SCORE    4145
#define IDC_STATIC_VILLAGEUSER          4145
#define IDS_GUILD_MASTER                4146
#define ST                              4146
#define IDS_GUILD_MEMBER                4147
#define IDC_LISTMAIN                    4147
#define IDS_GUILD_JOIN_REQUEST          4148
#define IDC_LISTDUNGEON                 4148
#define IDS_GUILD_LEAVE_REQUEST         4149
#define IDC_LISTBATTLE                  4149
#define IDS_GUILD_LEAVE_MEMBER_SUCCESS  4150
#define IDC_LISTSPIRIT                  4150
#define IDS_GUILD_LEAVE_MEMBER_FAILED   4151
#define IDS_GUILD_DESTROY_SUCCESS       4152
#define IDS_GUILD_DESTROY_FAILED        4153
#define IDC_OPT_SEARCH_BOX              4153
#define IDS_GUILD_CHANGE_MASTER_SUCCESS 4154
#define IDC_SKILL_SEARCH_BOX            4154
#define IDC_QUEST_DELETE                4154
#define IDS_GUILD_CHANGE_MASTER_FAILED  4155
#define IDC_QUEST_VALUE_EDIT            4155
#define IDS_GUILD_CHANGE_NOTICE_SUCCESS 4156
#define IDC_TITLE_USE                   4156
#define IDS_GUILD_CHANGE_NOTICE_FAILED  4157
#define IDC_TITLE_DELETE                4157
#define IDS_GUILD_BATTLE_STATUS_NONE    4158
#define IDC_QUEST_COMPLETE              4158
#define IDS_GUILD_BATTLE_STATUS_READY   4159
#define IDS_GUILD_BATTLE_STATUS_BATTLE  4160
#define IDS_WHISPER                     4161
#define IDS_SEARCH_CHARNAME             4162
#define IDS_SEARCH_ACCNAME              4163
#define IDS_LOGIN_STATUS                4164
#define IDS_ONLINE                      4165
#define IDS_OFFLINE                     4166
#define IDS_SKILL_NAME                  4167
#define IDS_BANK_ITEM_DELETE_CONFIRM    4168
#define IDS_BANK_ITEM_DELETE_CONFIRM2   4169
#define IDS_SKILL_MASTERY_0             4170
#define IDS_SKILL_MASTERY_1             4171
#define IDS_SKILL_MASTERY_2             4172
#define IDS_SKILL_MASTERY_3             4173
#define IDS_SKILL_PRODUCT               4174
#define IDS_SKILL_NOT_ENOUGH_POINT      4175
#define IDS_DESC                        4176
#define IDS_SKILL_CONFIRM_1             4177
#define IDS_SKILL_CONFIRM_2             4178
#define IDS_SKILL_CONFIRM_3             4179
#define IDS_SKILL_CONFIRM_4             4180
#define IDS_SKILL_CONFIRM_5             4181
#define IDS_SKILL_CONFIRM_6             4182
#define IDS_SKILL_PRODUCT_COMPOSE       4183
#define IDS_SKILL_DISABLE_BY_ONLINE     4184
#define IDS_SKILL_DISABLE_BY_COMPOSE    4185
#define IDS_SKILL_EXP_ERROR             4186
#define IDS_WC_DEFAULT_TEXT             4187
#define IDS_WC_MONEY                    4188
#define IDS_WC_DELETE_CONFIRM           4189
#define IDS_ITEM_MAILBOX                4190
#define IDS_SKILL_MASTERY_4             4191
#define IDS_ITEM_INVENTORY_PET          4192
#define IDS_GUILD_SUBMASTER             4193
#define IDS_NOT_EXIST_QUEST             4194
#define IDS_QUEST_ID                    4195
#define IDS_QUEST_PARAM1                4196
#define IDS_QUEST_PARAM2                4197
#define IDS_QUEST_NPCNAME               4198
#define IDS_QUEST_NAME                  4199
#define IDS_QUEST_SCENARIO_NAME         4200
#define IDS_STRING4201                  4201
#define IDS_MAX_SKILL                   4201
#define IDS_TITLE_ID                    4202
#define IDS_TITLE_USE                   4203
#define IDS_TITLE_NAME                  4204
#define IDS_TITLE_CHECK_TYPE            4205
#define IDS_TITLE_CHECK_VALUE           4206
#define IDS_TITLE_CUR_VALUE             4207
#define IDS_TITLE_USING_STATE           4208
#define IDS_TITLE_NOT_EDIT              4209
#define IDD_USER                        4888
#define IDD_QUEST                       4889
#define IDD_CHARTITLE                   4890
#define ID_32771                        32771
#define ID_32772                        32772
#define ID_32773                        32773
#define ID_32774                        32774
#define ID_32775                        32775
#define ID_32776                        32776
#define ID_32777                        32777
#define ID_32778                        32778
#define ID_Menu                         32779
#define ID__                            32780
#define ID__32781                       32781
#define ID_OPTION                       32783
#define IDM_ABOUT                       32784
#define ID_32785                        32785

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        4195
#define _APS_NEXT_COMMAND_VALUE         32786
#define _APS_NEXT_CONTROL_VALUE         4155
#define _APS_NEXT_SYMED_VALUE           4000
#endif
#endif
