#pragma once 

enum POLICYNAME
{
	POLICY_EXPIRE_TIME = 1,
	POLICY_RECODE_FIND_TIME		//是否在调用find方法时，记录最后访问时间
};

enum RETURNCODE
{
	CACHE_RETURN_FAILED = -1,
	CACHE_RETURN_SUCCESS = 0,
	CACHE_RETURN_NOSUCH_GROUP,
	CACHE_RETURN_CANNOT_CREATE_GUID,
	CACHE_RETURN_NOSUCH_RECORD, 
	CACHE_RETURN_PARAMETER_ERROR,
	CACHE_RETURN_EXCEPTION,
	CACHE_RETURN_FULL
};

#define DEFAULT_EXPIRE_TIME 120
#define MIN_EXPIRE_TIME 10
#define MAX_EXPIRE_TIME 360000 // 100HOURS

#define CACHE_CAPABILITY 10000

#define SINGLE_USERKEY false
#define MULTI_USERKEY true