//
// Generated by Microsoft (R) D3DX9 Shader Assembler
//
//  Source: EnvMapPShader.psh
//  Flags: 
//


const DWORD dwEnvMapPixelShader[] =
{
    0xffff0101, 0x00000042, 0xb00f0000, 0x00000042, 0xb00f0001, 0x00000005, 
    0x800f0000, 0xb0e40000, 0x90e40000, 0x00000005, 0x800f0001, 0xb0e40001, 
    0xb0ff0001, 0x00000004, 0x80070000, 0x80e40001, 0xa0e40000, 0x80e40000, 
    0x0000ffff
};
