//
// Generated by Microsoft (R) D3DX9 Shader Assembler
//
//  Source: EnvMapNoBaseTexturePShader.psh
//  Flags: 
//


const DWORD dwEnvMapNoBaseTexturePixelShader[] =
{
    0xffff0101, 0x00000042, 0xb00f0000, 0x00000005, 0x800f0000, 0xb0e40000, 
    0xb0ff0000, 0x00000004, 0x80070000, 0x80e40000, 0xa0e40000, 0x90e40000, 
    0x40000001, 0x80080000, 0x90ff0000, 0x0000ffff
};
