#if !defined(__AGPMQUESTSTRINGTABLE_H__)
#define __AGPMQUESTSTRINGTABLE_H__

// commented by ST, 더이상 사용안하는듯

// Quest Template
//#define AGPMQUESTSTRING_QUEST			"Quest"
//#define AGPMQUESTSTRING_CATEGORY		"카테고리"
//
//#define AGPMQUESTSTRING_DEFAULT_INFO	"기본 정보"
//#define AGPMQUESTSTRING_NAME			"이름"
//#define AGPMQUESTSTRING_QUEST_TID		"퀘스트 TID"
//#define AGPMQUESTSTRING_ITEM_TID		"아이템 TID"
//#define AGPMQUESTSTRING_MONSTER_TID		"몬스터 TID"
//#define AGPMQUESTSTRING_SKILL_TID		"스킬 TID"
//#define AGPMQUESTSTRING_DBID			"DBID"
//
//#define AGPMQUESTSTRING_START_CONDITION "시작 조건"
//#define AGPMQUESTSTRING_LEVEL			"레벨"
//
//#define AGPMQUESTSTRING_RACE			"종족"
//#define AGPMQUESTSTRING_EMPTY			"<empty>"
//#define AGPMQUESTSTRING_HUMAN			"휴먼"
//#define AGPMQUESTSTRING_ORC				"오크"
//
//#define AGPMQUESTSTRING_CLASS			"클래스"
//#define AGPMQUESTSTRING_KNIGHT			"전사"
//#define AGPMQUESTSTRING_RANGER			"궁수"
//#define AGPMQUESTSTRING_MONK			"몽크"
//#define AGPMQUESTSTRING_MAGE			"마법사"
//
//#define AGPMQUESTSTRING_GENDER			"성별"
//#define AGPMQUESTSTRING_MALE			"남성"
//#define AGPMQUESTSTRING_FEMALE			"여성"
//
//#define AGPMQUESTSTRING_ITEM			"아이템"
//#define AGPMQUESTSTRING_SKILL			"스킬"
//
//#define AGPMQUESTSTRING_PRE_START		"퀘스트 줄때"
//
//#define AGPMQUESTSTRING_DIALOG			"대화"
//#define AGPMQUESTSTRING_ACCEPT_TEXT		"퀘스트 진행여부 확인 대화"
//#define AGPMQUESTSTRING_INCOMPLETE_TEXT	"퀘스트 미완료 대화"
//#define AGPMQUESTSTRING_COMPLETE_TEXT	"퀘스트 완료 대화"
//
//#define AGPMQUESTSTRING_SUMMARY			"완료 조건 요약"
//#define AGPMQUESTSTRING_SUMMARY_ITEM	"아이템 요약"
//#define AGPMQUESTSTRING_SUMMARY_LEVEL	"레벨 요약"
//#define AGPMQUESTSTRING_SUMMARY_MONEY	"겔드 요약"
//#define AGPMQUESTSTRING_SUMMARY_MONSTER	"몬스터 요약"
//
//#define AGPMQUESTSTRING_DIALOG_DESCRIPTION "New Line : </n>, 캐릭터 이름 : </이름>"
//
//#define AGPMQUESTSTRING_MONEY			"겔드"
//#define AGPMQUESTSTRING_EXPERIENCE		"경험치"
//#define AGPMQUESTSTRING_MONSTER			"몬스터"
//#define AGPMQUESTSTRING_NEXT_QUEST		"다음 퀘스트"
//#define AGPMQUESTSTRING_PREV_QUEST		"이전 퀘스트"
//
//#define AGPMQUESTSTRING_COMPLETE_CONDITION "완료 조건"
//#define AGPMQUESTSTRING_RESULT			"보상"
//
//#define AGPMQUESTSTRING_EVALUATION		"평가"
//#define AGPMQUESTSTRING_COUNT			"수량"
//
//#define AGPMQUESTSTRING_USING			"사용"
//
//#define AGPMQUESTSTRING_QUEST_TYPE		"퀘스트 종류"
//
//#define AGPMQUESTSTRING_SCENARIO		"시나리오"
//#define AGPMQUESTSTRING_NORMAL			"일반"
//#define AGPMQUESTSTRING_TUTORIAL		"튜토리얼"
//#define AGPMQUESTSTRING_LEVELUP			"승단"
//
//// Quest Group
//#define AGPMQUESTSTRING_QUEST_GROUP		"퀘스트 그룹"
//#define AGPMQUESTSTRING_GROUP_ID		"그룹 ID"
//#define AGPMQUESTSTRING_GRANT_GROUP		"부여 그룹"
//#define AGPMQUESTSTRING_ESTIMATE_GROUP	"평가 그룹"
//
//static CHAR* RaceStringTable[] = 
//{
//	AGPMQUESTSTRING_EMPTY,
//	AGPMQUESTSTRING_HUMAN,
//	AGPMQUESTSTRING_ORC
//};
//
//static CHAR* ClassStringTable[] =
//{
//	AGPMQUESTSTRING_EMPTY,
//	AGPMQUESTSTRING_KNIGHT,
//	AGPMQUESTSTRING_RANGER,
//	AGPMQUESTSTRING_MONK,
//	AGPMQUESTSTRING_MAGE
//};
//
//static CHAR* GenderStringTable[] =
//{
//	AGPMQUESTSTRING_EMPTY,
//	AGPMQUESTSTRING_MALE,
//	AGPMQUESTSTRING_FEMALE
//};
//
//static CHAR* EvaluationTable[] = 
//{
//	"<",
//	"<=",
//	">",
//	">=",
//	"==",
//};
//
//static CHAR* QuestTypeTable[] =
//{
//	AGPMQUESTSTRING_EMPTY,
//	AGPMQUESTSTRING_SCENARIO,
//	AGPMQUESTSTRING_NORMAL,
//	AGPMQUESTSTRING_TUTORIAL,
//	AGPMQUESTSTRING_LEVELUP
//};

#endif