
//{{AFX_CODEJOCK_PRIVATE

#ifndef _XTP_SCHEMA_CURRENT

#define _XTP_SCHEMA_71  (0x1)
#define _XTP_SCHEMA_80  (0x2)
#define _XTP_SCHEMA_85  (0x3)
#define _XTP_SCHEMA_86  (0x4)
#define _XTP_SCHEMA_861 (0x5)
#define _XTP_SCHEMA_87  (0x6)
#define _XTP_SCHEMA_875 (0x7)
#define _XTP_SCHEMA_95  (0x8)
#define _XTP_SCHEMA_97  (0x9)
#define _XTP_SCHEMA_98  (0x10)
#define _XTP_SCHEMA_100 (0x11)
#define _XTP_SCHEMA_103 (0x12)
#define _XTP_SCHEMA_104 (0x14)
#define _XTP_SCHEMA_1041 (0x15)
#define _XTP_SCHEMA_1042 (0x16)
#define _XTP_SCHEMA_110 (0x17)

#define _XTP_SCHEMA_CURRENT _XTP_SCHEMA_110
#endif

//}}AFX_CODEJOCK_PRIVATE
