//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AgcmDialogs.rc
//
#define IDC_BUTTON_UDA_APPLY            3
#define IDC_BUTTON_LA_REMOVE            3
#define ID_BUTTON_CHAR_ANIM_START_ANIMATION 3
#define ID_NEW_BLOCKING                 3
#define ID_FILE_LIST_FIND               3
#define IDC_BUTTON_INSERT_LODDATA       3
#define IDC_BUTTON_OL_ADD               3
#define IDC_BUTTON_APPLY_SKILL          3
#define IDC_BUTTON_LA_ADD               4
#define ID_BUTTON_CHAR_ANIM_START_ANIM_TYPE 4
#define IDC_BUTTON_REMOVE_LODDATA       4
#define IDC_BUTTON_OL_REMOVE            4
#define ID_BUTTON_CHAR_ANIM_SET_PROPERTY 5
#define IDC_BUTTON_CHANGE_LODDATA       5
#define ID_BUTTON_CHAR_ANIM_INSERT      6
#define IDC_BUTTON_CHANGE_DISTANCE      6
#define ID_BUTTON_CHAR_ANIM_SET_SUB_ANIM 7
#define IDC_BUTTON_APPLY_PRE_LOD        7
#define ID_BUTTON_CHAR_ANIM_REMOVE      8
#define IDC_BUTTON_INSERT_DUMMY         8
#define ID_BUTTON_CHAR_ANIM_REMOVE_ALL  9
#define ID_BUTTON_CHAR_ANIM_SET_ATTACHED_DATA 10
#define IDC_EDIT_BINDING_NAME           1000
#define IDD_DIALOG_BINDING              1000
#define IDC_CHAR_RACE_TYPE              1000
#define IDC_FILE_LIST                   1000
#define IDC_EDIT_RADIUS                 1001
#define IDC_R_TEXT                      1001
#define IDC_CHAR_CLASS_TYPE             1001
#define IDD_FILE_LIST_FIND              1001
#define IDC_EDIT_NAME                   1001
#define IDC_EDIT_EL_FIND                1002
#define IDC_G_TEXT                      1002
#define IDC_EDIT_FIND                   1002
#define IDC_EDIT_LEVEL                  1002
#define IDC_COMBO_BINDING_TYPE          1003
#define IDC_EDIT_SKILL_NAME             1003
#define IDC_COMBO_RACE_CLASS_TYPE       1005
#define IDC_LIST_SKILL_LIST             1005
#define IDC_BUTTON_SKILL_ADD            1006
#define IDC_COMBO_REGION_NAME           1007
#define IDC_BUTTON_SKILL_DELETE         1007
#define IDC_EDIT_POSITION               1008
#define IDC_TARGET_POS_X                1009
#define IDC_BUTTON_POS_ADD              1009
#define IDC_TARGET_POS_Y                1010
#define IDC_BUTTON_POS_DELETE           1010
#define IDC_TARGET_POS_Z                1011
#define IDC_LIST_POSITION               1011
#define IDC_CHECK_RANDOM_POS            1012
#define IDC_TARGET_BASE_ID              1013
#define IDC_COMBO_ACTIVE_CONDITION      1013
#define IDC_TARGET_BASE_TYPE            1014
#define IDC_EDIT_MIN_ACTIVE_TIME        1014
#define IDC_TARGET_RADIUS_MIN           1015
#define IDC_EDIT_MAX_ACTIVE_TIME        1015
#define IDC_TARGET_RADIUS_MAX           1016
#define IDC_COMBO_REACTIVE_CONDITION    1016
#define IDC_TELEPORT_TYPE_POS           1017
#define IDC_COMBO_USE_CONDITION         1017
#define IDC_EDIT_USE_INTERVAL           1018
#define IDC_TELEPORT_TYPE_BASE          1019
#define IDC_AI2_AggressiveEdit          1033
#define IDC_Check_NPC                   1034
#define IDC_Check_FixedNPC              1035
#define IDC_EFFECT_LIST                 1192
#define IDC_BUTTON_SET_BLENDING_ANIMATION 1501
#define IDC_BUTTON_SET_SOUND_DATA       1502
#define IDC_BUTTON_SET_SUB_ANIMATION    1503
#define IDC_COMBO_CONDITION             1504
#define IDC_EDIT_ACTIVE_RATE            1505
#define IDC_EDIT_BLENDING_ANIMATION     1506
#define IDC_EDIT_CUSTOM_TYPE            1507
#define IDC_EDIT_POINT                  1508
#define IDC_EDIT_SUB_ANIMATION          1509
#define IDC_LIST_SOUND                  1510
#define IDD_CHAR_ANIM_ATTACHED_DATA     1511
#define IDD_CHAR_ANIM_ATTACHED_SOUND_DATA 1512
#define IDD_CHARACTER_SKILL             4000
#define IDD_SKILL_TEMPLATE_LIST         4001
#define IDC_SKILL_DATA_INDEX            4001
#define IDD_EDIT_DLG                    4002
#define IDC_EDIT_SKILL_DATA_ANIMATION_NAME 4002
#define IDC_BUTTON_SKILL_DATA_SET_ANIMATION 4003
#define IDD_DEF_SKILL                   4004
#define IDC_BUTTON_SKILL_DATA_SET_EFFECT 4004
#define IDD_USABLE_SKILL_LIST           4005
#define IDC_LIST_SKILL_TEMPLATE         4005
#define IDC_EDIT_SKILL_DATA_SKILL_NAME  4005
#define IDC_BUTTON_STL_FIND             4006
#define IDD_SKILL_TEMPLATE              4006
#define IDC_BUTTON_SKILL_DATA_SET_SKILL_NAME 4006
#define IDC_EDIT_                       4007
#define IDC_BUTTON_START_ANIMATION      4007
#define IDD_CHAR_SKILL                  4007
#define IDC_COMBO_DEF_SKILL_INDEX       4008
#define IDC_EDIT_DEFAULT_SKILL_NAME     4009
#define IDC_BUTTON_SKILL_DATA_SET_DEF_SKILL 4009
#define IDC_BUTTON_SKILL_DATA_SET_DEFAULT_SKILL_NAME 4010
#define IDC_BUTTON_SKILL_DATA_REMOVE    4010
#define IDC_LIST_USABLE_SKILL           4011
#define IDC_EDIT_SMALL_SKILL_TEXTURE    4011
#define IDC_BUTTON_FIND_USABLE_SKILL    4012
#define IDC_BUTTON_SET_SMALL_SKILL_TEXTURE 4012
#define IDC_BUTTON_SKILL_DATA_SET_ANIM_PROPERTY 4012
#define IDC_EDIT_UNABLE_SKILL_TEXTURE   4013
#define IDC_EDIT_SKILL_TEXTURE          4014
#define IDC_BUTTON_START_EFFECT         4014
#define IDC_BUTTON_SET_SKILL_TEXTURE    4015
#define IDC_BUTTON_DELETE_SKILL_TEXTURE 4016
#define IDC_COMBO_EQUIP_TYPE            4016
#define IDC_BUTTON_SET_UNABLE_SKILL_TEXTURE 4017
#define IDC_TREE_SKILL                  4017
#define IDC_BUTTON_DELETE_SMALL_SKILL_TEXTURE 4018
#define IDC_BUTTON_DELETE_UNABLE_SKILL_TEXTURE 4019
#define IDC_EDIT_ANIMATION_NAME         4019
#define IDC_BUTTON_SET_ANIMATION        4022
#define IDC_BUTTON_SET_ANIM_PROPERTY    4023
#define IDC_COMBO_WEAPON_TYPE           4024
#define IDC_SLIDER_ANIMATION            4036
#define IDC_EDIT_CUR_ANIM               4037
#define IDC_BUTTON_OPEN_EFFECT_LIST     4038
#define IDC_BUTTON_OPEN_CONDITION_LIST  4039
#define IDC_BUTTON_ANIM_PLAY            4040
#define IDC_BUTTON_ANIM_STOP            4041
#define IDC_EDIT_SKILL_INFO             4042
#define IDC_BUTTON_OPEN_STATUS_LIST     4043
#define IDC_BUTTON_OPEN_CUST_DATA_LIST  4044
#define IDC_BUTTON_OPEN_ROTATION_DLG    4045
#define IDC_BUTTON_CHANGE_SKILL_INFO    4046
#define IDC_BUTTON_ADD_EFFECT           4047
#define IDC_BUTTON_REMOVE_EFFECT        4048
#define IDC_BUTTON_COPY_EFFECT          4049
#define IDD_CHARACTER                   4400
#define IDD_CHAR_TEMPLATE_LIST          4403
#define IDC_LIST_CHAR_TEMPLATE          4404
#define IDC_EDIT_ARMOUR_CLUMP           4406
#define IDC_BUTTON_SET_ARMOUR_CLUMP     4407
#define IDC_EDIT_CHARACTER_HEIGHT       4408
#define IDC_BUTTON_SET_CHARACTER_HEIGHT 4409
#define IDC_EDIT_CHARACTER_HIT_RANGE    4410
#define IDC_EDIT_CHARACTER_HEIGHT2      4411
#define IDC_EDIT_CHARACTER_DEPTH        4411
#define IDC_BUTTON_SET_CHARACTER_HIT_RANGE 4412
#define IDC_EDIT_PICK_ATOMIC            4413
#define IDC_BUTTON_SET_PICK_ATOMIC      4414
#define IDC_BUTTON_REMOVE_ARMOUR_CLUMP  4415
#define IDC_BUTTON_REMOVE_PICK_ATOMIC   4416
#define IDD_CHAR_CUSTOM_FLAGS           4417
#define IDC_EDIT_B_SPHERE_CENTER_X      4417
#define IDC_CHECK_PLAY_MOVING_SOUND     4418
#define IDC_EDIT_B_SPHERE_CENTER_Y      4418
#define IDC_EDIT_B_SPHERE_CENTER_Z      4419
#define IDC_EDIT_B_SPHERE_RADIUS        4420
#define IDC_BUTTON_GENERATE_B_SPHERE    4421
#define IDC_BUTTON_SET_CHARACTER_DEPTH  4422
#define IDC_EDIT_CHARACTER_SCALE        4423
#define IDD_EVENT_PRODUCT_DLG           5000
#define IDC_COMBO1                      5000
#define IDC_COMBO_CATEGORY              5000
#define IDC_FACE_ATOMIC                 5000
#define IDC_COMBO_RIDABLE_MATERIAL_TYPE 5000
#define IDC_COMBO_CAM_COLLISION         5000
#define IDD_TELEPORT_TARGET             5001
#define IDC_TREE1                       5001
#define IDC_TREE_ANIMATION              5001
#define IDC_FACE_MATERIAL               5001
#define IDC_CHECK1                      5002
#define IDC_OJBECT_ID                   5002
#define IDC_ITEM_WITH_HAIR              5002
#define IDC_WEA_LENSFLARE               5002
#define IDC_CHECK_COMMON_SPIRIT_STONE   5002
#define IDC_TAGGING                     5002
#define IDC_CHECK_CLUMP_HIDE_END_TIME   5002
#define IDC_CHECK_HIDE_CASTING_EFFECT   5002
#define IDC_DONOTCULL                   5002
#define IDC_CHECK_USE_HUMAN             5002
#define IDR_HTML_SETFACE                5003
#define IDC_WEA_SHOWSTAR                5003
#define IDC_CHECK_CLUMP_SHOW_START_TIME 5003
#define IDC_ALWAYS_SHOW                 5003
#define IDC_CHECK_USE_ORC               5003
#define IDD_ANIM_FLAGS                  5004
#define IDC_OBJECT_ID                   5004
#define IDC_EDIT_OBJECT_ID              5004
#define IDC_WEA_SHOWBREATH              5004
#define IDC_CHECK_USE_HUMAN3            5004
#define IDC_CHECK_USE_MOONELF           5004
#define IDD_CHARACTER_ANIMATION         5005
#define IDC_CHECK5                      5005
#define IDC_WEA_MOON                    5005
#define IDD_TELEPORT_EDIT_GROUP         5007
#define IDC_WEATHER                     5008
#define IDC_WEATHER_EFFECT1             5009
#define IDD_CHARACTER_FACE              5009
#define IDC_WEATHER_EFFECT2             5010
#define IDC_BUTTON1                     5011
#define IDC_SET_WEATHER                 5011
#define IDC_BUTTON_SET_RIDER_HEIGHT     5011
#define IDC_SPECULAR_COLOR              5011
#define IDC_BLOCK_UPDATE                5011
#define IDD_DIALOG1                     5011
#define IDD_GACHA                       5011
#define IDC_BASE_COLOR                  5012
#define IDC_FACE_TEXTURE                5013
#define IDC_CHECK2                      5014
#define IDC_ITEM_WITH_FACE              5014
#define IDC_PLIGHT_OFF                  5014
#define IDC_WEA_PLIGHT_OFF              5014
#define IDC_CHECK_CHAR_ANIM_CAST        5014
#define IDC_CHECK_SIEGEWAR              5014
#define IDC_USE_BENDING                 5014
#define IDC_WEA_DISABLE_WEATHER_EFFECT  5015
#define IDC_AVATAR_ITEM                 5015
#define IDC_EDIT_ANIM_POINT             5016
#define IDC_EDIT_SET_RIDER_HEIGHT       5016
#define IDC_EDIT_RIDER_HEIGHT           5016
#define IDC_WEA_RESERVED_1              5016
#define IDC_WEA_RESERVED_2              5017
#define IDC_LIST_WHOLE_TELEPORT_POINT   5018
#define IDC_WEA_PLIGHT_OFF5             5018
#define IDC_WEA_RESERVED_3              5018
#define IDC_BUTTON_MOVETO_POINT         5019
#define IDC_RADIO1                      5019
#define IDC_BUTTON_MOVETO_GROUP         5020
#define IDC_RADIO2                      5020
#define IDC_BUTTON_CREATE_POINT         5021
#define IDC_RADIO3                      5021
#define IDC_EDIT_SW_BOX_WIDTH           5021
#define IDC_BUTTON_DELETE_POINT         5022
#define IDC_RADIO4                      5022
#define IDC_EDIT_SW_BOX_HEIGHT          5022
#define IDC_BUTTON_EDIT_POINT           5023
#define IDC_EDIT_SW_SPHERE_RADIUS       5023
#define IDC_LIST_GROUP_POINT            5024
#define IDC_LOOKAT_NODE                 5024
#define IDC_EDIT_GROUP_NAME             5025
#define IDC_BENDING_FACTOR              5025
#define IDC_EDIT_DESCRIPTION            5026
#define IDC_CHECK_SELF_DESTRUCTION_ATTACK_TYPE 5026
#define IDC_EDIT_POINT_NAME             5027
#define IDC_EDIT_CLUMP_HIDE_FADE_OUT_TIME 5027
#define IDC_CHECK_NON_PICKING_TYPE      5027
#define IDC_EDIT_CLUMP_HIDE_OFFSET_TIME 5028
#define IDC_EDIT_SW_COLLOBJ_OFFSET_X    5028
#define IDC_EDIT_CLUMP_HIDE_FADE_OUT_TIME2 5029
#define IDC_EDIT_CLUMP_SHOW_FADE_IN_TIME 5029
#define IDC_EDIT_SW_BOX_HEIGHT2         5029
#define IDC_EDIT_SW_COLLOBJ_OFFSET_Z    5029
#define IDC_OFFSET_X                    5029
#define IDC_EDIT_CLUMP_SHOW_OFFSET_TIME 5030
#define IDC_OFFSET_Y                    5030
#define IDC_LIST_GACHA                  5030
#define IDC_TELEPORT_GROUP_LIST         5031
#define IDC_OFFSET_X3                   5031
#define IDC_OFFSET_Z                    5031
#define IDC_SELECTED_GACHA              5031
#define IDC_TELEPORT_POINT_GROUP        5032
#define IDC_TELEPORT_POINT_TARGET       5033
#define IDC_TELEPORT_ADD_GROUP          5034
#define IDC_TELEPORT_REMOVE_GROUP       5035
#define IDC_TELEPORT_ADD_TARGET         5036
#define IDC_TELEPORT_REMOVE_TARGET      5037
#define IDC_TELEPORT_GROUP_ADD          5038
#define IDC_TELEPORT_GROUP_EDIT         5039
#define IDC_TELEPORT_GROUP_DELETE       5040
#define IDD_MAIN_UDA                    5632
#define IDC_COMBO_RENDER_TYPE           5633
#define IDC_COMBO_BLEND_MODE            5634
#define IDC_COMBO_ATOMIC_INDEX          5635
#define IDC_EDIT_INPUT                  6000
#define IDD_FACTOR                      6000
#define IDD_INPUT                       6001
#define IDD_EFFECT_LIST                 7000
#define IDC_DialogList                  7000
#define IDC_DialogSelect                7001
#define IDC_EDIT_UES_EID                7002
#define IDD_USE_EFFECT_SET              7002
#define IDC_DialogView                  7002
#define IDC_BUTTON_EID_FIND             7003
#define IDC_DialogReset                 7003
#define IDC_EDIT_UES_OFFSET_X           7004
#define IDD_EFFECT_CONDITION            7004
#define IDC_OK                          7004
#define IDC_EDIT_UES_OFFSET_Y           7005
#define IDD_EFFECT_LIST_FIND            7005
#define IDC_EDIT_UES_OFFSET_Z           7006
#define IDD_EFFECT_STATUS               7006
#define IDC_BUTTON_EID_RESET            7007
#define IDD_EFFECT_SCRIPT               7007
#define IDC_EDIT_UES_SCALE              7008
#define IDD_EFFECT_CONDITION_LIST       7008
#define IDC_EDIT_UES_PARENT_NODEID      7009
#define IDD_EFFECT_SS_CONDITION         7009
#define IDC_EDIT_UES_CUST_DATA          7010
#define IDD_EFFECT_STATUS_LIST          7010
#define IDC_EDIT_UES_GAP                7011
#define IDD_EFFECT                      7011
#define ID_USE_EFFECT_SET_APPLY         7012
#define IDD_EFFECT_LIST_MODAL           7012
#define IDC_COMBO_UES_INDEX             7013
#define IDD_ROTATION                    7013
#define IDD_EFFECT_HELP                 7014
#define IDC_BUTTON_SET_CONDITION_FLAGS  7015
#define IDC_BUTTON_SET_STATUS_FLAGS     7017
#define IDC_CHECK_COMMON_INIT           7017
#define IDC_EDIT_SOUND_NAME             7018
#define IDC_CHECK_CHAR_ANIM_WAIT        7018
#define IDC_BUTTON_SET_SOUND            7019
#define IDC_CHECK_CHAR_ANIM_WALK        7019
#define IDC_CHECK_CHAR_ANIM_RUN         7020
#define IDC_CHECK_CHAR_ANIM_ATTACK      7021
#define IDC_CHECK_CHAR_ANIM_STRUCK      7022
#define IDC_CHECK_ES_SET_DIRECTION      7023
#define IDC_CHECK_CHAR_TARGET_STRUCK    7023
#define IDC_BUTTON_SAVE                 7024
#define IDC_CHECK_CHAR_ANIM_DEAD        7024
#define IDC_CHECK_ES_SET_HIT_EFFECT     7025
#define IDC_CHECK_ES_SET_ONLY_TARGET    7026
#define IDC_EDIT_SCRIPT                 7026
#define IDC_CHECK_ES_SET_LOOP           7027
#define IDC_EDIT_CONDITION              7027
#define IDC_CHECK_ES_SET_ANIM_LOOP      7028
#define IDC_BUTTON_INPUT                7029
#define IDC_CHECK_ES_SET_FIRST_TARGET   7030
#define IDC_CHECK_SKILL_TARGET          7030
#define IDC_CHECK_ES_SET_CALC_DIST      7031
#define IDC_CHECK_CHARACTER_LEVEL_UP    7031
#define IDC_CHECK_CHARACTER_CREATE      7032
#define IDC_CHECK_SKILL_TARGET_TARGET   7032
#define IDC_BUTTON_OUTPUT               7033
#define IDC_BUTTON_OPEN_SS_CONDITION    7034
#define IDC_EDIT_STATUS                 7035
#define IDC_CHECK_OBJECT_WORK           7035
#define IDC_CHECK_ITEM_EQUIP            7036
#define IDC_TREE_EFFECT                 7036
#define IDC_CHECK_ITEM_USE              7037
#define IDC_CHECK_CHARACTER_LOGON       7037
#define IDC_BUTTON_ADD                  7037
#define IDC_CHECK_SS_FIRE               7038
#define IDC_CHECK_ITEM_SPIRIT_STONE     7038
#define IDC_BUTTON_REMOVE               7038
#define IDC_BUTTON_ADD2                 7038
#define IDC_CHECK_SS_WATER              7039
#define IDC_CHECK_COMMON_DESTROY        7039
#define IDC_CHECK_SS_AIR                7040
#define IDC_CHECK_CHAR_RESURRECTION     7040
#define IDC_EDIT_X                      7041
#define IDC_CHECK_SS_EARTH              7041
#define IDC_CHECK_CHARACTER_TRANSFORM   7041
#define IDC_EDIT_Y                      7042
#define IDC_CHECK_SS_MAGIC              7042
#define IDC_CHECK_COMMON_CHECK_TIME     7042
#define IDC_EDIT_Z                      7043
#define IDC_CHECK_SS_LIGHTENING         7043
#define IDC_BUUTON_APPLY                7044
#define IDC_CHECK_SS_POISON             7044
#define IDC_CHECK_SS_ICE                7045
#define IDC_EDIT_HELP                   7045
#define IDC_CHECK_SS_FIRE_TARGET        7046
#define IDC_CHECK_SS_WATER_TARGET       7047
#define IDC_CHECK_SS_AIR_TARGET         7048
#define IDC_CHECK_SS_EARTH_TARGET       7049
#define IDC_CHECK_SS_MAGIC_TARGET       7050
#define IDC_CHECK_SS_LIGHTENING_TARGET  7051
#define IDC_CHECK_SS_POISON_TARGET      7052
#define IDC_CHECK_SS_ICE_TARGET         7053
#define ID_CAD_ON_COMMAND_REMOVE_1      7095
#define ID_CAD_ON_COMMAND_DATA          7096
#define ID_CAD_ON_COMMAND_FLAGS         7097
#define ID_CAD_ON_COMMAND_REMOVE        7098
#define ID_CAD_ON_COMMAND_ADD           7099
#define ID_CAD_ON_COMMAND_START         8000
#define IDD_INSERT_BLOCKING_INFO        8001
#define IDD_EDIT_BLOCKING_INFO          8002
#define IDD_OPEN_EDIT_BLOCKING          8003
#define IDC_COMBO_BLOCKING_TYPE         8004
#define IDC_EDIT_NEW_INDEX              8005
#define IDC_CHECK_EDIT_BLOCKING_SCALE   8010
#define IDC_EDIT_TEMPLATE_DESCRIPTION   8010
#define IDC_CHECK_EDIT_BLOCKING_POSIT   8011
#define IDC_CHECK_EDIT_BLOCKING_RIGHT   8012
#define IDC_CHECK_EDIT_BLOCKING_UP      8013
#define IDC_CHECK_EDIT_BLOCKING_AT      8014
#define IDC_CHECK_EDIT_BLOCKING_ALL     8015
#define IDC_CHECK_EDIT_BLOCKING_NONE    8016
#define IDC_CHECK_EDIT_BLOCKING_HEIGHT  8017
#define IDC_COMBO_CUR_INDEX             8018
#define IDC_EDIT_BLOCKING_TYPE          8019
#define IDC_BUTTON_CHANGE_TYPE          8020
#define IDC_COMBO_HAS_BLOCKNIG_INDEX    8021
#define IDC_BUTTON_INSERT               8021
#define IDC_BUTTON_COPY_AND_INSERT      8022
#define IDC_BUTTON_DELETE               8023
#define IDD_DIALOG_AI2_TEMPLATE         8100
#define IDC_AI2_AdjustWarriorEdit       8101
#define IDD_DIALOG_AI2                  8102
#define IDC_AI2TemplateCombo            8103
#define IDC_AI2_AdjustArcherEdit        8104
#define IDD_Edit_ConditonTable          8105
#define IDC_AI2TemplateAddButton        8106
#define IDC_AI2_AdjustMageEdit          8107
#define IDC_AI2TemplateUpdateButton     8108
#define IDC_AI2_AddUseItemButton        8109
#define IDC_AI2_AddUseSkillButton       8110
#define IDC_AI2_DeleteUseItemButton     8111
#define IDC_AI2_DeleteUseSkillButton    8112
#define IDC_AI2_UseItemList             8113
#define IDC_AI2_UseSkillList            8114
#define IDC_AI2_AdjustMonkEdit          8115
#define IDC_AI2_AdjustTryDebuffEdit     8116
#define IDC_AI2_AdjustHealEdit          8117
#define IDC_AI2_AdjustBuffEdit          8118
#define IDC_AI2_AdjustDemageEdit        8119
#define IDC_AI2_AdjustTryAttackEdit     8120
#define IDC_AI2_AdjustDebuffEdit        8121
#define IDC_AI2_AdjustOKButton          8122
#define IDC_TargetParameterCombo        8123
#define IDC_AI2_AdjustCancelButton      8124
#define IDC_PercentCombo                8125
#define IDC_OperatorCombo               8126
#define IDC_ConditionCheckCombo         8128
#define IDC_EditTableOKButton           8129
#define IDC_EditTableCancelButton       8130
#define IDC_ComboBox                    8131
#define IDC_ParameterEdit               8132
#define IDC_TimerEdit                   8133
#define IDC_ProbableEdit                8134
#define IDC_AI2TemplateNameEdit         8135
#define IDC_AI2TemplateSelectButton     8136
#define IDC_AI2TemplateRemoveButton     8137
#define IDC_AI2ExitButton               8138
#define IDC_AI2_UpdateUseItemButton     8139
#define IDC_AI2_UpdateUseSkillButton    8140
#define IDD_EVENT_QUEST                 8501
#define IDC_QUEST_LIST                  8502
#define IDC_HWATER_EDIT_HEIGHT0         9000
#define IDD_HWATER_DIALOG               9000
#define IDD_LOD_LIST                    9001
#define IDC_HWATER_EDIT_HEIGHT1         9001
#define IDC_HWATER_EDIT_HEIGHT2         9002
#define IDC_LIST_CLUMP_LIST             9003
#define IDC_HWATER_EDIT_HEIGHT3         9003
#define IDD_LOD_DISTANCE                9004
#define IDC_HWATER_EDIT_SPEED0          9004
#define IDD_LOD_STR                     9005
#define IDC_HWATER_EDIT_SPEED1          9005
#define IDD_LOD_DLG                     9006
#define IDC_HWATER_EDIT_SPEED2          9006
#define IDC_HWATER_EDIT_SPEED3          9007
#define IDC_HWATER_EDIT_DIRX0           9008
#define IDC_HWATER_EDIT_DIRX1           9009
#define IDC_EDIT_LOD_INDEX              9010
#define IDC_HWATER_EDIT_DIRX2           9010
#define IDC_HWATER_EDIT_DIRX3           9011
#define IDC_CHECK_TRANSFORM_GEOMETRY    9012
#define IDC_EDIT_DISTANCE_0             9012
#define IDC_HWATER_EDIT_DIRY0           9012
#define IDC_BUTTON_EDIT_LOD_FIND        9013
#define IDC_EDIT_DISTANCE_1             9013
#define IDC_HWATER_EDIT_DIRY1           9013
#define IDC_EDIT_LOD_FIND               9014
#define IDC_EDIT_DISTANCE_2             9014
#define IDC_HWATER_EDIT_DIRY2           9014
#define IDC_EDIT_DISTANCE_3             9015
#define IDC_HWATER_EDIT_DIRY3           9015
#define IDC_CHECK_BILLBOARD             9016
#define IDC_EDIT_DISTANCE_4             9016
#define IDC_HWATER_EDIT_ID              9016
#define IDC_LIST_LOD_DLG                9017
#define IDC_HWATER_EDIT_TEX_X0          9017
#define IDC_CHECK_YAXIS                 9018
#define IDC_HWATER_EDIT_TEX_Y0          9018
#define IDC_CHECK_USE_ATOMIC_INDEX      9019
#define IDC_HWATER_EDIT_TEX_X1          9019
#define IDC_COMBO_LODDLG_INDEX          9020
#define IDC_HWATER_EDIT_TEX_Y1          9020
#define IDC_COMBO_DISTANCE_TYPE         9021
#define IDC_HWATER_EDIT_COLOR_RED       9021
#define IDC_EDIT_MAX_DISTANCE           9022
#define IDC_HWATER_EDIT_COLOR_GREEN     9022
#define IDC_HWATER_EDIT_COLOR_BLUE      9023
#define IDC_HWATER_BUTTON_BUMP          9024
#define IDC_HWATER_EDIT_BUMPMAP         9025
#define IDC_HWATER_BUTTON_FRESNEL       9026
#define IDC_HWATER_EDIT_FRESNELMAP      9027
#define IDC_HWATER_EDIT_REFLECTION_WEIGHT 9028
#define IDC_HWATER_EDIT_ALPHA_MIN       9029
#define IDC_HWATER_EDIT_ALPHA_MAX       9030
#define IDC_HWATER_EDIT_ALPHA_DEC_HEIGHT 9031
#define IDC_HWATER_EDIT_WAVE_MIN        9032
#define IDC_HWATER_EDIT_WAVE_MAX        9033
#define IDC_HWATER_EDIT_WAVE_DEC_HEIGHT 9034
#define IDC_HWATER_EDIT_VERTEXPERTILE   9035
#define IDC_BASE_COLOR_R                9036
#define IDC_BASE_COLOR_G                9037
#define IDC_BASE_COLOR_B                9038
#define IDD_ANIMATION_PROPERTY          10000
#define IDC_CHECK_ANIM_LOOP             10001
#define IDD_CHAR_ANIMATION              10002
#define IDC_CHECK_ANIM_BLEND            10002
#define IDD_SET_SUB_ANIM                10003
#define IDC_EDIT_ANIM_PREFERENCE        10004
#define IDD_CHAR_HAS_ANIM               10005
#define IDC_CHECK_ANIM_LINK             10005
#define IDD_SET_CHAR_LINK_ANIM          10006
#define IDC_EDIT_ANIM_ACTIVE_RATE       10006
#define IDC_TREE_ANIMATION_LIST         10007
#define IDC_EDIT_CUST_ANIM_TYPE         10007
#define IDD_AGCMEVENTEFFECT_CHAR_ANIM_ATTACHED_DATA 10007
#define IDC_COMBO_SUB_ANIM_TYPE         10008
#define IDD_CHAR_ANIM_CUST_FLAGS        10008
#define IDC_EDIT_ANIM_CUST_ANIM_POINT   10008
#define IDC_CHAR_HAS_ANIM_LIST          10009
#define IDC_LINK_ANIM_LIST              10010
#define IDC_COMBO_SOUND_DATA_INDEX      10013
#define IDC_EDIT_SOUND_FILE_NAME        10014
#define IDC_BUTTON_SET_SOUND_FILE_NAME  10015
#define IDC_COMBO_SOUND_DATA_CONDITION  10016
#define IDC_BUTTON_APPLY                10017
#define IDC_BUTTON_RESET_SOUND_DATA     10018
#define IDC_CHECK_LOOP                  10019
#define IDC_EDIT_BLEND_ANIM_NAME        10019
#define IDC_BUTTON_CUSTOM_FLAGS         10020
#define IDC_BUTTON_SET_BLEND_ANIM       10020
#define IDC_BUTTON_REMOVE_BLEND_ANIM    10021
#define IDC_EventAuctionApplyButton     11000
#define IDD_OBJECT_TYPE                 11000
#define IDC_EventAuctionCancelButton    11001
#define IDD_EventAuctionDialog          11001
#define IDC_EventAuctionStatic          11002
#define IDC_EventAuctionExitButton      11003
#define IDC_EDIT_PRE_LIGHT_RED          11029
#define IDC_EDIT_PRE_LIGHT_GREEN        11030
#define IDC_EDIT_PRE_LIGHT_BLUE         11031
#define IDC_EDIT_PRE_LIGHT_ALPHA        11032
#define IDC_CHECK_PRE_LIGHT             11076
#define IDC_CHECK_LIGHT                 11078
#define IDC_CHECK_AMBIENT               11080
#define IDC_CHECK_ALPHA                 11081
#define IDC_CHECK_RENDER_UDA            11082
#define IDC_CHECK_NO_CAMERA_ALPHA       11083
#define IDC_CHECK_BLOCKING              11084
#define IDC_CHECK_RIDABLE               11085
#define IDC_CHECK_FADE                  11086
#define IDC_CHECK_IS_SYSTEM_OBJECT      11087
#define IDC_CHECK_SHADOW                11088
#define IDC_CHECK_ALPHA_FUNC            11089
#define IDC_CHECK_OCCLUDER              11090
#define IDC_EDIT_CATEGORY               15400
#define IDC_BUTTON_SET_CATEGORY         15401
#define IDC_BUTTON_REMOVE_BASE_CLUMP    15402
#define IDD_OBJECT                      15402
#define IDC_EDIT_STRING                 15402
#define IDD_OBJECT_LIST                 15403
#define IDC_BUTTON_REMOVE_COLLISION_CLUMP 15403
#define IDC_EDIT_BASE_CLUMP             15404
#define IDC_BUTTON_SET_BASE_CLUMP       15405
#define IDC_BUTTON_REMOVE_INIT_ANIM     15406
#define IDD_EDIT                        15406
#define IDC_COMBO_GROUP_INDEX           15407
#define IDC_BUTTON_GROUP_ADD            15408
#define IDC_EDIT_TEMPLATE_NAME          15409
#define IDC_EDIT_INIT_ANIM_SPEED        15410
#define IDC_EDIT_PICKING_NODE_INDEX     15410
#define IDC_EDIT_PICKING_NODE_INDEX1    15410
#define IDC_BUTTON_REMOVE_PICK_CLUMP    15411
#define IDC_EDIT_PICKING_NODE_INDEX2    15411
#define IDC_EDIT_COLLISION_CLUMP        15412
#define IDC_EDIT_PICKING_NODE_INDEX3    15412
#define IDC_BUTTON_SET_COLLISION_CLUMP  15413
#define IDC_EDIT_PICKING_NODE_INDEX4    15413
#define IDC_EDIT_INIT_ANIM              15414
#define IDC_EDIT_PICKING_NODE_INDEX5    15414
#define IDC_BUTTON_SET_INIT_ANIM        15415
#define IDC_EDIT_PICKING_NODE_INDEX6    15415
#define IDC_EDIT_PICK_CLUMP             15416
#define IDC_BUTTON_GROUP_REMOVE         15417
#define IDC_BUTTON_SET_PICK_CLUMP       15418
#define IDC_TREE_OBJECT_LIST            15438
#define IDC_EDIT_UI_IMAGE               15602
#define IDC_BUTTON_SET_UI_IMAGE         15603
#define IDC_EDIT_SECOND_CLUMP           15604
#define IDC_BUTTON_SET_SECOND_CLUMP     15605
#define IDC_EDIT_SMALL_UI_IMAGE         15606
#define IDC_BUTTON_SET_SMALL_UI_IMAGE   15607
#define IDC_COMBO_ITEM_PART             15608
#define IDC_EDIT_STACKABLE_NUM          15610
#define IDC_COMBO_ITEM_KIND             15611
#define IDC_EDIT_FIELD_CLUMP            15612
#define IDC_BUTTON_SET_FIELD_CLUMP      15613
#define IDC_COMBO_ITEM_TYPE             15614
#define IDD_ITEM                        15615
#define IDC_COMBO_ITEM_WTYPE            15615
#define IDC_CHECK_EQUIP_TWO_HANDS       15616
#define IDC_EDIT_LIGHT_FIRST_COLOR      15617
#define IDD_ITEM_LIST                   15618
#define IDC_LIST_ITEM_LIST              15618
#define IDC_BUTTON_REMOVE_SECOND_CLUMP  15618
#define IDC_BUTTON_REMOVE_FIELD_CLUMP   15619
#define IDC_BUTTON_REMOVE_UI_IMAGE      15620
#define IDC_BUTTON_REMOVE_SMALL_UI_IMAGE 15621
#define IDC_COMBO_ITEM_USABLE_TYPE      15622
#define IDC_COMBO_ITEM_OTHER_TYPE       15623
#define IDC_COMBO_ITEM_SPIRIT           15624
#define IDC_LIGHT_SYSTEM                15625
#define IDC_EDIT_LIGHT_SECOND_COLOR     15626
#define IDC_EDIT_STACKABLE_NUM4         15627
#define IDC_EDIT_LIGHT_GAP              15627
#define IDC_EDIT_BSPHERE_CENTER_X       15629
#define IDC_EDIT_BSPHERE_CENTER_Y       15630
#define IDC_EDIT_BSPHERE_CENTER_Z       15631
#define IDC_EDIT_BSPHERE_RADIUS         15632
#define IDC_BUTTON_GENERATE_BSPHERE     15633
#define IDD_WATER_DLG                   17000
#define IDC_WATER_BUTTON_L1FILE         17001
#define IDC_WATER_EDIT_STATUSID         17002
#define IDC_WATER_EDIT_L1FILE           17003
#define IDC_WATER_BUTTON_WAVE           17004
#define IDC_WATER_EDIT_WAVEFILE         17005
#define IDC_WATER_BUTTON_L1COLOR        17006
#define IDC_WATER_EDIT_L1RED            17007
#define IDC_WATER_EDIT_L1GREEN          17008
#define IDC_WATER_EDIT_L1BLUE           17009
#define IDC_WATER_EDIT_L1ALPHA          17010
#define IDC_WATER_EDIT_L1V              17011
#define IDC_WATER_EDIT_L1TSIZE          17012
#define IDC_BMODE_RADIO1                17013
#define IDC_BMODE_RADIO2                17014
#define IDC_BMODE_RADIO3                17015
#define IDC_BMODE_RADIO4                17016
#define IDC_BMODE_RADIO5                17017
#define IDC_BMODE_RADIO6                17018
#define IDC_BELNDOP_RADIO0              17019
#define IDC_BELNDOP_RADIO1              17020
#define IDC_BELNDOP_RADIO2              17021
#define IDC_BLENDOP_STATIC              17022
#define IDC_WATER_EDIT_L1U              17023
#define IDC_WATER_BUTTON_WAVECOLOR      17024
#define IDC_WATER_EDIT_WAVERED          17025
#define IDC_WATER_EDIT_WAVEGREEN        17026
#define IDC_WATER_EDIT_WAVEWIDTH        17027
#define IDC_WATER_EDIT_WAVEBLUE         17028
#define IDC_WATER_EDIT_WAVEHEIGHT       17029
#define IDC_WATER_EDIT_WAVEMINNUM       17030
#define IDC_WATER_EDIT_WAVEMAXNUM       17031
#define IDC_BMODE_RADIO7                17050
#define IDC_BMODE_RADIO8                17052
#define IDC_BMODE_RADIO9                17053
#define IDC_BMODE_RADIO10               17054
#define IDC_BMODE_RADIO11               17055
#define IDC_WATER_BUTTON_L2FILE         17059
#define IDC_WATER_EDIT_L2V              17062
#define IDC_WATER_EDIT_L2FILE           17064
#define IDC_WATER_EDIT_L2U              17069
#define IDC_WATERTYPE_RADIO0            17070
#define IDC_WATERTYPE_RADIO1            17071
#define IDC_BLENDOP_STATIC3             17072
#define IDC_WATER_EDIT_WAVELIFETIME     17073
#define IDC_WATER_EDIT_WAVESCALEX       17074
#define IDC_WATER_EDIT_WAVESCALEZ       17075
#define IDC_SPAWN_X                     21999
#define IDD_DIALOG_SPAWN                22000
#define IDC_SPAWN_Y                     22001
#define IDC_SPAWN_Z                     22002
#define IDC_SPAWN_MAX                   22003
#define IDC_SPAWN_CHARACTERS            22006
#define IDC_SPAWN_CHARACTER             22007
#define IDC_SPAWN_RATE                  22008
#define IDC_SPAWN_ADD_CHAR              22009
#define IDC_SPAWN_DEL_CHAR              22010
#define IDC_SPAWN_RADIUS                22011
#define IDC_SPAWN_UPD_CHAR              22012
#define IDC_SPAWN_GROUP_TREE            22013
#define IDC_SPAWN_GROUP_MIN             22014
#define IDC_SPAWN_GROUP_MAX             22015
#define IDC_SPAWN_GROUP_MAX2            22016
#define IDC_SPAWN_GROUP_ADD             22017
#define IDC_SPAWN_GROUP_DELETE          22018
#define IDC_SPAWN_GROUP_UPDATE          22019
#define IDC_SPAWN_NAME                  22020
#define IDC_SPAWN_GROUP_NAME            22021
#define IDC_SPAWN_SET_GROUP             22022
#define IDC_SPAWN_EDIT_CONDITION        22023
#define IDC_SPAWN_MIN_FACTOR            22032
#define IDC_SPAWN_MAX_FACTOR            22033
#define IDC_SPAWN_EVENT                 22037
#define IDC_ItemDropCloseButton         22121
#define IDC_ItemCount0Edit              22122
#define IDC_ItemCount1Edit              22123
#define IDC_ItemCount2Edit              22124
#define IDC_ItemCount3Edit              22125
#define IDC_ItemCount4Edit              22126
#define IDC_ItemCount5Edit              22127
#define IDC_ItemCount6Edit              22128
#define IDC_ItemCount7Edit              22129
#define IDC_ItemCount8Edit              22130
#define IDC_ItemCount9Edit              22131
#define IDC_DropRateEdit                22132
#define IDC_RuneCount0Edit              22133
#define IDC_RuneCount1Edit              22134
#define IDC_RuneCount2Edit              22135
#define IDC_RuneCount3Edit              22136
#define IDC_RuneCount4Edit              22137
#define IDC_RuneCount5Edit              22138
#define IDC_RuneCount6Edit              22139
#define IDC_RuneCount7Edit              22140
#define IDC_RuneCount8Edit              22141
#define IDC_RuneCount9Edit              22142
#define IDC_ItemDropAddUpdateButton     22143
#define IDC_EquipItemCount0Edit         22144
#define IDC_ItemCount10Edit             22145
#define IDC_RuneCount10Edit             22146
#define IDC_FreeForAllRadio             22147
#define IDC_CommonRadio                 22148
#define IDC_RareRadio                   22149
#define IDC_SpecialRadio                22150
#define IDC_DropItemList                22151
#define IDC_DropItemDeleteButton        22152
#define IDC_AddDropItemTemplateButton   22153
#define IDC_EquipRateEdit               22154
#define IDC_MinQuantityEdit             22155
#define IDC_AddDropItemNameEdit         22156
#define IDC_JackpotRateEdit             22157
#define IDC_UpdateDropItemTemplateButton 22158
#define IDC_JackpotPieceEdit            22159
#define IDC_RemoveDropItemTemplateButton 22160
#define IDC_MaxQuantityEdit             22161
#define IDC_RuneOptDamageEdit           22162
#define IDC_DropItemTemplateCombo       22163
#define IDC_RuneOptMinDamageEdit        22164
#define IDC_RuneOptMaxDamageEdit        22165
#define IDC_RuneOptAttackPoint          22166
#define IDC_RuneOptMinAttackPoint       22167
#define IDC_RuneOptMaxAttackPoint       22168
#define IDC_RuneOptDefenseRate          22169
#define IDC_RuneOptMinDefenseRate       22170
#define IDC_RuneOptMaxDefenseRate       22171
#define IDC_RuneOptDefensePoint         22172
#define IDC_RuneOptMinDefensePoint      22173
#define IDC_RuneOptMaxDefensePoint      22174
#define IDC_EquipItemCount1Edit         22175
#define IDC_SelectDropItemTemplateButton 22176
#define IDC_EquipItemCount2Edit         22177
#define IDC_SelectedDropItemTemplateList 22178
#define IDC_EquipItemCount3Edit         22179
#define IDC_DeleteSelectedDropItemTemplateButton 22180
#define IDC_RuneOptHP                   22181
#define IDC_RuneOptMinHP                22182
#define IDC_RuneOptMaxHP                22183
#define IDC_RuneOptMP                   22184
#define IDC_RuneOptMinMP                22185
#define IDC_RuneOptMaxMP                22186
#define IDC_RuneOptSP                   22187
#define IDC_RuneOptMinSP                22188
#define IDC_RuneOptMaxSP                22189
#define IDC_RuneOptHPRegen              22190
#define IDC_RuneOptMinHPRegen           22191
#define IDC_RuneOptMaxHPRegen           22192
#define IDC_RuneOptMPRegen              22193
#define IDC_RuneOptMinMPRegen           22194
#define IDC_RuneOptMaxMPRegen           22195
#define IDC_RuneOptSPRegen              22196
#define IDC_RuneOptMinSPRegen           22197
#define IDC_RuneOptMaxSPRegen           22198
#define IDC_RuneOptAttackSpeed          22199
#define IDC_RuneOptMinAttackSpeed       22200
#define IDC_RuneOptMaxAttackSpeed       22201
#define IDC_EquipItemCount4Edit         22202
#define IDC_EquipItemCount5Edit         22203
#define IDC_EquipItemCount6Edit         22204
#define IDC_SPAWN_TemplateCombo         22205
#define IDC_EquipItemCount7Edit         22206
#define IDC_SPAWN_AddButton             22207
#define IDC_EquipItemCount8Edit         22208
#define IDC_SPAWN_UpdateButton          22209
#define IDC_EquipItemCount9Edit         22210
#define IDC_SPAWN_RemoveButton          22211
#define IDC_EquipItemCount10Edit        22212
#define IDC_SPAWN_NameEdit              22213
#define IDC_DropItemSelectEdit          22214
#define IDC_DropItemSelectList          22215
#define IDC_SPAWN_SelectButton          22216
#define IDC_Combo_DropCategory          22217
#define IDC_List_DropInfo               22218
#define IDC_Edit_DropRate               22219
#define IDC_Static_DropInfo             22220
#define IDD_DIALOG_DROP_TEMPLATE_DLG    22301
#define IDD_DIALOG_DROP_ITEM            30000
#define IDD_EVENT_NATURE_DLG            30500
#define IDD_TEMPLATE_SELECT_DLG         30501
#define IDD_HSVCONTROL_RGB_INPUT_DLG    30502
#define IDD_TEMPLATE_NAME_DLG           30503
#define IDD_FARCLIPPLANE                30504
#define IDD_SKYSETTING                  30505
#define IDD_HSVINPUT                    30506
#define IDC_SPOID                       30507
#define IDD_EFFECT_EDIT_DIALOG          30508
#define IDB_TEXTURE_BACKGROUND          30509
#define IDD_NPCDialogTemplateSelectDlg  30509
#define IDD_NPCTradeTemplateSelectDlg   31000
#define IDC_WEATHER_TEMPLATE_COMBO      31001
#define IDC_NPCTradeTemplateCombo       31002
#define IDD_SKILL_MASTER_DIALOG         31003
#define IDC_RANGE                       31004
#define IDD_FILE_LIST                   31005
#define IDC_R                           31006
#define IDC_NPCTradeTemplateSelectButton 31007
#define IDD_SHRINE_DIALOG               31008
#define IDC_G                           31009
#define IDC_B                           31010
#define IDC_NPCTradeTemplateOKButton    31011
#define IDC_NPCTradeTemplateCancelButton 31012
#define IDC_TEMPLATE_LIST               31101
#define IDC_ADD_TEMPLATE                31102
#define IDC_REMOVE_TEMPLATE             31103
#define IDC_EDIT_TEMPLATE               31104
#define IDC_RENAME_TEMPLATE             31105
#define IDB_HSV_TABLE                   31201
#define IDC_NAME                        31301
#define IDC_FOG_DISTANCE_SLIDER         31402
#define IDC_FOG_DISTANCE                31404
#define IDC_FOG_FARCLIP                 31406
#define IDC_FOG_FARCLIP_SLIDER          31408
#define IDC_STOPTIME                    31409
#define IDC_TIMEZONE                    31410
#define IDC_CLOUD_TEXTURE1              31413
#define IDC_CLOUD_TEXTURE2              31415
#define IDC_CIRCUMSTANCE_TEXTURE        31417
#define IDC_IMAGE_PREVIEW               31418
#define IDC_TEXTURELIST                 31419
#define IDC_SUN_TEXTURE                 31420
#define IDC_CLOUDSPEED1                 31421
#define IDC_CLOUDSPEED2                 31423
#define IDC_CLOUD1_COLOR                31425
#define IDC_CLOUD2_COLOR                31427
#define IDC_CIRCUMSTANCE_COLOR          31429
#define IDC_SKYRADIUS                   31430
#define IDC_SUN_COLOR                   31431
#define IDC_SETFOG                      31433
#define IDC_HSVCONTROL                  31434
#define IDC_HSV_SKYTOP                  31435
#define IDC_HSV_SKYBOTTOM               31436
#define IDC_HSV_DIRECTIONAL             31437
#define IDC_HSV_AMBIENT                 31438
#define IDC_HSV_FOG                     31439
#define IDC_EFFECTINTERVAL              31440
#define IDC_AMBIENT_EFFECT_LIST         31441
#define IDC_EFFECT_ADD                  31442
#define IDC_EFFECT_DELETE               31443
#define IDC_EFFECT_EDIT                 31445
#define IDC_CLOUD1_ALPHA                31447
#define IDC_CLOUD2_ALPHA                31448
#define IDC_CIRCUMSTANCE_ALPHA          31449
#define IDC_B_TEXT                      31450
#define IDC_CIRCUMSTANCE_ALPHA2         31450
#define IDC_SUN_ALPHA                   31450
#define IDC_EFFECTEDIT                  31452
#define IDC_USE_COLOR                   31454
#define IDC_USE_CLOUD                   31455
#define IDC_USE_FOG                     31456
#define IDC_USE_EFFECT                  31457
#define IDC_USE_LIGHT                   31458
#define IDC_BACKGROUNDMUSIC             31460
#define IDC_BROWSE                      31461
#define IDC_BGM                         31462
#define IDC_BACKGROUND_TITLE            31463
#define IDC_TYPE_SKY                    31465
#define IDC_TYPE_EFFECT                 31466
#define IDC_TYPE_BGM                    31467

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        5012
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         5032
#define _APS_NEXT_SYMED_VALUE           5004
#endif
#endif
