PLUGIN = rtgcond

# Who are the maintainers ?
MAINTAINERS = adamj

# since this tool contains multiple object files - define the extra ones
# here. The standard ones are added by 'maketool'


ifndef BASEDIR
BASEDIR = $(CURDIR)/../..
endif
include $(BASEDIR)/makeincl/maketool
