#if (!defined(RPPLUGIN_H))
#define RPPLUGIN_H

/*
 * This is a required file for each plugin. It should be generated by the
 * plugin vendor. The information contained in this file should be unique
 * derived from the vendor id / name to prevent conflict with other plugins
 */

#if (defined(RWDEBUG) && !defined(RPERROR_H))
extern long _rtLtMapStackDepth;
#define RWDEBUGSTACKDEPTH _rtLtMapStackDepth
#endif /* (defined(RWDEBUG) !defined(RPERROR_H)) */

/* rwPLUGIN_ID must be defined in order to use the RenderWare debug/error
 * mechanism
 */

#define rwPLUGIN_ID            rwID_AMBOCCLMAPPLUGIN
//#define rwPLUGIN_ERRFUNC      _rwdb_CriterionLTMAPTOOL
//#define rwPLUGIN_ERRENUM     e_rwdb_CriterionLTMAPTOOL
//#define rwPLUGIN_ERRENUMLAST e_rwdb_CriterionLTMAPTOOLLAST

#endif /* (!defined(RPPLUGIN_H)) */
